### ISSUE TITLE
Update dataset gene sets csv when dataset gene set linkage is updated

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/corpora-data-portal#1005]
## Need
To ensure that the csv of gene sets stored in s3 for a given dataset matches the gene sets linked to that dataset

## Approach (suggested)
- When a Post request is sent to `/dp/v1/datasets/{dataset_uuid}/gene_sets`, after the linkages in the database have been updated, call function created in [1003](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/1003) with list of gene set ids and the dataset_uri with _genesest.csv appended. 
- After the csv has been created/stored, if it doesnt exist create a row in DatasetArtifact table (of type GENE_SET_CSV) linking the dataset to the file. If the row already exists update the updated_at time.
- This should be done asynchronously to avoid blocking the request response.

## DOD
- when the gene sets linked to a dataset are updated the gene set csv for a dataset is also updated 
- Add an integration test to ensure both creation and updates (or overwrites) propagate through to the csv

**Comment by MDunitz** [comment]
@tihuan the creation of geneset links in the dataset will be synchronous. Its just the csv creation that will be async. Since we just overwrite the file each time I didnt think it would be an issue if further geneset linking was allowed at that time

**Comment by tihuan** [comment]
ooh got it! Sorry for missing the important part 😆 That makes total sense 😄 Thanks so much, @MDunitz 🚀 !

**Comment by brianraymor** [comment]
Per the [simplification](https://docs.google.com/document/d/15rQuHfjezUo0RcJ3xVoRuWLP6OQ9bqiGDanmczehJtE/edit#heading=h.h1v05pg02lhb) of gene sets, UX linking is no longer required. Closing.
