### ISSUE TITLE
Update collection gene set csv when gene sets are added to a collection

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/corpora-data-portal#1007]
## Need
- To update the gene set csv for a collection when new gene sets are added to the collection

## Approach
- add geneset_csv_uri field to collections table 
- migrate db
- On call to POST `/dp/v1/collections/{collection_uuid}/genesets`, after gene sets have been created and linked to the collection, pass the ids of all of the genesets linked to the collection to the function created in [1003](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/1003) along with {collection_id}/geneset.csv (as the s3 uri)
- set the geneset_csv_uri field on the collections table

## DOD
- Adding gene sets to a collection is propagated through to the collection gene set csv
- Add an integration test to ensure both creation and updates (or overwrites) work as intended 

This work is fairly similar to the work described in [1005](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/1005). You may want to work with the engineer on that ticket to avoid duplicating work.

**Comment by tihuan** [comment]
Similar to #1003, maybe a synchronous response! https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/1005

**Comment by MDunitz** [comment]
Closing due to updates in product priorities
