### ISSUE TITLE
[FE] Download all genesets for a collection 

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/corpora-data-portal#1009]
figma - https://www.figma.com/file/TKV4sJ00zWobEFkaNgklC3/Gene-Sets?node-id=25%3A367

Get the csv uri from GET `/dp/v1/collections/{collection_uuid}/genesets`

![Screen Shot 2021-03-22 at 23.28.22 copy.png](https://images.zenhubusercontent.com/5b4523ca3f1e7333c932b3b1/b9976e5f-93de-4693-adbd-389190a7fe46)

**Comment by tihuan** [comment]
We can also use https://www.papaparse.com/docs#json-to-csv to create the CSV for download 👌

**Comment by tihuan** [comment]
@MDunitz  Looks like Harley updated the download all button to the Gene Set Tab!

https://www.figma.com/file/TKV4sJ00zWobEFkaNgklC3/Gene-Sets?node-id=230%3A107

![Screen Shot 2021-03-30 at 11.14.15 AM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/daa13f1c-ced0-47b3-94c3-3d77e43d0b88)

**Comment by MDunitz** [comment]
Closing - no longer aligned with product requirements
