### ISSUE TITLE
[FE] Download a particular geneset for a collection

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/corpora-data-portal#1010]
figma - https://www.figma.com/file/TKV4sJ00zWobEFkaNgklC3/Gene-Sets?node-id=25%3A367

GET `/dp/v1/collections/{collection_uuid}/genesets` should return all of the gene set information. Convert the geneset selected by the user to a csv and download.

![Screen Shot 2021-03-22 at 23.28.22.png](https://images.zenhubusercontent.com/5b4523ca3f1e7333c932b3b1/afb6f771-4b1c-4eec-9f5d-1ca4e2d9fe5e)

**Comment by tihuan** [comment]
The [CSV library](https://www.papaparse.com/docs#json-to-csv) we use can convert JSON back to a CSV! But so far I can't tell what encoding it uses for the output. We'll probably need to dig into its source code to find out

**Comment by MDunitz** [comment]
Closing - No longer aligned with product direction
