### ISSUE TITLE
[SPIKE] Investigate out-of-memory failures that occur when converting an uploaded file

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#1018]
There have been a few persistent errors that have shown up while files are being converted from .h5ad to either .cxg, .loom, or .rds and they typically show up as an out-of-memory error. However, when the file is converted on a regular EC2 instance, there is no memory error. This issue is to investigate why these errors are occurring and come up with a solution.

https://chanzuckerbergteam.slack.com/archives/C01CPJURT0S/p1615415622189000 -- occurred while uploading 10+ Tabula Muris datasets. First guess was an issue with hitting Dropbox limits.

https://chanzuckerbergteam.slack.com/archives/C01CPJURT0S/p1616019680035500 -- occurred while converting from Anndata to Seurat. Separately a 60GB machine was not sufficient to convert the file though the memory size of the EC2 instances we use in Portal should be even bigger. Converting to a scipy sparse matrix fixed the issue. 

https://chanzuckerbergteam.slack.com/archives/C01CPJURT0S/p1616618497032100 -- occurred while converting a fairly small dataset (3GB) to Loom. Unclear why though an initial guess was that downloaded datasets are not getting cleaned up from the containers (see [this thread](https://chanzuckerbergteam.slack.com/archives/C01C310V70X/p1616632347028100)).

https://chanzuckerbergteam.slack.com/archives/C01CPJURT0S/p1617211537091800 --

> Which has an exit status of 0 but a "Reason: OutOfMemoryError: Container killed due to memory usage"
> And the logs show this:
> ERROR:__main__:Issue creating seurat.
> Traceback (most recent call last):
>   File "/backend/corpora/dataset_processing/process.py", line 363, in convert_file_ignore_exceptions
>     file_dir = converter(local_filename)
>   File "/backend/corpora/dataset_processing/process.py", line 323, in make_seurat
>     raise RuntimeError(f"Seurat conversion failed: {seurat_proc.stdout} {seurat_proc.stderr}")
> RuntimeError: Seurat conversion failed: b'' b'Loading required package: reticulate\n'

**Comment by Bento007** [comment]
#1030 increased the memory for each batch job. This has fixed the issue for now.

**Comment by maniarathi** [comment]
Given that we have increased the memory and we have introduced additional logging, does it seem reasonable to close this for now and investigate #1068 at a later point in time?

**Comment by Bento007** [comment]
I'd like to add some tooling to simplify testing the processing container before calling this one done.
