### ISSUE TITLE
CXG conversions not working for uploaded datasets

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#1042]
**Original Slack thread:** https://chanzuckerbergteam.slack.com/archives/C01CPJURT0S/p1617405681156300

**Stack trace:**
ERROR:__main__:Issue creating cxg.
Traceback (most recent call last):
File "/backend/corpora/dataset_processing/process.py", line 363, in convert_file_ignore_exceptions
file_dir = converter(local_filename)
File "/backend/corpora/dataset_processing/process.py", line 334, in make_cxg
raise RuntimeError(f"CXG conversion failed: {cxg_proc.stderr}")
RuntimeError: CXG conversion failed: b"Usage: cellxgene <options> COMMAND <args>\n\nError: No such command 'convert'.\n"

**Diagnosis:** we're installing from source code for the cellxgene package and some pretty large changes to rename the backends occurred in the last deployment which means that the current command to install is still installing the cellxgene _desktop_ application which does not contain logic about conversion since it is czi-hosted specific.

**Definition of Done:**
- [x] Update Dockerfile.processing_image to use the czi-hosted commands.
- [ ] Write an E2E test to ensure that the CXG conversion is occurring correctly.

**Comment by MDunitz** [comment]
a [PR](https://github.com/chanzuckerberg/corpora-data-portal/commit/651aa2f696e7f507304f549017ee700df53ae4fd)  was deployed to prod fixing the conversion issue. A separate [ticket](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/1067) was created for the E2E test.
