### ISSUE TITLE
Update the collections revisions page with dataset labels.

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#1086]
## Need
It must be obvious to curators what datasets are new, deleted, updated, or unchanged from the collection revision page.

[figma](https://www.figma.com/file/jZzZF9oO0YRMxmVRDxDHp3/Public-Revisions?node-id=441%3A122)

## Approach
- Using the list of datasets from a collection determine if each one should have a label.
- Apply the following label based on the figma model if the following criteria are met:
 - _Deleted_ if the dataset is published and tombstoned
 - _Update_ if the dataset is **not** published and original_uuid is **not** none.
 - No labels if the dataset is published and original_uuid is **not** none
 - _New_ if the dataset is **not** published and original_uuid is none.
 
## Definition of Done
- Show that all labels are correctly displayed for a deleted, unmodified, updated, and new dataset.
-  The labels are not displayed on the public collections page.

**Comment by Bento007** [comment]
@tihuan can you help us estimate this ticket.

**Comment by tihuan** [comment]
Sync'd with Seve on this! Thank you 🚀

**Comment by maniarathi** [comment]
What was the final consensus on this? I think the estimate didn't stick. 

Also I'm curious as to what the approach will be? @seve on the call you mentioned something about a new column? Is that the approach?

**Comment by seve** [comment]
> hmm I’m thinking the first column is using flex with space between already. So we’d just be swapping the dataset upload status icon with revision tag?
