### ISSUE TITLE
Default Cryptographic Secrets Stored in Source Code

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#1095]
**Description:**
Cryptographic secrets were found within the corpora-data-portal application source code. As this is an open source repository, any attacker or malicious insider would have access to these secrets. This may enable them to attack the cryptographic systems used by the application.
The assessment team found that the Flask secret key defaulted to a hard-coded secret of “OpenSesame” if a secrets file is not found (lines 39-48 of `corpora-data-portal-main/backend/chalice/api_server/app.py`, shown below).

![Screen Shot 2021-04-13 at 9.52.14 PM.png](https://images.zenhubusercontent.com/5c537006f3a9152a2050f2ad/4d665fd2-a0b5-409e-bf35-7179baca4b71)

The Flask secret key was used to sign session cookies, so anyone with access to this key would be able to impersonate other users and escalate privileges to a user with higher permissions.

While this currently has no impact on the production application when the auth_secret is successfully loaded, it is recommended practice not to set a default value for a secret. Ensuring that the testing environment loads secrets in the same manner as the production environment would lessen the chance of future code refactors or bad deployments causing the hard-coded secret to be used in production.

**Recommended Remediation:**
The assessment team recommends that the secrets for the testing environment are loaded in the same manner as for the production environment. If this is deemed impractical, then the application initialization code should only use the hardcoded variable when the testing environment is explicitly set, and fail to start the server otherwise.

**Comment by Bento007** [comment]
This is a very low risk issue. Closing for this reason.
