### ISSUE TITLE
bug(revisions): Disabling feature flag while revision is in progress leads to unexpected behavior

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/corpora-data-portal#1149]
## Describe the bug
If you disable a feature flag when a revision is in progress you'll see both the revision and the published collection in the my-collections page

Is this acceptable behavior?

**Comment by brianraymor** [comment]
This reads like an edge case to me.

**Comment by maniarathi** [comment]
Can we close as this is not something we are likely going to address in the near future?

**Comment by brianraymor** [comment]
Agree with @maniarathi. Closing.
