### ISSUE TITLE
Publish documentation for consumers about the data and metadata found at the data resource

### ISSUE THREAD

**Issue by jlzamanian** [chanzuckerberg/corpora-data-portal#116]
## Background:
This ticket is to fulfill [DCP 2.0 requirement M1.12](https://docs.google.com/document/d/1_0NCGdkLCKrJvZMlt5x5Df7RT7G929C-BcSI5wBnX4Y/edit#heading=h.dixwo7u4xv68)

## User Story
*When data consumers arrive at the HCA DCP 2.0 website, they will want access to documentation, written by HCA Data Ops, that explains the HCA DCC metadata schema so that data consumers can understand the data contained in the HCA.*

## Acceptance Criteria
- [ ] The documentation must describe the metadata schema so that the consumer can understand the data.
- [ ] The documentation must be published on the browser.

**Comment by ambrosejcarr** [comment]
@jlzamanian is the goal to have this information published on the browser?

**Comment by jlzamanian** [comment]
@ambrosejcarr That is the intention. Feel free to close or repurpose if it duplicates work detailed elsewhere.

**Comment by ambrosejcarr** [comment]
Perfect. 👍 

I adjusted it slightly to add the browser requirements and pulled in the user goal.
