### ISSUE TITLE
bug: Icons on the dataset page grow and shrink with window size.

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#1163]
## Describe the bug
On the cellxgene data portal page, the explorer icon and the download icon grow smaller and bigger as the window size changes. You can eventually scale the icon sizes down to be invisible.

## To Reproduce
1. Navigate to a collection dataset page
2. Change the size of the window to grow and shrink the icons.

## Expected behavior
The icon does not grow and shrink with window size

**Comment by maniarathi** [comment]
One other thing.. the icon sizes appear to be different on private collection pages versus public collection pages. Hopefully this fix also will solve that.
