### ISSUE TITLE
[SPIKE] Figure out dataset deletion problem

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/corpora-data-portal#1180]
Because we have the requirement that cellxgene Explorer links be evergreen (i.e. they do not change), we originally thought we could simply rename a newly added dataset to be the old dataset that it’s replacing. [S3 doesn’t allow us to do that](https://stackoverflow.com/questions/21184720/how-to-rename-files-and-folder-in-amazon-s3) and we didn’t know that.

Then the next logical step that was considered was to delete the old directory and replace it with the new ones. Unfortunately we have files that are larger than 5GB and this means that multi-part copy will kick in from S3 which is slow. This will likely hit our API limits (30 seconds) and our frontend is not set up to handle asynchronous API calls at the moment (this would require extra frontend engineering work).

**Next steps for this spike**:
- [x] Validate the time to copy over the largest datasets we currently have (i.e. larger than 5GB)
- [x] Madison to reach out to our AWS rep to figure out whether there is a workaround that they’re aware of. And she’s also reaching out to Bruce to get a second opinion.

**Likely outcome if AWS solutions don’t work out**:
Madison had been working on a “metadata API” design this sprint. This will likely be needed in order to ship revise in place which we didn’t expect previously. Essentially it will implement the ability for cellxgene Explorer to redirect so if it hits an evergreen link and the dataset changes, it redirects to the new dataset.

If the above is the correct solution, issues for the "metadata API" will be the outcome of this spike.

**Comment by Bento007** [comment]
Using this script to copy all of the files for dataset *0586711d-1e0f-4104-949c-74a2b7d075c5* in *corpora-data-staging*, it took 103.4213 sec for all files. The largest file being the loom file was 5.5GB in size and took 44.5876 sec to copy.

## Results
```
WARNING:__main__:func:'copy' args:[(s3.ObjectSummary(bucket_name='corpora-data-staging', key='0586711d-1e0f-4104-949c-74a2b7d075c5/local.h5ad'), s3.Object(bucket_name='corpora-data-staging', key='copy_test/local.h5ad')), {}] took: 34.7219 sec
WARNING:__main__:func:'copy' args:[(s3.ObjectSummary(bucket_name='corpora-data-staging', key='0586711d-1e0f-4104-949c-74a2b7d075c5/local.loom'), s3.Object(bucket_name='corpora-data-staging', key='copy_test/local.loom')), {}] took: 44.5876 sec
WARNING:__main__:func:'copy' args:[(s3.ObjectSummary(bucket_name='corpora-data-staging', key='0586711d-1e0f-4104-949c-74a2b7d075c5/local.rds'), s3.Object(bucket_name='corpora-data-staging', key='copy_test/local.rds')), {}] took: 23.7880 sec
WARNING:__main__:func:'main' args:[(), {}] took: 103.4213 sec
```
## Script
```python
#!/usr/bin/env python
import logging
from functools import wraps
from time import time
import boto3

logging.basicConfig(level=logging.WARN)
logger = logging.getLogger(__name__)


s3 = boto3.resource("s3", config=boto3.session.Config(signature_version="s3v4"))


def timing(f):
    @wraps(f)
    def wrap(*args, **kw):
        ts = time()
        result = f(*args, **kw)
        te = time()
        logger.warning('func:%r args:[%r, %r] took: %2.4f sec' % (f.__name__, args, kw, te-ts))
        return result
    return wrap


total = 0
def callback_generator(src, dest):
    global total
    total = 0
    def _callback(bytes_copied):
        global total
        total = total + bytes_copied
        logger.info(f"copied {total}/{src.size} from {src.key} to {dest.key}")
    return _callback


@timing
def copy(s3_src, s3_dst):
    copy_source = {
        'Bucket': s3_src.bucket_name,
        'Key': s3_src.key
    }
    s3_dst.copy(copy_source, Callback=callback_generator(s3_src, s3_dst))


@timing
def main():
    artifact_bucket = s3.Bucket("corpora-data-staging")
    prefix = "0586711d-1e0f-4104-949c-74a2b7d075c5"
    for s3_object in artifact_bucket.objects.filter(Prefix=prefix):
        new_key = "/".join(["copy_test", *s3_object.key.split("/")[1:]])
        new_object = artifact_bucket.Object(new_key)
        copy(s3_object, new_object)


if __name__ == "__main__":
    main()
```

**Comment by maniarathi** [comment]
Hey @morsecodist I wonder if you have any insight into faster copies between S3 to S3 when you were researching for s3parcp?

**Comment by maniarathi** [comment]
When you say S3 copies internally are pretty fast, do you have numbers by any chance? Running the AWS CLI command for example clocks in around 10s/GB which is still too slow for us (also validated by Trent's script above). It would have to get to about half that speed, I think, for us to be able to considering using it.

**Comment by morsecodist** [comment]
@maniarathi I didn't do any specific benchmarks but the numbers you mention are in line with what I observed. We do very little S3 copying and none of it blocks any user-facing operations so we considered this good enough. If copying faster is important to your application I'd be happy to coordinate setting up a multipart copy. Without bandwidth constraints it has the potential to be quite fast though I don't have any numbers unfortunately.

**Comment by maniarathi** [comment]
Closing as we have opted to do redirects instead of investing in fast deletions.
