### ISSUE TITLE
Create notification for upload failures in prod environment 

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/corpora-data-portal#1186]
The lack of an operational response was confusing to a UCSC curator who was waiting to be contacted after a conversion failure.

Per the [single-cell-eng thread](https://chanzuckerbergteam.slack.com/archives/C01CPJURT0S/p1620928817362000):
> It seems like she waited to let us know because she was waiting for a response from us based on the error massage

## Need 
When an upload fails we automatically tell the curator we will look into it. To do so, we need alerting so we are aware when an upload fails. 

## DOD
- Update the step function error handle to send a slack message (#single-cell-ops) to the curation channel when an upload job fails.
- Include a link to the batch process in the Slack alert.

**Comment by Bento007** [comment]
- turn off TFE notifiaction to single-cell-ops
- Update the step function error handle to send a slack message to the curation channel when an upload job fails.

**Comment by Bento007** [comment]
I need to add the slack webhook to the secret used by the processing container. I asked team-happy where that secret is populated. I'm still waiting for a response.
