### ISSUE TITLE
feat(Publish): Detect diffs between a revision and published collection

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#1189]
## Need
As a curator, I would like to know when I have made changes that are different from the original collection.

### Solution 1: published_at
Add `published_at` to `DbCollection`. This field is a timestamp that says when the collection was published, or empty if the collection has never been published. A revision would have the same `published_at` value as the original collection. We can detect if the user has modified the collection or its datasets if the `updated_at` time stamp for the collection or any of its children are greater than `published_at`.

This does not have the ability to detect if the user has actually made changes or submitted the same information again. This could confuse the user who may think they made changes when there is no visible difference. 

### Solution 2: Compare
Retrieve both the revision and the published collection and compare the fields. If they diverge we can alert the user. Some fields will naturally differ because of the revision process and must be ignored when comparing. These fields are `collection.visibility`, `dataset.collection_visibility`, `created_at`, and `update_at`. `dataset.original_uuid` should be compared with the published dataset with the matching `dataset.id`

## Definition of Done

- [ ] Solution 2
   - [ ] Compute revision diff at collection fetch time
   - [ ] Store revision diff boolean in react query store as an additional field on Collection entity

**Comment by Bento007** [comment]
## Spike
Determine how difficult it would be to compare the private and publish collection information on the frontend or backend.

**Comment by maniarathi** [comment]
@seve to add additional details in the definition of done.

**Comment by tihuan** [comment]
Already in prod!
