### ISSUE TITLE
feat(revision): Notify revision state for collection as a whole

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/corpora-data-portal#1190]
## Need

Users should know if they are viewing a revision and if any changes have been made to their collection since they initiated their revision.  Users should also not have the ability to publish their revision unless some change has been made

![image](https://user-images.githubusercontent.com/8716829/118554287-1be3a780-b716-11eb-9ef2-de491e0f1452.png)
![image](https://user-images.githubusercontent.com/8716829/118554361-30c03b00-b716-11eb-800b-36076075a39b.png)

[Figma Link](https://www.figma.com/file/jZzZF9oO0YRMxmVRDxDHp3/Public-Revisions?node-id=441%3A71)

## Approach

Utilize the method of display revision edit status that resolves from #1189 

## Definition of Done

• Users are notified if they're viewing a revision
• If the revision has been edited display that changes have been made and enable the publish revision button

**Comment by Bento007** [comment]
does this include changing the message that shows up when deleting the revision?
![Uploading Screen Shot 2021-05-17 at 6.18.44 PM.png…]()
