### ISSUE TITLE
Define which metadata should display in cellxgene

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/corpora-data-portal#121]
The current DCP Artifact contains a lot of metadata, only some of which is likely to be useful being displayed in the interactive project dataset (cellxgene) viewer.   Specifically, should the "DCP cellxgene" show all metadata that is inside the DCP loom files?  Or should it only display a subset (the "interesting" bits)?

There are many categorical metadata where:
* all cells have the _same_ value -- example: project.project-core.project_short_name
* or, all cells have a _unique_ value -- example: bundle_uuid
* or, the values are not very interesting to look at -- example: file_uuid, file_version, bundle_version, ...

Furthermore, all of this stuff is available in the project page - at least in theory.

In practice, only those metadata which help the user down-select interesting subsets of the data, explore distribution by annotation, etc, are helpful.

Task: define the list of metadata to display in cellxgene.  This could be a combination of rules/heuristics:
* black/white list of annotations (eg, do not show file_uuid)
* Do not display metadata where all cells have the same values
* Do not display metadata where all cells have different values

Note that this is a display convention - it does not change what metadata is in the Artifact or available for download -- simply what cellxgene displays.   It will also be configurable, so we can change it in the future.

@mckinsel @jychien - initially assigning to you on Ambrose' suggestion.   Ideally would like a rough draft of this for our next sprint.

**Comment by jahilton** [comment]
Our current suggestions are found [here](https://docs.google.com/spreadsheets/d/1wAPWTk0rVTeEPE_ndKK7NvYNjO_99D-1gOmcKD6xq1U/edit#gid=1348656151) in the **Matrix Cell Metadata** column

**Comment by bkmartinjr** [comment]
@jahilton - do I correctly understand this as the "white list" of annotations to show in the matrix view?   Do you also want any heuristic-driven decisions as suggested by @ambrosejcarr (eg, don't show single-value metadata)?  Or leave that to a second pass?

**Comment by parthshahva** [comment]
I'm sensing a possible disconnect here. @mckinsel said to copy over the loom files from DCP 1.0 for the now. We are waiting for the cell/expression part of the schema to be defined before we can start storing that data. Thus the loom files currently have DCP 1.0 entities/properties, but the whitelist above is for DCP 2.0 entities/properties.

@jahilton @ambrosejcarr @mckinsel can we go live with serving the DCP 1.0 metadata matrices or do we need to cut over as part of the requirements? If so, this puts additional priority on defining the cell/expression portion of the metadata schema.

**Comment by bkmartinjr** [comment]
good point @parthshahva.

That said, development is not currently blocked by this.  We just need to resolve before we finalize Artifact spec and build the ETLs.   For now, I'll add a simple whitelist which can be informed by this once it stabilizes.

**Comment by ambrosejcarr** [comment]
Application of the proposed heuristics could change my perspective, but
with the existing files, I have difficulty parsing more than half of the
field names and as a result I do not want to go live with the matrix files
as they are.

However, copying over the 1.0 files is sufficient to unblock downstream
development and UX research on portions of the system not related to the
schema and we should continue using them until we can swap to the 2.0
matrix files.

**Comment by jahilton** [comment]
Sounds like there is a path forward in short-term

But @bkmartinjr , yes that is a 'white list' as you said. I would definitely leave the heuristic-driven decisions to a later pass (I actually think a user will be confused if a field is there for 1 matrix, but not for another - so that needs to be carefully considered)

> can we go live with serving the DCP 1.0 metadata matrices or do we need to cut over as part of the requirements?

@parthshahva all metadata needs to be consistent before going live

**Comment by parthshahva** [comment]
Makes sense @jahilton. We can discuss the timeline for the rest of the schema required next week
