### ISSUE TITLE
Delete collection instead of Cancel Revision

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#1304]
If I start a revision and then decide to cancel, I see:

![Screen Shot 2021-07-28 at 2.51.15 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/58efccd2-a6bc-4332-9101-a1d71a1fe487)

If I then navigate to _My Collections_ and then continue the revision, I see:

![Screen Shot 2021-07-28 at 2.54.01 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/b64015ba-c10c-485a-a009-966dfa6022f8)

**Comment by brianraymor** [comment]
If I manually refresh, then the correct menu text is displayed.

**Comment by seve** [comment]
Same as #1309
