### ISSUE TITLE
If a published dataset is deleted, the dataset menu should be disabled 

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#1306]
If a curator deletes a published dataset, the dataset menu is still enabled, allowing a second deletion (?) or an update (?) of the dataset. The menu should be disabled in this case.

![Screen Shot 2021-07-28 at 3.07.26 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/29bc5b53-b8c8-4a74-8b31-8664e897b848)

**Comment by brianraymor** [comment]
Further, I might also suggest that the download and explore controls be disabled. We don't instantly remove the dataset as a visual clue of the revisions that have occurred for the collection.

**Comment by seve** [comment]
@hthomas-czi Should we just remove all three of those buttons for deleted datasets? Or disable? Disabling feels to me like there is a chance they will be enabled through some interaction, but once the dataset is disabled there's no more interactions that can be done on it.

If we do disable, should the "more" ellipses button be disabled or just the menu items in the pop up that results on interaction with the  more button

**Comment by hthomas-czi** [comment]
@seve I think we should disable them rather than remove them. All row buttons should be disabled, so the user wouldn't be able to open the drop down menu.

**Comment by brianraymor** [comment]
The related [figma](https://www.figma.com/file/jZzZF9oO0YRMxmVRDxDHp3/Public-Revisions?node-id=441%3A122)
