### ISSUE TITLE
Cannot create a private collection that includes a link?

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#1311]
1. `Create collection`
2. Add a link in the modal
3. Press `Create`. Nothing happens.
4. Delete the link. Press `Create`. The collection is created.

https://images.zenhubusercontent.com/228681195/e12ee7b9-5cd3-4b41-88f7-8725374003cb/screen_recording_2021_07_28_at_5_08_53_pm.mov

**Comment by seve** [comment]
Post to the backend fails with 400

Body:
```
{
"name":"asdasd",
"description":"asda",
"contact_name":"dasd",
"contact_email":"asd","
Name":"",
"DOI":"https:/doi.org/12313",
"links":[{"link_name":"","link_type":"DOI","link_url":"https:/doi.org/12313"}],"
data_submission_policy_version":"1.0"
}
```

Response:
```
{
  "detail": "Additional properties are not allowed ('Name', 'DOI' were unexpected)",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```

**Comment by seve** [comment]
Somehow, the link type and name fields are being appended to the payload

**Comment by seve** [comment]
It's not a frontend regression, I see the same request on prod.

**Comment by tihuan** [comment]
A PR is out to fix this! PTAL thank you 🙌 https://github.com/chanzuckerberg/corpora-data-portal/pull/1312
