### ISSUE TITLE
Deleting the last published dataset during a revision shows the "No datasets uploaded" UX

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#1313]
If I delete the last published dataset in a collection, the dataset should be labeled as "Deleted" and the `Publish` button disabled. In the example below, I'm shown the 
"No datasets uploaded" UX that  is shown when creating a new private collection ... until I refresh the page which then reverts to the UX appropriate for revisions.

https://images.zenhubusercontent.com/280546849/2a6d2611-5ea3-4504-857b-de3e2c6f2d4a/screen_recording_2021_07_29_at_10_36_38_am.mov

**Comment by tihuan** [comment]
this doesn't seem reproducible on staging anymore! PTAL again, @brianraymor 🙏 Thank you!

**Comment by tihuan** [comment]
nvm, to reproduce, we need to do the following steps quickly per @seve :

1. Start a new revision of a collection that only has one dataset
1. Delete the dataset ASAP!!

**Comment by brianraymor** [comment]
@tihuan - With other changes, this seems to be resolved. I'm unable to reproduce after multiple attempts.

**Comment by tihuan** [comment]
Awesome! Thanks so much for checking, @brianraymor 🙌
