### ISSUE TITLE
Design the file download experience

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/corpora-data-portal#157]
Dependencies **+ answers where I have them**:

1.) Can the URLs be generated on the fly, as user is selecting files + categories?
**According to @Bento007, no. We need a separate button/method by which user says they are ready for URLs to be generated.**

2.) The level of granularity of each URL
**Project-Organ-Assay-Species category + file type (.bam, .fastq, .csv.gz, .loom, .mtx.gz, -matrix.csv.gz, -cells.csv.gz, -genes.csv.gz)**

3.) Are we allowing download of whole project via a single URL?
**Yes and no. User must specify the file type(s) they want, then we bundle their selected file type(s) for all categories available within that project into a single URL.**

4.) Can user download all individually generated URLs as a line-delimited list in a single click?
**Yes.** 

This falls under epic #58

**Comment by liaprins-czi** [comment]
Here is the latest prototype exploring the download flow.

To do:
- [ ] Update to accommodate new technical feasibility mentioned in (1.) above.

**Comment by calvinnhieu** [comment]
Weighing in here:

1. True
2. True. However, I believe it is currently in-flux as to whether or not we will provide raw data via the Browser
3. This will not be available in the first iteration of the download flow, but is an important feature to improve usability that will likely follow shortly after.
4. Could you expand on this?

**Comment by liaprins-czi** [comment]
@calvinnhieu 4.) Basically, once user has made selections and clicked the button to "Generate download URLs", if they have selected 2 or more organ-assay-species combinations and/or two or more file types, then they'll by definition be getting two or more download links (one per organ-assay-species-filetype). Ambrose suggested to have a button they can click to copy all of the URLs to their clipboard, and when they paste (i.e. in a document), it will list out all the URLs on separate lines.

**Comment by liaprins-czi** [comment]
Also, if we end up not having raw data downloadable, I'll remove that top section of the file selection area (with the bam and fastq and assocatied csv.gz)
