### ISSUE TITLE
Determine ontology storage/lookup plan for M1/M2

### ISSUE THREAD

**Issue by parthshahva** [chanzuckerberg/corpora-data-portal#162]
Questions to answer:
- [ ] What should be stored in the ledger? 
- [ ] What should be stored in the artifact? 
- [ ] What is the responsibility of the consumer ETL jobs?

**Comment by jahilton** [comment]
**What should be stored in the ledger?**
One table that holds all terms from the relevant databases.
The table uses the term ID as the primary key (e.g. EFO:0001182)
All other fields in the table are filled directly from the ontology database (label, synonyms)
Other tables will link to this by submitting only the term ID

**What should be stored in the artifact?**
All metadata from the ontology table that is linked to another object.
(The unlinked ontology metadata could be included, it just doesn't serve much purpose)

**What is the responsibility of the consumer ETL jobs?**
Display the ontology metadata in the artifact as it would any other metadata

So I think an appropriate question to add is: **How is the ontology metadata loaded to the ledger?**

**Comment by ambrosejcarr** [comment]
@parthshahva our discussion is listed above. If this meets your requirements, this issue can be closed.
