### ISSUE TITLE
Design the project page

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/corpora-data-portal#19]
Create a few options for how individual project pages could look.

**AC:** 
---
- [x] design mocks for organization of individual project pages
- [x] mocks explore how the user experience would differ if we choose to: 
  - Bundle categories of files together into zip/tar archives that take the same values of the metadata variables we display on the browser
  - Keep files unbundled. 
- [x] obtain user feedback and decide on the correct design.

**Comment by liaprins-czi** [comment]
Here's a list of questions (for SMEs + users) I have about the projects page, the answers to which will help to narrow down the design:
https://docs.google.com/document/d/1lTQTE-KcFy35FTdDWaT2Ob5fjWDXT-6v7CFoSsMcMMA/edit#heading=h.ttd8dx9oe8jj

It includes links to specific Figma prototypes that exemplify the options under consider for the design.

I've met with a few people internally to get their feedback, and will be typing up my notes from those sessions, here:
https://drive.google.com/open?id=1MwdmetBgF6_TJqMgmFICOypiIV6SdVYa

**Comment by liaprins-czi** [comment]
I have added action items to the synthesized notes from the internal feedback I've solicited. These are the next steps for solidifying the browser designs:
https://docs.google.com/document/d/1B7BNDvoxhnkU7vFSSc4kKPQWCp51dqpdzkHTVysMbLA/edit?usp=sharing

**Comment by ambrosejcarr** [comment]
As discussed on Friday, our goal with this initial prototype is to make sure we capture the user facing functionality of the existing DCP software. As part of this, I made a quick assumption early on that this would include the "checkout" capability of the browser. 

However, design discussions with @liaprins-czi and @colinmegill prompted me to revisit browser-based download of multi-files. I am no longer convinced it makes sense and would like to pause this feature to give some time for user research. You can see my reasoning [here](https://docs.google.com/document/d/1wzOMYFzgZsbLOvcPaPo0D4a3qdGnysf1eXJLSSjkGIA/edit#heading=h.bwuly3wdh661).

In the meantime, I would like to downscope on download. The browser need only: 
1. Enable downloading of matrix files and metadata.
2. Communicate to users how they can use the command line to download the rest of the files (sync with @Bento007 and @calvinnhieu on this).

and the back-end needs to: 
1. Create a very simple CLI interface to enable download of multiple files. I'd be fine with aws s3 sync for now. 

I will propagate this feature downscoping through the requirements and backlog.

**Comment by liaprins-czi** [comment]
Here is a link to the design prototype demoing how a user goes about downloading files. It includes designs for both the list-of-projects and the project page:
https://www.figma.com/proto/0kKMpYmqJuBpqDCmmunhBD/4-Browser?node-id=2%3A0&viewport=-20854%2C918%2C1&scaling=min-zoom

Here is a link to the Figma file itself, which includes several explanatory comments:
https://www.figma.com/file/0kKMpYmqJuBpqDCmmunhBD/4-Browser?node-id=0%3A1

![2 project page | Project Info.png](https://images.zenhubusercontent.com/5d4c6939b2c9257cd301cec2/7fcb4828-b91a-4942-a300-7b5c84edbbd6)

![3 project page | Project Data.png](https://images.zenhubusercontent.com/5d4c6939b2c9257cd301cec2/addf3d1e-cecd-49f2-afcc-248aed1bbc99)

![4 project page | File selection modal.png](https://images.zenhubusercontent.com/5d4c6939b2c9257cd301cec2/5bb67b4f-ac6b-4bd5-8f6f-b0a2ef501057)

![5 project page | URL list in modal.png](https://images.zenhubusercontent.com/5d4c6939b2c9257cd301cec2/c43ca30f-83d8-4baa-86e5-e17637349f64)

Note: Mobile version coming next, Ambrose has made a separate issue to hold all mobile browser designs.

**Comment by ambrosejcarr** [comment]
This looks great. 

One meta question:
- How would you suggest we review these types of designs, determine they are complete, and close tickets? 

Some comments on the download modal window: 
- I'd love it if it were possible to make the downloads more compact. Some options would be, in order of preference: 
  - 3-column layout with (a) file name (b) download url (c) copy url button. 
  - simply reduce white space between the rows
- Could we have a "Copy all URL" button that would copy them into a newline delimited list that a user could paste somewhere?

**Comment by liaprins-czi** [comment]
@ambrosejcarr I like all of those ideas, I have updated the prototype (at the same link):
https://www.figma.com/proto/0kKMpYmqJuBpqDCmmunhBD/4-Browser?node-id=2%3A0&viewport=-12563%2C736%2C0.5&scaling=min-zoom

As far as how I think we should review these designs, determine they are complete, and close the tickets...

Review:
I think the person who created the acceptance criteria + anyone who is dependent on the designs to do their job should review them. I am not always sure who that includes, but if they can be tagged on the design-specific GH issue to review, that would be great (I am happy to do that, I just will need to know who to include).

Determine they are complete:
If they meet the acceptance criteria and are feasible to be implemented without remaining questions (as reviewed by those who are dependent upon the design to do their step), then they are complete.

Close the tickets:
Once all reviewers have reviewed and determine complete, it is ready to be closed. I can close them or you can, it doesn't matter to me! Which do you prefer?

What do you think of that process?

**Comment by ambrosejcarr** [comment]
This sounds good to me. For this one, I'd suggest: 
* Jason (science policy requirements)
* Marcus (tech requirements)
* Ambrose (product requirements)

I'd say the one who did the work gets to close the ticket :)

**Comment by ambrosejcarr** [comment]
Right now, this portion of the prototype is correct: 

![image.png](https://images.zenhubusercontent.com/5b2bd089a26e500c78d1a809/56a9a293-8a88-49ca-8fe3-5d0fe403dc47)

However, when we improve the published artifact to contain "analysis metadata" then there will be two separate raw metadata files: one for bam and one for fastq. They will be very similar. The bam metadata will additionally contain information on the software used to align the fastq file and the genome against which the file was aligned.

**Comment by liaprins-czi** [comment]
Thanks @ambrosejcarr. 

Will they both be .csv.gz? Or will they each have distinct file extensions? Will we still need this current .csv.gz that applies to both the .bam and the .fastq, in addition to the two analysis metadata files you are talking about?

Also, should I update the prototype now, or wait until we do in fact "improve the published artifact"? (I can still design a UI solution to accommodate the change, but not sure when ppl should start to go off of it versus what I have now).

**Comment by ambrosejcarr** [comment]
In the future we will have two files, one each for `.bam` and `.fastq` that are both `.csv.gz`. These two files _replace_ the existing one. The existing file a reasonable intermediate step because it is similar to what the two future files will look like (because the two future files are very similar to one another!).

**Comment by liaprins-czi** [comment]
okay, good to know, thank you. Within the file naming scheme, #75 , I will need to add some specification about how to distinguish these two files via their names for the user once they download. 

Of the top of my head am thinking to append either with `...-bam_companion.csv.gz` or `...-fastq_companion.csv.gz` but "accompaniment" is probably too long. Something in that vein though?

**Comment by ambrosejcarr** [comment]
Simply adding `fastq` and `bam` to the respective metadata files would be highly informative. Can drop `companion` and I think you have the right solution.

**Comment by liaprins-czi** [comment]
Update: Here is the new final design as a Figma file:
https://www.figma.com/file/ZlGIwcvDzn4HBr50cYsBRV/5-Browser?node-id=0%3A1

And as a prototype:
https://www.figma.com/proto/ZlGIwcvDzn4HBr50cYsBRV/5-Browser?node-id=2%3A0&viewport=-400%2C631%2C0.125&scaling=min-zoom
