### ISSUE TITLE
explore how to validate raw data

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/corpora-data-portal#195]
Goal: confirm that the correct raw data files were uploaded relative to the accompanying metadata

**Comment by jychien** [comment]
**Current work in progress document:** https://docs.google.com/spreadsheets/d/1hcxhvTEehozVU6wMifwgSLoERMnG47YbcP4ahwvP4Rg/edit?usp=sharing

**Overall checkpoints for raw datafiles:**

1. Make sure the appropriate fastq files are present 
2. Make sure fastq files are the expected lengths
3. When possible, check to see if expected barcode is present in the appropriate fastq file using whitelist
