### ISSUE TITLE
Investigate the HTAN QC pipeline

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/corpora-data-portal#233]
During the NIH/HCA meeting, Josh Campbell mentioned a pipeline that they developed to run QC on raw matrix files.

- [x] Identify what QC metrics are a part of read-out for each raw matrix file
- [ ] If we think some/all of those will be valuable, get the pipeline operational by running it on a DCP matrix file

From Josh's email...
> Our pipeline is part of the singleCellTK R package. It is currently in a development branch here:
> https://github.com/compbiomed/singleCellTK/tree/devel
> 
> For instructions on how to run it on the command line, see here:
> https://github.com/compbiomed/singleCellTK/blob/devel/exec/SCTK_runQC_Documentation.md
> We will be publishing docker and singularity images in the next week or two to help with reproducibility and dependencies.

**Comment by jychien** [comment]
### **singleCellTK** has the following QC metric output:
&nbsp;  

**GENERAL METRICS (R package: [Scater](https://bioconductor.org/packages/release/bioc/manuals/scater/man/scater.pdf))**
- **sum:** Total counts per cell
- **detected:** Total genes detected per cell
- **percent_top_n:** (where n==50, 100, 200, or 500) Percentage of counts assigned to top n highly expressed genes
- **subsets_mito_sum:** Total mitochondrial counts per cells
- **subsets_mito_detected:** Number of mitochondrial genes detected per cell
- **subsets_mito_percentage:** Percentage of mitochondrial counts out of total gene counts
&nbsp;  

**METRICS ON DROPLET MATRIX (R package: [dropletUtils](https://bioconductor.org/packages/release/bioc/manuals/DropletUtils/man/DropletUtils.pdf))**
- **dropletUtils_emptyDrops_total:** Total UMI count for each barcode
- **dropletUtils_emptyDrops_pvalue:** Barcodes with UMI counts less or equal to _lower_ are used to estimate an ambient profile vector, against which significant deviations are tested with a Monte Carlo approach. Benjamini-Hochberg correction is applied to the calculated p-values.
- **dropletUtils_emptyDrops_logprob:** The log-probability of observing the barcode's count vector under the null model
- **dropletUtils_emptyDrops_fdr:** False discovery rate, suggested cutoff of 1%
- **dropletUtils_emptyDrops_limited:** TRUE/FALSE; indicating whether a lower p-value could be obtained by increasing number of iterations used for Monte Carlo p-value calculations
- **dropletUtils_barcodeRank_knee:** Numeric, specifies total count (log, y-axis) at the knee point when plotted against log-rank of barcode
- **dropletUtils_barcodeRank_inflection:** Numeric, specifies total count  (log, y-axis) at the inflection point when plotted against log-rank of barcode
![image](https://user-images.githubusercontent.com/52470876/78399261-70c36d80-75a9-11ea-8781-33f96d8ab2b8.png)
- **Question:** What are the _lower_ and _retain_ parameters used for emptyDrops analysis?

**Comment by jychien** [comment]
**METRICS FOR DOUBLET DETECTION: (R packages: [scran](http://bioconductor.org/packages/release/bioc/manuals/scran/man/scran.pdf), [scds](http://bioconductor.org/packages/release/bioc/manuals/scds/man/scds.pdf))**
- **doubletFinder_doublet_score:** Likelihood of cell being doublet using artificially generated doublets. Score is defined as the ratio of densities of simulated doublets to the (squared) density of the original cells
- **doubletFinder_doublet_label:** "Singlet" or "Doublet" as deemed by algorithm
- **scds_cxds_score:** Numeric value that determines how likely a cell is a doublet, based on co-expression of gene pairs
- **scds_bcds_score:** Numeric value that determines how likely a cell is a doublet, using artificially generated doublets
- **scds_hybrid_score:** Numeric value that determines how likely a cell is a doublet, uses both cxds and bcds algorithm
- **scran_doubletCells_score:** Numeric value that determines how likely a cell in the counts matrix is a doublet
- **scrublet_score:** Numeric value that determines how likely a cell in the counts matrix is a doublet
- **scrublet_call:** Whether the cell is deemed a doublet or not by the algorithm

**METRICS FOR AMBIENT RNA CONTAMINATION (R package: [celda](https://bioconductor.org/packages/release/bioc/manuals/celda/man/celda.pdf))**
- **decontX_contamination:** Probability of contamination determined by decontX
- **decontX_clusters:** Clusters determined by Celda, a clustering algorithm that runs in the background of decontX

@jahilton, there are the listed QC metrics as shown in the SCTK [documentation](https://github.com/compbiomed/singleCellTK/blob/devel/exec/SCTK_runQC_Documentation.md). These metrics are extracted from expression matrices by the associated R packages, but it is unclear whether qc metrics csv files were used for the data generated by the Optimus pipeline.
