### ISSUE TITLE
Widen Organ and Assay columns

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#249]
Currently it very difficult to parse multi-line columns especially in the organ and assay columns because there is no differentiation of gap between a new item or an item that simply has spilled over into the next line. An example:

DNA library
construction
10X v2
sequencing
cDNA library
construction

Can we widen those two columns so that each item can be represented on a single line or add an additional space between items please?

**Comment by maniarathi** [comment]
Oops; reopening because "DNA library construction" and "cDNA library construction" still have the same issue where it's split as 

DNA library
construction
10X v2
sequencing
cDNA library
construction

**Comment by liaprins-czi** [comment]
This is very mysterious... all of the changes I had made previously are missing completely! I will follow up with @calvinnhieu and @Bento007 to see if there is a way to find them. Otherwise I will redo them from scratch.
