### ISSUE TITLE
Create prod deployment of Data Browser

### ISSUE THREAD

**Issue by calvinnhieu** [chanzuckerberg/corpora-data-portal#294]
Deploy a new `prod` deployment of the Data Browser in the `single-cell-prod` AWS account

DoD:
- [ ] Unit tests passing
- [ ] Functional tests passing
- [ ] E2E tests passing
- [ ] GH push tests passing
- [ ] Automated deploy hook working

**Comment by Bento007** [comment]
Add this to the list https://app.zenhub.com/workspaces/dcp2-5e2a191dad828d52cc78b028/issues/chanzuckerberg/dcp-prototype/295
