### ISSUE TITLE
Finalize the Corpora schema

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#301]
The Corpora schema is the schema that we require submitters to adhere to in order to submit datasets to Corpora. The schema will be largely flexible with very few required fields and contains more recommendations on formatting and use of standardized ontologies and labels with the carrot that it will allow for a better consumption experience through cellxgene and the data portal.

Tasks:
- [x] Approval of schema internally
- [ ] External review and approval

**Comment by brianraymor** [comment]
Jonah Cool is reviewing the schema document to ensure that the community can understand it (with a little coaching) prior to the single cell accountables meeting on June 4. We'll identify external partners and a review plan at that time.

We're also reviewing with Stanford for the Seed Networks on June 11.

**Comment by mckinsel** [comment]
We finished all the reviews with external partners. There were a few relatively modest comments, and the schema doc has been updated.
