### ISSUE TITLE
Publication of Corpora Metadata Schema

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#302]
From the [Single Cell Plan 2020 document](https://docs.google.com/document/d/13KbnfQVruyEp5JbeTbhelYejroqBHn2jtW0YbRnAx0I/edit#) this epic is directly tied to the user story: 

[CZI curated dataset publication](https://docs.google.com/document/d/13KbnfQVruyEp5JbeTbhelYejroqBHn2jtW0YbRnAx0I/edit?ts=5eb1f951#heading=h.8kyk5pombysn) (the bolded part)

*Scientists who want to host data on Corpora can register their interest in submitting by initiating the curation process. **Corpora provides a structured way for users to record high level metadata about their projects, such as the name of their publication, the authors who should be credited, DOIs, if they exist, so they don't need to wait for us to contact them to provide this information, and understand up-front what we need from them.***

*(This prepares for future stories in Download and explore published projects and Search over an increasing volume of published projects.)*

"A prospective publisher understands what metadata is required when submitting a dataset to Corpora. Manual interactions between the publisher and curator continue."

The completion of this epic will allow anyone at CZI to be able to point to a webpage for anyone interested in submitted data to Corpora that contains clear instructions and requirements on what datasets we accept (more easily).

**Comment by brianraymor** [comment]
During July 13 refinement, agreed to address #308 in a later milestone and close this issue.
