### ISSUE TITLE
Set up Corpora database

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#303]
The Corpora database need not reflect the finalized schema but should have migration capabilities available so that changes can easily be made once the schema is finalized.

The Corpora database should be set up based on the UML described in the high level architecture [document](https://docs.google.com/document/d/1d8tv2Ub5b3E7Il85adOAUcG8P05N6UBZJ3XbhJSRrFs/edit?ts=5ec475b2#heading=h.t849jh3lwzxu), Figure 6.

Tasks
- [ ] Setup database migration framework
- [x] Generate/setup ORM classes

**Comment by maniarathi** [comment]
@Bento007 Assigning this to you for now and once you're done with the second task, can you please hand over to @calvinnhieu to complete the final two tasks? Thank you!

**Comment by maniarathi** [comment]
This ticket has redundant tasks: the bringing up of the infrastructure of the database is already handled by ticket #309 so I will remove that from here, unassign Trent and assign this ticket to Calvin. The focus of this ticket will be on defining the tables in the database which includes ORM + migration and doing some basic testing to make sure it works as intended.

**Comment by calvinnhieu** [comment]
Currently blocked on a small AWS resource naming decision. Expect to be clear EOD.

ORM PR (PR350) will be validated via successful load of the sample project (#334).

@maniarathi I haven't set up a DB migration framework in the past. Will follow-up offline for a knowledge transfer (I believe you and Parth set something up with `alembic` in the past?)
