### ISSUE TITLE
Design Data Processing Pipeline infrastructure

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#305]
The data processing pipeline represents the pipeline that is executed once a submitter of a dataset/project clicks "publish," whether privately or publically.

It performs the following tasks:
- Conversion to a canonicalized matrix for consumption by the data browser AND for public download
- Conversion to all supported downloadable formats (i.e. Loom, H5AD, and Seurat)
- Conversion to CXG for cellxgene deployment
- Deployment to cellxgene
- Validation

This issue refers to developing the infrastructure necessary to run these steps and asynchronously notify when the pipeline has finished working so that the submitter may view the deployment results.

TEAM COMMENTS:
1. @patangay mentioned "Looking at what we were trying to do on the data portal, I wonder if all the ETL stuff can be done inside of Airflow or something similar. I don’t think I want to be the one to suggest solutions, but the idea was that once we had the product requirements in place, you folks would reach out to @JenAtTheShore to see if there was any specific path she would recommend going down."

**Comment by mckinsel** [comment]
This has been moved to be part of the [upload from Dropbox RFC](https://github.com/chanzuckerberg/single-cell/pull/88), so closing.
