### ISSUE TITLE
Determine canonicalized Corpora matrix format 

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#306]
Corpora will offer a transformed version of all datasets for download that has been standardized and canonicalized in a way that it is amendable to search functions in the data portal as well as amenable to data integration. This ticket tracks the effort to determine what that standard looks like including tasks like what ontology to adhere to, what metadata names to use, what format, etc.

**Comment by brianraymor** [comment]
Closed during triage with Arathi. No longer required based on the current design.
