### ISSUE TITLE
Migrate existing datasets to finalized schema

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#307]
Tasks:
- [ ] Create scripts to migrate datasets available at cellxgene.cziscience.com to the Corpora metadata schema.
- [ ] Create scripts to enter the above datasets manually into the Corpora database.
- [ ] Execute both scripts and verify success

**Comment by brianraymor** [comment]
@mckinsel - would you review and update task list in top-level summary comment?

**Comment by maniarathi** [comment]
@mckinsel Can you break this down into more concrete tasks please per the meeting? Thanks!

**Comment by mckinsel** [comment]
This issue has been succeeded by issues #437, #439, #440, and #441
