### ISSUE TITLE
Document Corpora metadata schema on corpora.cziscience.com

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#308]
Issue title says it all :)

**Comment by brianraymor** [comment]
Reviewed with @mckinsel - he agrees that it would be helpful to publish the metadata on the portal in Milestone 1 (See [DCP](https://data.humancellatlas.org/metadata) for prior examples). But I'd also note that this is **NOT** required per the Milestone 1 _sketch_. The curator can forward the schema in email during the manual curation process for example.

I would regard this as a **low priority nice to have**. 

Also bringing to the attention of @patdugan20 ...

**Comment by brianraymor** [comment]
Triaged by @maniarathi and @tihuan - closing. Will address as part of the overall documentation for data submitters later in the 2020 plan.
