### ISSUE TITLE
Setup infra for corpora.cziscience.com

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#309]
Point what is now https://browser.dev.single-cell.czi.technology/ to corpora.cziscience.com. 

Setup dev, staging and prod versions of the site.

- [ ] migrate corpora-data-portal/infra to single-cell-infra
- [ ] create certificates for new new domain
- [ ] deploying infra from single-cell-infra
- [ ] deploy site from corpora-data-portal

**Comment by brianraymor** [comment]
Reviewed during triage with Arathi. @Bento007 - would you add a more detailed check list of tasks in the top-level summary comment?
