### ISSUE TITLE
Update OpenAPI Spec with finalized API design

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#310]
Now that the [high level architecture design document](https://docs.google.com/document/d/1d8tv2Ub5b3E7Il85adOAUcG8P05N6UBZJ3XbhJSRrFs/edit#) has been completed, tweak the OpenAPI spec that has been developed to reflect the new changes. Any changes that are required based on design doc bugs can be fixed here as well.

**Comment by brianraymor** [comment]
Arathi and I removed the _Publish API to corpora-api.cziscience.com_ item in the original check list, since there is no requirement to publish the API in Milestone 1.

**Comment by maniarathi** [comment]
Hi @Bento007, I'm taking myself off this ticket since the first task item (finalizing the API in the design document) is complete. I trust you've got the reins from here :)
