### ISSUE TITLE
Implement Corpora API to read projects from database

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#311]
Instead of hardcoding the datasets, implement the `GET /v1/project` API to read existing projects from the database which will eventually be used to populate the frontend of corpora.cziscience.com.

For more information, see the high level Corpora architecture documentation, API Design section [here](https://docs.google.com/document/d/1d8tv2Ub5b3E7Il85adOAUcG8P05N6UBZJ3XbhJSRrFs/edit#heading=h.ybgspejrlzp5).

Tasks:
- [ ] Implement endpoint to query DB
- [ ] Unit test

**Comment by maniarathi** [comment]
@calvinnhieu To break down this ticket further and provide estimates.

**Comment by calvinnhieu** [comment]
Updated and estimated

**Comment by maniarathi** [comment]
@Bento007 this should be in the Now pipeline right?
