### ISSUE TITLE
Gene representation in Corpora

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/corpora-data-portal#320]
There are a bunch of different ways to refer to a human gene, but we want to use HGNC gene symbols in our interfaces in Corpora. This gives us human-intelligible labels. Everyone knows what TP53 is, but almost no one immediately recognizes ENSG00000141510.

The challenge with HGNC is its relaxed approach to versioning and consistency. It appears to use a rolling release model of sorts. So changes can be made whenever, and they’re live immediately. All that gets recorded is the date of the last change.

Also, there are lots of statuses for gene symbols: approved, alias, previous, withdrawn. But there are no clear rules that govern the relationships between them. So one symbol could be an alias for another but also a previous symbol for a third.

Since we want HGNC gene symbols to be in our interface, it would be nice if the same symbols referred to the same genes across different datasets. But we need to let that goal go because it’s obviously impossible. For example, suppose we see the symbol “POP3” in a submission. POP3 is not an “approved symbol”, but it is an alias. Unfortunately, it’s an alias for three different approved symbols: PYCD5, POPDC3, and MLST8. So which one is it? Given that it’s not possible to do a perfect job of this, what can we do that would at least be helpful? 

Suppose we’re given a dataset where the names of the features appear to be gene symbols. Also suppose we’ve downloaded a big table of all symbols from the HGNC biomart and use that as our frozen gene symbol database.

Each symbol in the dataset falls into one of five categories:

Category | Description
-- | --
Approved | The symbol is currently an HGNC “Approved symbol”.
Upgradable | The symbol is not an approved symbol, but it is an alias or previous symbol for exactly one approved symbol.
Withdrawn | The symbol is withdrawn symbol, meaning “the gene has since been shown not to exist”
Ambiguous | The symbol is not an approved symbol, but it is an alias or previous symbol for multiple approved symbols.
Novel | The symbol is not present at all in HGNC.

To give a sense of how frequent these categories are, here’s how it breaks down for one recently submitted dataset with a total of 27072 symbols:

Category | Count
-- | --
Approved | 23774
Upgradable | 1008
Withdrawn | 36
Ambiguous | 13
Novel | 2241

So most symbols are fine, but around an eighth are not valid according to our schema.

Upgradable genes seem pretty straightforward: C6orf222 is now BNIP5, KIAA0430 is now MARF1, AARS is now AARS1, etc.

Withdrawn is a lot of microRNAs and uncharacterized loci, but also some genes like SPHAR which was shown to just be the UTR of another gene. Unfortunately, withdrawn and approved are not disjoint, for example EXT2 is approved and also an alias for the withdrawn EXT3.

Ambiguous is a small but difficult category with a bunch of symbols with no clear meaning. For example, NOV is not an approved symbol, but it is the previous symbol for CCN3 and an alias for RPL10 and PLXNA1.

Novel is mostly uncharacterized loci, read-throughs, pseudogenes, and lncRNAs.

**Proposal**
1. We should download a copy of all the HGNC symbols today, call it HGNC vMemorialDay2020 or whatever, and use that as our source of consistent gene symbols forever. Someday if it feels out of date, we can migrate forward, but we don't want the set of symbols changing continuously underneath us.
2. When we get a dataset with human gene symbols, we should relabel everything that is "upgradable" but leave all the other symbols alone. Even though it means Corpora datasets will have symbols that are not HGNC approved symbols, it's really the only thing we can do.

**Comment by brianraymor** [comment]
Would it be possible to use the [HGNC REST API](https://www.genenames.org/help/rest/) to write a maintenance utility (like a broken link checker) that was run on occasion to see if a symbol had changed state?

**Comment by mckinsel** [comment]
Yeah, they also expose that via form too: https://www.genenames.org/download/custom/

If you set your filter to `gd_date_sym_change LIKE '%2020%'` for example, you see the 60 or so that have been changed this year.

**Comment by brianraymor** [comment]
I was thinking about query by symbol present in our database and flagging its state if there was a change.

**Comment by maniarathi** [comment]
@mckinsel Once ready to close, could you add the tickets to the board that will be required to update the database/validation scripts to reflect the change please?
