### ISSUE TITLE
Handling non-primary cell sources in Corpora

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/corpora-data-portal#321]
In the proposed Corpora schema, we have fields like "sex", "tissue", and "ethnicity". These are meaningful for the standard "grind up a pancreas"-style experiments, but it's no so clear what to do with them when the source of the cells is more complex.

**Proposal**
For cells from cells lines, leave sex and ethnicity blank. Leave disease blank even if the cell line is derived from diseased cells, but do fill in disease if there was some subsequent intervention like a viral infection. For tissue, use the source tissue and append "(cell line)". For example HEK 293 could be "kidney rudiment (cell line)" and "UBERON:0005095 (cell line)" for tissue and tissue_ontology.

For organoids, do the same thing except add "(organoid)" and use the tissue the organoid is modeling.

**Comment by maniarathi** [comment]
Outcome: need to change "cell line" to "cell culture"

**Comment by mckinsel** [comment]
Yeah, and the schema doc has been updated to reflect this.
