### ISSUE TITLE
Instrument and report on Key Performance Indicators for Average daily users

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#327]
**Requirements:**
1. Get permission to access Single Cell’s Google Analytics account

2. Obtain account keys for dev, staging, prod, and use files `.env.development`, `.env.staging`, and `.env.production` to manage the keys
    1. Note, currently `.env.staging` and `.env.production` are not in the repo nor in an S3 bucket yet, which is part of [#469](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/469undefined)

    1. As a workaround, we could temporarily create and git check in both `.env.staging` and `.env.production` in our repo?

3. Set up daily active user view in Google Analytics for Data Portal for all environments. E.g., 

dev and staging: cellxgene.[ENV].single-cell.czi.technology/
prod: cellxgene.cziscience.com/

Data use:
1. Average daily users. High level -- how many people are using our system on a given day?
2. **[Key Performance Indicators](https://docs.google.com/document/d/13KbnfQVruyEp5JbeTbhelYejroqBHn2jtW0YbRnAx0I/edit?ts=5eb1f951#)**

**Comment by brianraymor** [comment]
This is required. 

We do have users with M1 being an _iteration_ of cellxgene.cziscience.com which already has Google Analytics enabled.

**Comment by Bento007** [comment]
Have we determine what our KPIs are?

**Comment by brianraymor** [comment]
See the top-level summary for this KPI - _Average daily users. High level -- how many people are using our system on a given day?_ which is already in place for cellxgene.cziscience.com. 

Ambrose and I will be adding more KPIs for future milestones such as the [Download KPI.](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/7)

**Comment by mckinsel** [comment]
Couple questions:

1. Why do we want daily active users in dev and staging?
2. I get a daily active user email every Monday. Is this just extending that to the data portal?

**Comment by brianraymor** [comment]
@mckinsel 

1. @tihuan updated the top-level summary. He should clarify his intent for dev and staging.
2. Correct. See my [earlier response](https://github.com/chanzuckerberg/corpora-data-portal/issues/327#issuecomment-658478022) which was [reiterated](https://github.com/chanzuckerberg/corpora-data-portal/issues/327#issuecomment-670056349).

**Comment by MDunitz** [comment]
Do we need to check in with Trust/Legal before adding analytics? Or are we covered by our previous conversations?

**Comment by brianraymor** [comment]
We're covered for M1. We've started M2 discussions on org-scitech-trust for authentication and registration.

**Comment by seve** [comment]
Are we planning on having a single GA dashboard/cookie for both the data portal and cellxgene? Otherwise we might get misleading data around users who use only one or the other platform vs using both. ie. 200 cxg users + 150 dp users = 350 total users, but 100 of those users may be using both platforms and counted twice.

@tihuan Did you answer the earlier question regarding the need for GA on dev/staging?

**Comment by tihuan** [comment]
Ooh really great question, @seve !

I'm thinking we'll use Single Cell's GA account, and therefore both DP and cellxgene will share the same IDs for all environments (dev, staging, prod). And hopefully that means GA will use the same cookie for both DP and cellxgene, and therefore not double counting anything?

And the need for GA on dev/staging is just to make sure the implementation works for every environment, but we definitely don't need usage reports on that 😄 

Hope this answers your questions! Thanks, Seve!

**Comment by brianraymor** [comment]
It should be shared because it's one product - not two.

**Comment by brianraymor** [comment]
Arathi and I agreed to close in favor of new KPI(s). This issue is too specific to GA.
