### ISSUE TITLE
Cleanup frontend

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#330]
There is a lot of legacy code involving the previous project pages, references to "DCP," and other code that depends on the previous dcp-prototype API. This all needs to be deleted.

**Comment by calvinnhieu** [comment]
@maniarathi Could you provide some more clarification re: which of the following components that you're proposing get deleted? In particular, the frontend design/pages can be reused unless we're planning on using a completely new design. In the case of wiping the current pages, would a single blank page be appropriate?

Components (checked = reusable/keep, unchecked = delete):
- [ ] List of projects page
- [ ] Project page
- [ ] Authn/authz modules

**Comment by calvinnhieu** [comment]
Actually, the question of "what can be reused" is more granular than the list I made above - I think we have two options here:

1. Delete and start fresh
2. Per component review to determine salvageability

I think (1) is largely the direction we want to take, but I think there's some value in preserving stand-alone components. I could work with @tihuan to do an assessment of these and delete anything that's too large/specific to the old designs.

**Comment by maniarathi** [comment]
I think everything stated above sounds good, but @liaprins-czi do you have a sense of how much of the previous data browser design we should delete vs keep based on your wireframes?

**Comment by maniarathi** [comment]
Oh! Also, any place that uses the term "data browser" - can we please change it to "data portal"? Thank you so much!!

**Comment by liaprins-czi** [comment]
@maniarathi Great question. I am not to finalized wireframes yet especially in terms of visual design, so I'm not sure what they'll end up looking like visually. Which is probably important for the front-end code...
 
But I know we will need a table like the one in the DCP 2.0's "list of projects" page, and for it to be sortable. We will need to add more methods of searching though, like an actual search and/or filtering.

For the project page itself, the layout will depend on what the schema for Corpora is like compared to that of DCP 2.0/the metadata we were able to pull in there. So it will likely change layout.

However, I see the biggest design lift for Corpora being to design from scratch the data contribution flow, so I have been planning to lean on what is already there for the data consumption flow. So I think we should salvage what we can of the original DCP 2.0 portal.

**Comment by tihuan** [comment]
@maniarathi Sure! I see that in the FE, only `README.md` has `Data Browser Frontend`, so we just need to change that to `Data Portal Frontend`?

And to close this ticket do we just need to preserve the current branch as `backup-FE-pages` and then change the text above to `Data Portal Frontend`? Thank you!

**Comment by maniarathi** [comment]
Yep @tihuan , that sounds perfect, thank you!

**Comment by tihuan** [comment]
Sweet will do 😄 Thanks a lot, @maniarathi !
