### ISSUE TITLE
Load sample project into Corpora database

### ISSUE THREAD

**Issue by calvinnhieu** [chanzuckerberg/corpora-data-portal#334]
Use the listed sample project to populate the Corpora DB with simple test data to unblock API development and testing.

Sample .h5ad project in S3:
s3://cellxgene-data-wrangling-prod/Single_cell_gene_expression_profiling_of_SARS_CoV_2_infected_human_cell_lines_Calu_3-28/Single_cell_gene_expression_profiling_of_SARS_CoV_2_infected_human_cell_lines_Calu_3-28-remixed.h5ad

**Comment by calvinnhieu** [comment]
Update on RDS blocker:
- Spoke with MichaelB at Infra office hours:
    - Received primer on `single-cell-infra` repo organization
    - Gained context on Infra's goals and current offering of development/workflow tools
    - Set up meeting for 3:30pm to set up secure dev environment and required security groups to unblock API and Db developmnt

**Comment by calvinnhieu** [comment]
3:30 meeting update:

- Backend AWS resources (API, RDS) will be protected behind private VPC
- During development, port forwarding via Bastion server will provide access to private resources
- In deployment, configure security groups to provide secure access between private resources

**Comment by calvinnhieu** [comment]
Sample project successfully loaded into dev RDS

**Comment by Bento007** [comment]
Good work. Later, you'll have to explain in pictures preferably how this is happening.
