### ISSUE TITLE
Create Staging infra in single-cell-infra

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#337]

**Comment by Bento007** [comment]
related to #379

**Comment by Bento007** [comment]
the staging deployment is depended on the infra bucket deployed in the dev module. I need to remove the dependency to that bucket before deploying the chalice app.

**Comment by Bento007** [comment]
fixed by https://github.com/chanzuckerberg/single-cell-infra/pull/99

**Comment by maniarathi** [comment]
Hey @Bento007 what's the status of this ticket? Is is complete now with the PR in single-cell-infra checked in?

**Comment by Bento007** [comment]
it's complete.
