### ISSUE TITLE
Create production infra in single-cell-infra

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#338]
# What
We need infrastructure setup to support the production environment of Corpora.

# How
- Update the [single-cell-infra terraform code](https://github.com/chanzuckerberg/single-cell-infra/tree/main/terraform/envs/prod) with a corpora module.
- Deploy corpora to the production infra.
- Update to this deployment can occur manually as needed.
- Create a production branch -- DONE!
- No auto deployment from `staging` branch to `production`

# Definition of Done
A new production deployment of corpora is live and viewable online. The url for the site is https://cellxgene.cziscience.com/dp/.

**Comment by tihuan** [comment]
Questions:

1. Can we add the "what" and "how" for this issue please?

2. "What": After this ticket is done, what new capabilities do we get? Is it that we'll be able to merge `staging` branch into `main` branch (or a new `prod` branch) and Github Action will deploy both BE and FE to prod? Or is it that we'll be able to deploy to prod manually and from local machine?

3. "How": Depends on what we want to achieve above, what are the tasks we need to get done in this issue to make it happen?

Thank you!

**Comment by Bento007** [comment]
Coomplete
