### ISSUE TITLE
Simplify deployment of single-cell-infra and corpora

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#348]
M1 Requirements:
1. Use @maniarathi 's secret doc for deployment and rollback instructions for oncall engineer 

============== Below to be done in M2

The current deployment processes looks something like this:
1. Deploy corpora-data-portal/browser/backend.
1. The resulting api-gateway ID is added to single-cell-infra/terraform/env/{stage}/corpora/variables.tf/api_gateway_id
1. deploy single-cell-infra/terraform/env/{stage}/corpora
1. run make upload-deloyment in corpora-data-portal/browser/backend to save the chalice state.
1. Deploy corpora-data-portal/browser/frontend

- We could simplify it into a single script in corpora-data-portal.
- Alternatively we could simplify the deployment by using chalice terraform
- Other possible solution are welcome.

**Comment by brianraymor** [comment]
@Bento007 - to work with @tihuan and @mweiden  to clarify specific solution.

**Comment by tihuan** [comment]
Seems like we need more discussion to figure out what exactly we want to do in this issue, so we can't estimate this one yet?

I remember @mweiden had some thoughts on how we could simplify the deployment, @Bento007 can you help leading this issue and sync with Matt on the best approach to resolve this issue please?

Thank you!

**Comment by mckinsel** [comment]
Does this overlap with #469?

**Comment by Bento007** [comment]
@mckinsel #469 depends on this one.

**Comment by Bento007** [comment]
The initial deployment process has been simplified to the following steps:

1. Deploy corpora-data-portal/browser/backend.
1. Deploy single-cell-infra/terraform/env/{stage}/corpora secrets
1. Populate secrets in AWS
1. deploy single-cell-infra/terraform/env/{stage}/corpora
1. run make upload-deloyment in corpora-data-portal/browser/backend to save the chalice state.
1. Deploy corpora-data-portal/browser/frontend
1. Deploy cloudfront-invalidator

While the initial setup process may seem cumbersome, the update process is easily automated using github actions. 

## Remaining work
* Define the branch promotion process.
* Define github actions to deploy staging branch to the staging deployment, and prod branch to prod deployment.
