### ISSUE TITLE
Remove `refer_secret_id` from corpora terraform variables

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#353]
Context: https://github.com/chanzuckerberg/single-cell-infra/pull/75#discussion_r434850348

This secret variable ends up being sent over plaintext which means that it can be snooped, effectively making the S3 bucket that the secret is supposed to protect, entirely public. The solution here is to ensure that the s3 bucket that is serving the website does not contain anything restricted and that everything is fine for public consumption. Then this variable needs to be removed altogether (requires PR in single-cell-infra repo).

**Comment by Bento007** [comment]
I think this one can be closed. The refer_secret still serves an important purpose. It prevent user from access files directly from s3, which would be more expensive for us and slower for users. The worst case is a user discovers the secret and accesses the bucket, but this is an edge case that doesn't help anyone.

**Comment by Bento007** [comment]
fixed by #354
