### ISSUE TITLE
Design landing page

### ISSUE THREAD

**Issue by pdugan20** [chanzuckerberg/corpora-data-portal#355]
Design an MVP landing page for Corpora which:

- Communicates at a high level what Corpora is and what benefits is provides
- Visually communicates information about data-sets
- Establishes the beginnings of a brand identity (typography, color, logo, language, etc)

**Comment by pdugan20** [comment]
@liaprins-czi we should discuss at a high-level some of what we'd like to establish here re: branding. I think keeping it pretty minimal to begin with is appropriate.

**Comment by pdugan20** [comment]
I believe this UI should now be in a finalized form. @liaprins-czi @tihuan is that correct? This UI should be in a complete form here: https://www.figma.com/file/Ys3WOryh4RpT1V5ezlOtEL/M1-Find-Data-explorations?node-id=158%3A2440.

Can we mark this ticket as closed?

**Comment by liaprins-czi** [comment]
I had initially thought that this ticket was for the "glossy" landing page but now since we redefined "landing page" for M1 it makes sense to me to close it (then if "glossy" landing page is needed in future it can have its own issue).

**Comment by pdugan20** [comment]
@liaprins-czi oh I believe you're exactly right. we can probably revisit this when we get further along with the initial milestones. thanks!
