### ISSUE TITLE
Design authentication flow

### ISSUE THREAD

**Issue by pdugan20** [chanzuckerberg/corpora-data-portal#356]
We should design an authentication flow whose entry-point is the Corpora landing page or potentially any user facing page that can be viewed without an account.

The flow should accommodate:

- Standard fields associated with identifying an email address and password
- Potentially accommodate oauth via Google
- Link out to terms of service, legal, cookie policy, and any other pages which a user must accept in order to create an account
- Allow users to express interest in being contacted by a curator to submit data

**Comment by pdugan20** [comment]
@liaprins-czi lets make sure we walk through some different approaches here in terms of how to minimize the overall friction of these flows. I'm assuming we can use placeholder text until we have a clear sense from legal what requirements will go into the language around creating an account.

**Comment by pdugan20** [comment]
Variations on designs are here: https://www.figma.com/file/wRek2pyjwgfooVH71HstdH/Auth-Flows?node-id=0%3A1.

We are waiting on the auth engineering requirements to be locked in to inform the final designs here (modal vs embedded vs standalone page), but the general look and feel of the buttons an input fields should not change much going forward.

**Comment by ambrosejcarr** [comment]
Account creation looks good. I like compact & with the option to flag
additional providers (12). Is the flow for logging into an existing account
in scope for this ticket?

**Comment by pdugan20** [comment]
@ambrosejcarr yup both are in scope here.

**Comment by pdugan20** [comment]
OK so based on the outcomes of yesterday's meeting (option 2 from the following doc: https://docs.google.com/document/d/1IwvemUlVvAGLs8kBYRkwe4chkw6kwMSFEFxReICa7rc/edit#)

...I think a model where we employ the embedded sign in and register forms, and then call out the need to login to access certain features on the actual site is a good approach.

The header is placeholder, as is the copy for the sign-in prompt. But that aside, I think this is directionally a reasonable approach given what we've outlined in terms of technical constraints and requirements so far.

![13.png](https://images.zenhubusercontent.com/5ed9635e026fd7ca4c14fad6/0d60650a-91ad-4223-9544-c72d49840271)![14.png](https://images.zenhubusercontent.com/5ed9635e026fd7ca4c14fad6/806cf933-af47-4f5c-a03f-5a454db369d3)![15.png](https://images.zenhubusercontent.com/5ed9635e026fd7ca4c14fad6/09f0b7e2-a6a7-48db-959b-954b38cf956d)![16.png](https://images.zenhubusercontent.com/5ed9635e026fd7ca4c14fad6/b6528edf-58fc-42a8-92c2-2856f367472c)

**Comment by ambrosejcarr** [comment]
I like the call-out. We should be careful about the exact wording. Does _creation_ of annotations require an account? or just persistence in the hosted system? Can users download their annotations _locally_ without an account? 

@bmccandless can you help answer these questions?

**Comment by pdugan20** [comment]
Since multiple discussions relating to the callout are happening in different threads, I created a standalone ticket that blocks our auth flow designs to discuss and sign-off on that specifically:
https://app.zenhub.com/workspaces/corpora-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/480

**Comment by pdugan20** [comment]
Discussed this with Colin earlier in the week and we are good here in terms of aligning visually with Cellxgene proper. I updated the Figma files to drop the explanation text and the banner, and we are now just using the black Cellxgene logo, centered above the login forms.

![Screen Shot 2020-07-30 at 11.00.26 AM.png](https://images.zenhubusercontent.com/5ed9635e026fd7ca4c14fad6/054e37bf-074c-47f4-9210-18278479b7bf)

We've also dropped the "Institution" field as per last weeks discussion. I don't believe we reached a consensus on whether or not to point the Contact Us link to either an:
a. Github issue with a template
b. Google group alias

@tihuan did we land on one option vs the other?

**Comment by tihuan** [comment]
Love the new design 🎉 🤩 👍 🥇 !

@ambrosejcarr @brianraymor @colinmegill Does cellxgene have an help email already? If not, I can create a czi google group as an alias for it! Maybe something like `help-cellxgene@chanzuckerberg.com`? (the Google Group name will then be `help-cellxgene`)

I was thinking we could use the email for the "Contact Us" link for now. And if we start seeing repeated requests and/or uptick in request volume, then we can switch to Github issue with template to hopefully dedupe the issues better

What do you think? 

Thank you!

**Comment by ambrosejcarr** [comment]
I believe we decided we'd use cellxgene@chanzuckerberg.com for the time
being. @tihuan I don't think we currently have an alias.

**Comment by tihuan** [comment]
Oh thanks @ambrosejcarr ! `cellxgene@chanzuckerberg.com` SGTM 👍 

CC: @pdugan20
