### ISSUE TITLE
Design template page for static content

### ISSUE THREAD

**Issue by pdugan20** [chanzuckerberg/corpora-data-portal#357]
We should design a page that for all intents and purposes can be static and will serve content required for legal purposes (Terms of Service, Privacy Policy, Cookie Policy, etc).

We can make these very minimal to start with and just have them work within the brand system we create for Corpora.

**Comment by pdugan20** [comment]
@liaprins-czi happy to discuss options here, but given the density of the content for pages like this, it's most important just to establish a clear typographical hierarchy and we can go from there.

**Comment by brianraymor** [comment]
@hthomas-czi - PM reviewed during triage. Can this issue be closed or do you intend to reuse it?

**Comment by hthomas-czi** [comment]
@brianraymor Has this been designed?

**Comment by brianraymor** [comment]
@hthomas-czi - not to my knowledge. @pdugan20 would be the best point of contact.

**Comment by brianraymor** [comment]
Closing per conversation with @hthomas-czi
