### ISSUE TITLE
[Spike] Investigate common methods of file upload

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#361]
Had a short conversation with Marcus about this and Calvin brought it up in a code review, but we should try to support the more common methods of large file upload that contributors feel comfortable with in a way that also reduces latency. This ticket is a spike to investigate that and come up with the first upload mechanism for large files (note the REST API as it is implemented today can only handle small files). 

A starting point is Marcus mentioning that Dropbox is a common mechanism to store large files; we could implement a system by which contributors specify a Dropbox URL and we spin up a small instance to download the file and upload to S3 automatically.

**Comment by brianraymor** [comment]
The [Google Drive upload API](https://developers.google.com/drive/api/v3/manage-uploads#top_of_page) and [Cloud API ](https://cloud.google.com/storage/docs/performing-resumable-uploads) include patterns for multipart and resumable uploads.

**Comment by brianraymor** [comment]
Issue moved to [chanzuckerberg/single-cell #25](https://github.com/chanzuckerberg/single-cell/issues/25) via [**ZenHub**](https://www.zenhub.com/)
