### ISSUE TITLE
Design new project creation page

### ISSUE THREAD

**Issue by pdugan20** [chanzuckerberg/corpora-data-portal#364]
This page will probably share some common components with the existing project management page (where fields are common and remain editable post-creation).

It should allow for:
- Naming of a project
- Ability to add a dataset to the project
- Accommodate whatever other input is required on behalf of users

**Comment by pdugan20** [comment]
OK have some early work around creating a project and uploading a dataset here: https://www.figma.com/file/ldTQ4rQu0wYR6fSXJtjDhf/project-management?node-id=0%3A1

...and will plan to discuss at our design review later today. I'm hoping to gain more clarity around:

- required fields (aside from project name)
- whether or not a user can upload one or more dataset files as a part of a single project
- whether or not we plan on associating each project with a user id in order to show a list of a users projects that they have created (and can edit)

I believe we also have a list of minimum columns each dataset must contain, correct? So we'll probably want to create some robust error states here that explain to a user how to modify and reupload their dataset if it doesn't meet our minimum requirements.

**Comment by brianraymor** [comment]
Thinking about iterations:

- R1 - dataset list similar to current portal
- R1+1 - dataset list with matrix downloads
- R1+2 - project list with read-only metadata columns 
- R1+3 - project list with sortable metadata columns.
- R1+? - project list with search a'la [DCP](https://data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22%3A%22genusSpecies%22%2C%22terms%22%3A%5B%22Homo+sapiens%22%5D%7D%5D)

**Comment by brianraymor** [comment]
Issue moved to [chanzuckerberg/single-cell #21](https://github.com/chanzuckerberg/single-cell/issues/21) via [**ZenHub**](https://www.zenhub.com/)
