### ISSUE TITLE
Data consumers can use curated metadata to search or filter on the portal

### ISSUE THREAD

**Issue by pdugan20** [chanzuckerberg/corpora-data-portal#366]
**Story**

_Data consumers can use curated metadata to search or filter for the datasets that they want to download or explore on the portal._

**Notes**

@ambrosejcarr summarized our recent wrangling conversation about UX Research - reported heuristics for [Be Confident About Dataset Quality](https://docs.google.com/presentation/d/1MhPM27nFfGi7FJ4a6Oi6DAD2SVczpQnJ7WURgDyD3EY/edit#slide=id.gcddcdc5941_0_38).

1. A data consumer looking for datasets wants to limit their search to reputable scientists whose work they trust.
1. A data consumer with a question about a dataset wants to know who to contact.
1. A data consumer looking for a specific dataset wants to be able to find it by its "colloquial name", following the pattern (first author, year) e.g. "Azizi 2018"

I think `1` requires a full author list. In practice, scientists usually limit their search to first/co-first and senior/co-senior authors.

`2` is either the corresponding author(s) or the "contributor", who could be a curator. Creating clear UX around who should be contacted while respecting data ownership could be challenging.

`3` requires that first authors, last authors, and publication year be searchable.

---

This could potentially be auto-extracted using the [crossref API](https://api.crossref.org/v1/works/10.1101/2020.05.11.088591), but needs additional validation.

---

**UX Drafts**

[Figma](https://www.figma.com/file/18a4QULVIfpFQhTn1FGh8a/Filter-and-Search)

**Comment by brianraymor** [comment]
@hthomas-czi - shall we re-purpose this for the future _search and filtering_ epic and add your figma designs?

**Comment by brianraymor** [comment]
Opened in wrong repo. Rewriting as new epic in single-cell and closing this one.
