### ISSUE TITLE
Privatize Corpora API

### ISSUE THREAD

**Issue by calvinnhieu** [chanzuckerberg/corpora-data-portal#371]
- [x] Configure the Chalice API app to launch API Gateway and Lambdas in the Corpora VPC
- [x] Create required security groups via tf to enable communication between API Gateway, Lambda and RDS

**Comment by Bento007** [comment]
for your first bullet https://github.com/aws/chalice/issues/939

**Comment by calvinnhieu** [comment]
- still unable to connect to RDS via API/Lambda after creating listed security resources
- troubleshooting with Infra at 3PM Office Hours today
