### ISSUE TITLE
POST /v1/submission/{project_uuid}/validate

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#374]
Per the [API Design](https://docs.google.com/document/d/1d8tv2Ub5b3E7Il85adOAUcG8P05N6UBZJ3XbhJSRrFs/edit#heading=h.ybgspejrlzp5)

**Description**: Validates the project according to the guidelines in the Validation section and outputs the result, specifying all errors. The result of the validation is also stored in the backend database.

**Parameters**:
Submission UUID [REQUIRED]: The submission UUID of the submission that is being validated.

**Responses**:
200 OK: {`project_uuid, result, message`}
401 Unauthorized user
404 Submission not found

**Comment by maniarathi** [comment]
Assigning to @mckinsel to finish

**Comment by brianraymor** [comment]
Per the August 3 data portal call, reassigning to Milestone 2.

**Comment by maniarathi** [comment]
Closing this ticket since we are no longer supporting a `validate` endpoint. Validation will occur as part of the process of uploading a file.
