### ISSUE TITLE
Implement PII validation in cellxgene CLI

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#376]
Extend [Implement validation in the cellxgene CLI](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/632) to detect and report potential [PII](https://docs.google.com/document/d/1nlUuRiQ8Awo_QsiVFi8OWdhGONjeaXE32z5GblVCfcI/edit) in the dataset to the publisher.

**Comment by brianraymor** [comment]
Assigning to @mckinsel per the July 17 triage with @maniarathi and @tihuan

**Comment by maniarathi** [comment]
I did a spike on this a while back on this so here are a few packages I looked at:

- [CommonRegex](https://github.com/madisonmay/CommonRegex): Useful to grab the regexes but kinda slow implementation.
- [piianalyzer](https://pypi.org/project/piianalyzer/0.1.0/): Didn't work well, not really maintained, hard to configure for our needs.
- [piidetect](https://pypi.org/project/piidetect/): Just overkill.

I'd recommend pulling the regexes from CommonRegex and rolling our own PII checker 🤷‍♀️

**Comment by brianraymor** [comment]
Per the August 3 data portal call, reassigning to Milestone 2.

**Comment by mweiden** [comment]
Likely needs to be re-estimated based on discussion in the 2020-09-22 Refinement meeting. Current estimate is an 8.

**Comment by brianraymor** [comment]
Per the September 22 Refinement, moving to the Product Backlog to complete the in-progress epic.

**Comment by brianraymor** [comment]
Per conversation with @maniarathi and @mckinsel, I scoped to .h5ad with .loom support later.

**Comment by brianraymor** [comment]
Per the October 22 call on upload+validation, I will review this feature with Shawn.

**Comment by brianraymor** [comment]
Reviewed with Shawn. Closing.
