### ISSUE TITLE
Finalize M1 DCP/2 Metadata Schema

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#4]
Acceptance Criteria:
- [ ] Validate that the metadata schema can be flattened into tables that will be queried as part of populating the data browser.

**Comment by jahilton** [comment]
Currently working on the dataops-metadata-schema branch
Will submit a PR once it is up-to-date with the 2/18/2020 version of things ([docs here](https://drive.google.com/drive/u/1/folders/17IQl9BVvnkcvpgxcWMk_wfGGf6zC8_om))
