### ISSUE TITLE
Artifact-to-CXG converter (aka loader) script

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/corpora-data-portal#40]

**Comment by bkmartinjr** [comment]
Input validation & conversion:
* [ ] H5AD to "CXG"
* [ ] Loom to "CXG"
* [ ] Artifact to "CXG"

**Comment by brianraymor** [comment]
Per Bruce's [clarification](https://chanzuckerbergteam.slack.com/archives/CTE2KNL06/p1584398840026100) removing Demo label:

_ question about #40 - you just moved it to a demo deliverable, which is counter to my understanding.   It is not started, and won't be until the Artifact spec stabilizes.   I am planning a manual conversion for the demo. _

_I have already closed the tickets for those items I completed (which were necessary for a demo)_

Restored to previous state.
