### ISSUE TITLE
Implement Data Portal temporary landing page

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#401]
The initial "launch" of data portal will contain a single page that shows a list of datasets that can be launched in cellxgene. Each dataset has up to two options: a remix dataset and the original dataset. This ticket tracks the frontend implementation of the design of the front page.

Figma links: https://github.com/chanzuckerberg/corpora-data-portal/issues/365#issuecomment-651378333

Swagger: https://670bpw5cqf.execute-api.us-west-2.amazonaws.com/dev/

**Comment by maniarathi** [comment]
@liaprins-czi has been working on the prototype of the design here: https://www.figma.com/file/Ys3WOryh4RpT1V5ezlOtEL/M1-Find-Data-explorations?node-id=158%3A2440

**Comment by tihuan** [comment]
Thanks so much for linking the design, @maniarathi !! 😄 🙏
