### ISSUE TITLE
Refactor path modification to use CORPORA_HOME

### ISSUE THREAD

**Issue by calvinnhieu** [chanzuckerberg/corpora-data-portal#406]
Export an environment variable `CORPORA_HOME` used to set the repo top level dir in test files enabling selective test runners. [Context](https://github.com/chanzuckerberg/corpora-data-portal/pull/398#discussion_r446266171)

**Comment by brianraymor** [comment]
@Bento007 - Can you provide more context on this issue? @tihuan and I looked at Calvin's "context" but it was not enlightening.

**Comment by brianraymor** [comment]
@Bento007 indicated that this issue was resolved. Closing.
