### ISSUE TITLE
Database cascade for insert and delete

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#414]
Apply [cascade](https://docs.sqlalchemy.org/en/13/orm/cascades.html) to relationship in [corpora_orm.py](https://github.com/chanzuckerberg/corpora-data-portal/blob/main/backend/corpora/common/corpora_orm.py) to facility future CRUD operations.

This will allows us to perform manual inserts and deletes of datasets for M1 launch.

**Comment by tihuan** [comment]
@Bento007  please split into 2: each is about 5 points each

**Comment by brianraymor** [comment]
Discuss with @mckinsel to see if this optimizes his manual database script.
