### ISSUE TITLE
Link Name for Project Links

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#426]
When links are displayed in the frontend, we want to display a pretty name for the link not a raw url. This will require us to add a new column called `name` to the `DbProjectLink` table. This column will contain the name to display for the link in the frontend. This column should be returned whenever the links are returned.

**Comment by maniarathi** [comment]
@Bento007 Can you explain this ticket a bit more? I don't quite understand why there needs to be an additional column in the table as the display name could for example be a combination of the project name and the type (i.e. remix or original). 

This also seems like there's a dependency on UX here: we currently only know what our "throw-away" dataset/M1 page looks like. Eventually this will be going away and will be replaced by project pages that have not been designed yet.

**Comment by Bento007** [comment]
it would be for the the column on the far right. ![Screen Shot 2020-07-08 at 10.21.17 AM.png](https://images.zenhubusercontent.com/5a4d3418a016c5b034bbeac9/18f69962-9d48-43ae-89f3-2c07f42020d6)

**Comment by Bento007** [comment]
>  I don't quite understand why there needs to be an additional column in the table as the display name could for example be a combination of the project name and the type (i.e. remix or original).

You are referring to the artifact [DbDatasetArtifact links](https://github.com/chanzuckerberg/corpora-data-portal/blob/3d2caba553fdfa698a5668cf3943c25ab51f02ff/backend/corpora/common/corpora_orm.py#L250). I'm reffering to the [DbProjectLinks](https://github.com/chanzuckerberg/corpora-data-portal/blob/3d2caba553fdfa698a5668cf3943c25ab51f02ff/backend/corpora/common/corpora_orm.py#L190)

**Comment by Bento007** [comment]
> This also seems like there's a dependency on UX here: we currently only know what our "throw-away" dataset/M1 page looks like. Eventually this will be going away and will be replaced by project pages that have not been designed yet.

Regardless of the UX we should allow the links to have a friendly name for aesthetics.

**Comment by maniarathi** [comment]
Oh, I see. Thanks for pointing that out! cc-ing @mckinsel because we currently don't have a metadata key that we can query to populate something like that. 

cc-ing @pdugan20 as well just as an FYI.

**Comment by pdugan20** [comment]
Is this a shareable link? Like, is this something that we could just put behind a "copy link" action?

This is also just referring to a vanity url, correct? So like instead of share/id or whatever, it would be share/project-name? Or whatever convention we've decided on?

**Comment by mckinsel** [comment]
Yeah we should probably update the schema for this. I'm not actually sure where the current values came from either. I'm guessing Bruce created then when updating the site.

**Comment by maniarathi** [comment]
From the database end of things, I am actually addressing this with #430, by updating the database UML diagram to reflect the change and then executing the migration.

@mckinsel, can you update the schema, then we can close this?
