### ISSUE TITLE
Get /projects

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#428]
Implement get /v1/project and get /v1/project/{project_uuid}

**Comment by tihuan** [comment]
@Bento007 Do we still need this issue if we have https://app.zenhub.com/workspaces/corpora-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/311? Thank you!

**Comment by Bento007** [comment]
complete
