### ISSUE TITLE
Close sessions after interacting.

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#449]
Currently when a lambda is invoked a DB session is opened. That session will persist until that lambda is torn down. This leave DB sessions for an indefinite amount of time if the lambda is reused a lot. This can cause problems when trying to manage the database or test the database. [SQLAlchemy recommends](https://docs.sqlalchemy.org/en/13/orm/session_basics.html#when-do-i-construct-a-session-when-do-i-commit-it-and-when-do-i-close-it) keeping the session open for a "unit of work" before closing, commit, or rolling back. [Flask-SQLAlchemy](https://flask-sqlalchemy.palletsprojects.com/en/2.x/) provide resource to help manage sessions, we can also build out own solution.

**Comment by Bento007** [comment]
relates to https://github.com/chanzuckerberg/corpora-data-portal/pull/448

**Comment by brianraymor** [comment]
@mckinsel - per triage with @maniarathi and @tihuan - would you review and offer guidance?
