### ISSUE TITLE
Deprecate `Corpora`

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#450]
[Remove corpora.cziscience.com domain](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/559)

- [x] https://corpora.cziscience.com is removed (only PROD)
- [x] https://api.corpora.cziscience.com is removed (only PROD)

---

[Turn off legacy landing page](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/459)

- [x] @mckinsel notifies the author of the [affected paper ](https://www.cell.com/cell/fulltext/S0092-8674(20)30500-6#secsectitle0060)about the URL change 

- [x] Update https://chanzuckerberg.github.io/cellxgene/ to include the link to cellxgene.cziscience.com
- [x] Return a 404 for https://chanzuckerberg.github.io/cellxgene/posts/cellxgene_cziscience_com
- [x] Retain a copy of the HTML for https://chanzuckerberg.github.io/cellxgene/posts/cellxgene_cziscience_com around just in case

---

Update (8/4/2020): 

**Requirement**:
- [x] Update the related repos's README with the following message to avoid confusion:

> UPDATE (X/X/2020): Starting today, the name Corpora will only be used as the internal project name, with cellxgene Data Portal being the official product name

============= Archive - no need to the the following for M1

Given the decision to rebrand corpora to cellxgene, we will need to update our internals to ensure that the branding matches. This work includes:

- [ ] Updating Route53 with cellxgene.cziscience.com and deleting corpora.cziscience.com (dev and staging).
- [ ] Updating databases name with cellxgene.
- [ ] Update variable names in code that reference Corpora.
- [ ] Sort out S3 buckets names and any conflicts with existing cellxgene-prefixed buckets.
- [ ] Work with infra to rename roles related to Lambda functions used by Corpora.
- [ ] Update API Gateway to reflect name change
- [ ] Update IAM policies that reference Corpora
- [ ] Update secret names
- [ ] Update any references to Corpora in single-cell-infra repo
- [ ] Rename Github repo
- [ ] Update public-facing documentation that references Corpora

**Comment by Bento007** [comment]
Could we just change all of the outward facing documentation to say cellxgene and keep the internals as corpora. Corpora will be the internal name we use to distinguish cellxgene the tool from cellxgene the data browser. It will save us a ton of refactoring work, resolving name conflicts, migrating buckets, and makes it easier to communicate what part of the project is being modified.

**Comment by tihuan** [comment]
I can see why having Corpora namespace internally could cause confusion, since now publicly everything is Cellxgene. But I think I'm leaning towards @Bento007 's idea in terms of renaming, because in order to distinguish between cellxgene the tool and the data browser, the data browser will still need to have a different name than `cellxgene`. 

So data browser's internal project name could be either just `data portal` or `dp` for short, to match our external product name, as seen in API URL `api.cellxgene.cziscience.com/dp/*`, or just keep it as `corpora`

Personally I feel that as long as we update public facing name to be Data Portal (DP) and on https://github.com/chanzuckerberg/corpora-data-portal's README to say:

> UPDATE (8/1/2020): Starting today, the name `Corpora` will only be used as the internal project name, with `Cellxgene Data Portal` being the official product name

It should clear all the potential confusions?

Thank you!

**Comment by mckinsel** [comment]
Also I don't think we have a name for the "integration data corpus" if we drop Corpora. Ambrose [suggested](https://github.com/chanzuckerberg/corpora-data-portal/issues/461#issuecomment-662663002) just calling it "remix".

**Comment by brianraymor** [comment]
Per September 24 Sprint Planning, @maniarathi and @mckinsel agreed that we should merge the three remaining issues related to corpora deprecation into one issue and assign an estimate of 1 (rather than three tickets each estimated at 1).

**Comment by lesliecodes** [comment]
@signechambers1 can you verify the https://chanzuckerberg.github.io/cellxgene/ part? Thank you!
