### ISSUE TITLE
Turn off legacy landing page

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#459]
Condition: Once the new landing page is launched

Tasks:
1. Make sure the affected paper's author is properly notified about the URL change (https://www.cell.com/cell/fulltext/S0092-8674(20)30500-6#secsectitle0060)

2. Turn off https://chanzuckerberg.github.io/cellxgene/posts/cellxgene_cziscience_com

**Comment by tihuan** [comment]
I'm assuming the outcome of this ticket is that https://chanzuckerberg.github.io/cellxgene/posts/cellxgene_cziscience_com will show "404 Not Found"?

Or do we just want `https://cellxgene.cziscience.com/` to stop redirecting to https://chanzuckerberg.github.io/cellxgene/posts/cellxgene_cziscience_com, but people who navigates to https://chanzuckerberg.github.io/cellxgene/posts/cellxgene_cziscience_com directly will still be able to see the legacy page below?

![Screen Shot 2020-08-10 at 9.29.51 AM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/0b7aedc9-ed9b-40fd-84ab-c438022b6108)

CC: @brianraymor @ambrosejcarr @mweiden 

Thank you!

**Comment by brianraymor** [comment]
See the bolded sections below. These notes are documented in the 2020 plan and reflect the outcome of the branding discussion.

Note: The current portal (cellxgene.cziscience.com) will be updated as outlined in this plan and address the following requirements:

1. External COVID-19 sites depend on links to hosted cellxgene. For example, see interactive viewers on the COVID-19 Cell Atlas. Existing hosted cellxgene dataset links such as https://cellxgene.cziscience.com/d/krasnow_lab_human_lung_cell_atlas_10x-1.cxg/ MUST be preserved.
2. Existing hosted cellxgene datasets MUST NOT require user registration or authentication in the future if there is an emerging requirement for all users to register with the Data Portal. This would impact the expected user experience. Cellxgene supports the concept of multiple dataroots, each with different configuration and policies. All legacy datasets MUST be maintained in a separate dataroot ("https://cellxgene.cziscience.com/d/") that neither supports authentication nor user annotation. Future datasets MUST be served from a second dataroot that supports authentication and user annotation.
3. All legacy datasets MUST be reingested (copied) in the Data Portal to ensure that common features and policies are supported for both legacy and future datasets.
4. **The Data Portal MUST NOT redirect to the legacy github.io landing page. An updated landing page has been designed.**
5. **The legacy github.io landing page MUST be deleted to prevent users from taking dependencies on the page (inappropriately referencing it in papers) or growing confused by the proliferation of “almost but not quite entirely unlike” landing pages.**
6. Once this Data Portal is “live”, no further datasets will be added to the legacy COVID-19 portal.

**Comment by maniarathi** [comment]
Given some discussions today, I have a suggestion to revamp this ticket a bit. Instead of "turning off" the legacy page, why not just remove the links from the page, with a link to cellxgene.cziscience.com? We will still need the majority of the contents on this website that have detailed information on how to run cellxgene on your desktop.

**Comment by tihuan** [comment]
Sounds good to me! 

@brianraymor @ambrosejcarr thoughts? Thank you!

**Comment by brianraymor** [comment]
I shared my thought earlier on the original slack thread. There's already a documentation page for cellxgene - https://chanzuckerberg.github.io/cellxgene/. Bruce copied it to temporarily create the portal page for the covid-19 datasets.

**Comment by tihuan** [comment]
That's right!

I think Arathi is saying the following link will now go to https://cellxgene.cziscience.com instead of https://chanzuckerberg.github.io/cellxgene/posts/cellxgene_cziscience_com?

![Screen Shot 2020-08-26 at 6.17.26 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/2cc949e0-c51e-4fa6-80a9-37e8cb4c901c)

**Comment by brianraymor** [comment]
Sorry - that's not what I read in her comment. I read that Arathi believed that she was losing her documentation page if we turned off the current cellxgene landing page. But Bruce made a copy of that page.

**Comment by maniarathi** [comment]
Nah, you're both right. I didn't realize that `https://chanzuckerberg.github.io/cellxgene/` is the copy landing page. But Timmy is also right in that I was also suggesting that the highlighted link in his screenshot also go to the new cellxgene.cziscience.com.

**Comment by tihuan** [comment]
Thanks Arathi!! So what action items do we get out of this? (sorry brain not functioning well at this point of the day lol)

1. Update the highlighted link to `cellxgene.cziscience.com`
2. ?

Thank you 😆

**Comment by brianraymor** [comment]
1. Update https://chanzuckerberg.github.io/cellxgene/ to include the link to cellxgene.cziscience.com
2. Return a 404 for https://chanzuckerberg.github.io/cellxgene/posts/cellxgene_cziscience_com
3. Keep a copy of the HTML for https://chanzuckerberg.github.io/cellxgene/posts/cellxgene_cziscience_com around _just in case_

**Comment by brianraymor** [comment]
Per September 24 Sprint Planning, @maniarathi and @mckinsel agreed that we should merge the three remaining issues related to corpora deprecation into one issue and assign an estimate of 1 (rather than three tickets each estimated at 1). Closing.
