### ISSUE TITLE
Update 2020 plan to reflect branding decision

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#461]
- [x] Include note and reference for the branding change when "Corpora" is first defined
- [x] Revise text for cellxgene.cziscience.com transition

**Comment by brianraymor** [comment]
There are `104` references to "corpora" in the 2020 plan! I intend to simply add a note describing the branding decision rather than replacing all references.

@maniarathi, @bmccandless, @mckinsel, and @tihuan - please review and comment as needed by July 23 EOD. Also let me know if you'd like me to capture the overall discussion/alternatives from the slack channel as a comment in this issue.

With regards to the text related to the transition of the web site. I propose:

**Original:** We will plan for the seamless transition from the COVID-19 portal (cellxgene.cziscience.com) to the Corpora portal (corpora.cziscience.com). Once Corpora is “live”, no further data will be added to the COVID-19 portal. 

**Update**: With the deprecation of the Corpora brand, the current portal (cellxgene.cziscience.com) will be updated as outlined in the Milestone plan and address the following requirements: 

1. External COVID-19 sites depend on links to hosted cellxgene. For example, see _interactive viewers_ on the [COVID-19 Cell Atlas](https://www.covid19cellatlas.org/). Existing hosted cellxgene dataset links such as https://cellxgene.cziscience.com/d/krasnow_lab_human_lung_cell_atlas_10x-1.cxg/ **MUST** be preserved.
2. Existing hosted cellxgene datasets **MUST NOT** require user registration or authentication in the future if there is an emerging requirement for all users to register with the Data Portal. This would impact the expected user experience. Cellxgene supports the concept of _multiple dataroots_, each with different configuration and policies. All legacy datasets **MUST** be maintained in a separate dataroot ("https://cellxgene.cziscience.com/d/<dataset>") that neither supports authentication nor user annotation. Future datasets **MUST** be served from a second dataroot that supports authentication and user annotation.
3. All legacy datasets **MUST** be reingested (copied) in the Data Portal to ensure that common features and policies are supported for both legacy and future datasets.
4. The Data Portal **MUST NOT** redirect to the legacy [github.io landing page] (https://chanzuckerberg.github.io/cellxgene/posts/cellxgene_cziscience_com). An updated landing page has been designed.
5. The legacy [github.io landing page] (https://chanzuckerberg.github.io/cellxgene/posts/cellxgene_cziscience_com) **MUST** be deleted to prevent users from taking dependencies on the page (inappropriately referencing it in papers) or growing confused by the proliferation of “almost but not quite entirely unlike” landing pages.

**Comment by mckinsel** [comment]
Branding/terminology question that came out of finishing the schema work: what's the word for the effort to remix datasets in order to create a corpus suitable for integration research?

**Comment by ambrosejcarr** [comment]
"remix" seems no worse than "corpora". Open to ideas.
