### ISSUE TITLE
[Infra] Simplify CI/CD for Dev, Staging, and Prod Deployment

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#469]
Currently Data Portal automatically deploys app to the Dev environment when any commit is merged into `main` branch. 

But we want to expand the deployment flow to work for staging and prod deployments, which can follow a similar process cellxgene uses, which is any commits merge into staging/prod branch will trigger a deployment for its corresponding environment

Requirements:
1. When a commit is merged into staging branch, it deploys our app to staging env
1. When a commit is merged into prod branch, it deploys our app to prod env
1. Please make sure proper local tests have passed successfully in the GH Action flow before deployment, and after deployment also run the tests against the environment

NOTES:
1. Maybe work with Cellxgene engineers to set up the pipeline, so we have a consistent workflow among the teams

**Comment by tihuan** [comment]
@mweiden PTAL! Is this what you were thinking? Thank you!

**Comment by mweiden** [comment]
@tihuan looks good 👍

**Comment by tihuan** [comment]
Awesome thanks @mweiden !

And thanks @Bento007 for taking this 🙏 ⭐ !

**Comment by maniarathi** [comment]
Is this ticket complete now that all the PRs are closed?

**Comment by tihuan** [comment]
@Bento007 PTAL 🙏 Thank you!

**Comment by maniarathi** [comment]
Chatted with Trent. This can be closed.
