### ISSUE TITLE
DELETE /v1/submission/{project_uuid}

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#471]
Per the [API Design](https://docs.google.com/document/d/1d8tv2Ub5b3E7Il85adOAUcG8P05N6UBZJ3XbhJSRrFs/edit#heading=h.ybgspejrlzp5)

**Description**: Deletes the submission associated with the given project UUID. This does not delete the project if the project associated with the submission has been previously publicly published.

**Parameters**:

1. Project UUID [REQUIRED]: the UUID of the project to be deleted.

**Responses**:

1. 202 Accepted
2. 401 Unauthorized user
3. 404 Project not found

**Comment by Bento007** [comment]
Deletes the submission associated with the given project UUID. This does not delete the project if the project associated with the submission has been previously publicly published.

**Comment by maniarathi** [comment]
Closing this ticket for now in favor of re-opening tickets once we've talked about the design for deletion again and scheduled the work in our roadmap.

**Comment by brianraymor** [comment]
Removing from original epic to eliminate any confusion.
