### ISSUE TITLE
DELETE /v1/submission/{project_uuid}/dataset/

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#473]
Per the [API Design](https://docs.google.com/document/d/1d8tv2Ub5b3E7Il85adOAUcG8P05N6UBZJ3XbhJSRrFs/edit#heading=h.ybgspejrlzp5)

**Description:** Deletes a file from the project’s S3 bucket if the file exists. If no such file exists, then a warning will be outputted.

**Parameters**:
1. Project UUID [REQUIRED]: the UUID of the project from which the file will be removed.
2. Dataset UUID [REQUIRED]: Request body parameter. The UUID of the dataset that is being removed.

**Responses**:
1. 202 Accepted
2. 401 Unauthorized user
3. 404 Submission or file not found

**Comment by Bento007** [comment]
Deletes a file from the project’s S3 bucket if the file exists. If no such file exists, then a warning will be outputted.

**Comment by maniarathi** [comment]
Closing this API since we won't have /submission/ APIs moving forward and we'll want to rethink deletions holistically before writing tickets to develop said APIs.

**Comment by brianraymor** [comment]
Removing from the original epic to eliminate confusion.
