### ISSUE TITLE
Fusillade Example for DP's AuthN

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#483]
@Bento007  will help pull out some Fusillade example code to make it easier for @bmccandless to implement DP's AuthN

NOTE: Please kindly timebox this to 1 day max, since AuthN's work is M2, less time sensitive than M1's API work 😄🙏

Thank you!

**Comment by tihuan** [comment]
Changing priority to M1 to unblock https://app.zenhub.com/workspaces/corpora-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/481 (which also got changed to M1) Thank you!

CC: @brianraymor @Bento007

**Comment by Bento007** [comment]
We decided not to use fusillade. We found a simpler solution.
