### ISSUE TITLE
Delete APIs

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#488]
Add the APIs to Delete:
- /v1/submission/{project_uuid}/dataset/{dataset_uuid}
- /v1/submission/{project_uuid}
- /v1/project/{project_uuid}

Related to #414

**Comment by brianraymor** [comment]
@tihuan and @Bento007 - I'm confused why this is a priority over M1 issues.

It's not assigned to a Milestone but in the Now pipeline.
It looks like a duplicate to #471 and #473

And deletion is a Milestone 4 story:

_Publishers can update, replace, and delete their projects, datasets and metadata._

Can you advise?

**Comment by Bento007** [comment]
Duplicate, closing.
