### ISSUE TITLE
[FE] Create smoke test for DP

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#499]
## Need

When new code is deployed we need a way to quickly determine if the deployment was successful. A smoke test which verifies some basic functionality needs to be created.

## Requirements
The smoke test will constantly be evolving and growing. This is the minimal functionality that should be added to complete this issue.

- [ ] Set up basic E2E Smoke Test in FE for DP
- [ ] Verify the swagger API page is accessible
- [ ] Test that the list of projects is displayed correctly
- [ ] Test that project pages display correctly

**Comment by tihuan** [comment]
@mweiden @Bento007 I added setting up basic e2e smoke test in FE DP in this ticket as well! Thank you!

**Comment by mweiden** [comment]
@tihuan @brianraymor heads up: I scoped down this ticket to just the creation of the smoke test, since @tihuan has split out connecting it to CI/CD into this issue https://github.com/chanzuckerberg/corpora-data-portal/issues/519

**Comment by tihuan** [comment]
Thank you! Yes, I'll update this issue's title to reflect that too
