### ISSUE TITLE
Data Browser File download specification

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/corpora-data-portal#50]
Create specification that describes how the browser back end will enable download paths needed by proposed browser UX. 

Relates to #19

**Comment by Bento007** [comment]
Spec for download management. Feedback appreciated. https://docs.google.com/document/d/1uKEZMF0WfAIsMb_H-flSG3lxkMFeM94zAK3EzNfoSQ4/edit?usp=sharing

**Comment by ambrosejcarr** [comment]
Is this ready for broader review @Bento007 ?

**Comment by Bento007** [comment]
ues, I've sent it to marcus and calvin.
