### ISSUE TITLE
Health checks

### ISSUE THREAD

**Issue by mweiden** [chanzuckerberg/corpora-data-portal#500]
## Need

As a data portal developer/operator, I need an alert when a deployment environment is down, so that I know when to fix the system.

## Approach

- [x] Implement a DataDog alert with a loose error window for `dev` and `staging`
- [x] Implement a DataDog alert with a tight error window for `prod`
- [x] Confirm that DataDog alerts show up in the slack ops channel

## TEAM COMMENTS
1. Timmy: Maybe set Datadog up for pinging a few critical API endpoint first, then once DP web app is up, we can ping the website homepage too as a followup ticket!

**Comment by MDunitz** [comment]
Testing 
- https://api.dev.corpora.cziscience.com/v1/project
