### ISSUE TITLE
Investigate why api can't find psycopg2

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#501]
This error: ```[ERROR] Runtime.ImportModuleError: Unable to import module 'app': No module named 'psycopg2._psycopg'``` causes the backend api to not fail. This can be fixed by manually deploying a computer. 

I suspect this is happening when github actions deployed that backend.

**Comment by tihuan** [comment]
@Bento007 I know it's hard to estimate a bug, but can you try to estimate base on either:

1. Resolve the bug with a complete fix (whatever this means) 
2. Come up with a temp solution that can unblock Github Actions deployment

And we will iterate from there 😄?

Thank you!

**Comment by Bento007** [comment]
The issue was cause in github actions when the requirements were downloaded for SQLALchemy. It has a dependency for psycopgy2 which we are vendoring in. However it was downloaded any ways and caused the vendored in package to not work. The solution was to not vendor in psycopg2, and use psycopg2_binary in the requirements.txt. This ensure that a working version of psycopg2 is included in the deployment.

**Comment by Bento007** [comment]
In the future we should see about compiling our version of psycopg2 and included it into our build.

**Comment by tihuan** [comment]
Thanks for the investigation and clearing this roadblock, @Bento007 🙏 🎉 You rock 👍 !
