### ISSUE TITLE
[Infra] Create CloudFront Distribution `api.cellxgene.cziscience.com` and serve Cellxgene and DP APIs

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#502]
Given the brand merge, we want the cellxgene and DP's APIs to live on `api.cellxgene.cziscience.com/dp/*` and `api.cellxgene.cziscience.com/cellxgene/*` respectively, in order to better manage authentication and authorization

Requirements:

1. Create CloudFront distribution `api.cziscience.com`

1. Create Cache Behaviors

  1. `/dp/*` - to forward the requests to DP's API Gateway origin
  2. `/cellxgene/*` - to forward the requests to Cellxgene EB origin

1. Please set up **dev** and **staging's** equivalents as well at `api.cellxgene.[ENV].single-cell.czi.technology`

1. **Please configure this via Terraform**

1. This ticket does **NOT** include TF Enterprise migration

NOTE: By default I believe CloudFront doesn't forward any cookies, so we'll need to add our token cookies to the CF's cookie passlist

**TEAM COMMENTS:**
1. @bmccandless what cookie keys do we plan to use for refresh token and access token 😄?

Thank you!

**Comment by tihuan** [comment]
@bmccandless gentle ping on the question under the **TEAM COMMENTS** section 🙏 Thank you!

**Comment by tihuan** [comment]
@bmccandless what cookie keys do we plan to use for refresh token and access token 😄? Thank you!

**Comment by bmccandless** [comment]
@tihuan I'm currently using "cxgusr" as the cookie key.

**Comment by MDunitz** [comment]
I spoke with our amazon rep for about an hour on Friday. We concluded that its not possible to do what is described in this ticket (in terms of using cloudfront to rewrite to different domains based on /cellxgene and /dp. ( https://api.cellxgene.dev.single-cell.czi.technology/cellxgene/d/pbmc3k.cxg/api/v0.2/schema rewrite to https://cellxgene-eb.dev.single-cell.czi.technology/d/pbmc3k.cxg/api/v0.2/schema)

We came up with three options

1. update the web server configuration for "cellxgene-eb.dev.single-cell.czi.technology" and move all content to /cellxgene. Then we can use "cellxgene-eb.dev.single-cell.czi.technology" as origin in the distribution. With this setup, the request URL will not be changed and the output works as expected (https://cellxgene-eb.dev.single-cell.czi.technology/**cellxgene**/d/pbmc3k.cxg/api/v0.2/schema). And use the data portal api as the default (https://api.cellxgene.dev.single-cell.czi.technology/ -> dp api)

2. use the cellxgene api as the default (https://api.cellxgene.dev.single-cell.czi.technology/d/pbmc3k.cxg/api/v0.2/schema -> https://cellxgene-eb.dev.single-cell.czi.technology/d/pbmc3k.cxg/api/v0.2/schema) and remove all references to the dev.corpora.cziscience.com replacing it with cellxgene.dev.single-cell.czi.technology

3. create a Lambda@Edge function on path /cellxgene. This Lambda@Edge function should rewrite the request path and remove the first "/cellxgene" from the path. With this solution, the request path will be passed to origin server in a format that gives an output. 
We can then make the data portal api the default (A) or setup an additional lambda edge to redirect /dp (B)

I'm leaning towards 3A but would welcome any feedback

**Comment by bmccandless** [comment]
Thanks @MDunitz. 

cellxgene currently has an issue where the frontend and backend use the same base url:  browser points to <baseurl>/d/dataset.cxg, backend api is accessed at <baseurl>/d/dataset.cxg/api/v0.2/....   I have a ticket to separate out the backend base url from the frontend base url.  This is needed regardless of the 3 options Madison described.  Basically, in the configuration the backend base url could be specified to something like this: <apiroot>/cellxgene/ which I think is equivalent to option 1.

So, I think option 1, would just work, once this feature was implemented.   
In this option the data portal would use "<apiroot>/..." and cellxene would use "<apiroot>/cellxgene/..."

However, like the consistency of 3B.  
data port would use "<apiroot>/dp/..." and cellxgene uses "<apiroot>/cellgene/..."

**Comment by MDunitz** [comment]
option 3 would also be fairly straightforward to update once we separate the backend and frontend base urls

**Comment by tihuan** [comment]
Thanks so much for syncing with AWS rep and came up with the options, @MDunitz 😄 🙏 

And thanks @bmccandless for the bonus context!

So it sounds like the issue is path rewriting, which seems troublesome 🤔 Sorry for not thinking of this earlier!

If we want API consistency `/dp/*` and `/cellxgene/*`, maybe DP's server could also add prefix `/dp/*` to its route, so CF doesn't need to rewrite the path. And then default Cache Behavior could be either DP or cellxgene?

E.g.,

DP OLD
```py
@app.route("/", methods=["GET", "HEAD"])
```

DP NEW
```py
@app.route("/dp/", methods=["GET", "HEAD"])
```

Just hoping this would save us the need of setting up Lambda Edge to rewrite the path!

And cellxgene's BE/FE base URL separation SGTM 👍 ✨

**Comment by tihuan** [comment]
^ @Bento007 @mckinsel would love your thoughts on this as well 🙏  Thank you!

**Comment by Bento007** [comment]
> If we want API consistency /dp/* and /cellxgene/*, maybe DP's server could also add prefix /dp/* to its route, so CF doesn't need to rewrite the path. And then default Cache Behavior could be either DP or cellxgene?

this is a cheap solution, however it's easier to do this in the openapi.yml than python code.

Does this do anything to help the cellxgene api?
