### ISSUE TITLE
Measure the number of times each dataset is uniquely downloaded

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#503]
For **Scientists can download datasets in AnnData, Loom, or Seurat v3 RDS formats. Computational Biologists want to be able to download datasets from the _dataset-view_ so they can apply analyses that are unavailable in _Explore Data_.**

_Measure the number of times each dataset is uniquely downloaded._

Business justification: 

- We can provide this information to publishers to help them measure their paper's impact and their data's reuse, improving the value of our system. 
- This will help us form hypotheses about which data is valuable and focus our community data manager on sourcing additional datasets with similar characteristics.

---

**Notes from August 27 Refinement:**

1. How do we measure both unique downloads through the UI+REST API and through curl scripts?
2. How do we assign unique identifiers (IP and/or any unique identifier through CloudWatch)
3. And does the proposed solution meet CZI PII requirements?
5. Break down metrics by dataset ID

**Comment by brianraymor** [comment]
Issue moved to [chanzuckerberg/single-cell #7](https://github.com/chanzuckerberg/single-cell/issues/7) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tihuan** [comment]
@mckinsel Hmm sounds like before we have browser resumable download, we need to track this metric outside of the FE. So we'd need to do some research on how to track CLI resumable download usage?

**Comment by maniarathi** [comment]
Could we just store the count in the database and increment everytime there's an API request to download that particular dataset? Another option could be to write a script to query API Gateway logs to figure out the number of times the dataset was requested via the API.

**Comment by MDunitz** [comment]
Do we want any checks to prevent counting downloads related to testing?

**Comment by mckinsel** [comment]
What's "uniquely" mean here exactly?

**Comment by tihuan** [comment]
Matt: UCSC has a script for tracking download -- if useful for us to repurpose

**Comment by tihuan** [comment]
Ideally unique by IP, but please check with trust!

**Comment by mweiden** [comment]
Here is UCSC's exporter https://github.com/HumanCellAtlas/google-analytics-exporter

**Comment by tihuan** [comment]
Workshop needed!

**Comment by brianraymor** [comment]
I've verified with Ambrose that this can be addressed later (and not immediately with the download feature). Self-publishing is a higher priority right now. In addition, this should be triggered by a larger number of datasets.
