### ISSUE TITLE
Delete Dataset and Related Files

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#506]
When deleting a dataset, the files uploaded to storage associated with that dataset must also be deleted. This must also happen when a project or submissions is deleted. If a project or submission is deleted, the datasets and associated files must also be deleted.

Before deleting files from storage, make ensure the file is not apart of a publish project when deleting a submission, or apart of a submissions when deleting a published project.

**Comment by maniarathi** [comment]
Closing this ticket for now in favor of reopening tickets once we've looked at the deletion process for portal more holistically.
