### ISSUE TITLE
Add all M1 datasets to the database

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#508]
Per our refinement discussion on 2020-08-12, there was some ambiguity about the scope of this. It is _not_ successfully remixing all the existing datasets but rather moving the remixable into the db and noting the errors/blockers for Ambrose.

- [x] Get db access and and current ORM code working (See Trent's #512)
- [x] Prepare table of existing datasets on cellxgene.cziscience.com with remixability and if not remixable, a reason why
- [x] Write and run script to add projects/datasets to dev portal db
- [x] Once prod is up, do the same for prod

We expect about 50% of the datasets on the current site to work. There are some big batches that currently do not: Alexandria and lots of the covid19cellatlas data for example

**Comment by Bento007** [comment]
- Is this depended on the deployment of corpora prod. 
- Where will these dataset be visible from, prod, dev, staging?

**Comment by mckinsel** [comment]
This is talking about loading everything into prod I believe. So yeah would depend on corpora prod to finish it.

**Comment by maniarathi** [comment]
In order for the cellxgene link to be launchable from the portal, we need to update the script to add the cellxgene link to the database. For each dataset, this can be done by creating a `DeploymentDirectory` ORM object, populating it with the dataset ID and cellxgene link, and marking the environment as PROD to indicate that this is publicly launchable cellxgene link.

**Comment by ambrosejcarr** [comment]
@mckinsel does it make sense to tackle chanzuckerberg/single-cell#24 while writing the remix script?

**Comment by mckinsel** [comment]
The 18 remixable M1 datasets are in the prod database, showing up in the API, and visible on cellxgene.cziscience.com.
