### ISSUE TITLE
Design interim solution for downloading expression matrices

### ISSUE THREAD

**Issue by pdugan20** [chanzuckerberg/corpora-data-portal#514]
This will be the UI that supports [this eng requirement](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/16).

This will in part borrow from the earlier revisions @liaprins-czi did, which can be [viewed here](https://www.figma.com/file/aI3bt6MRFJODNnI4q9DGN8/9-Browser?node-id=0%3A1).

Borrowed from the eng ticket:

> For the original data set the format is limited to one standard format:
> 
>     H5AD - because the curation process creates an H5AD as part of creating a CXG
> 
> For the remix data set, the formats are:
> 
>     AnnData
>     Loom
>     Seurat v3 RDS

**Comment by brianraymor** [comment]
Issue moved to [chanzuckerberg/single-cell #17](https://github.com/chanzuckerberg/single-cell/issues/17) via [**ZenHub**](https://www.zenhub.com/)
