### ISSUE TITLE
Implement UI for downloading expression matrices PART 2

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#518]
What:
1. Implement the `<DownloadDataSet />` component, starting from [this mock](https://chanzuckerberg.invisionapp.com/share/K6YKM66VU8J#/screens/429923778)

2. Integrate with https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/602

3. Work with BE to figure out the POST endpoint interface `/dataset/{id}` and what the response shape looks like

4. Write e2e tests to assert the user flows #2 and #3 below work:

User flow:
1. When a user visits `cellxgene.cziscience.com/`, they see the datasets with a new column "Download dataset" and its "download" button
2. On "download" button click, a modal shows up with the dataset's information
3. The user can now select a dataset format either copy the CURL command OR click the "download" button to download the dataset

[Part 1 ticket](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/602) will implement column and trigger the empty modal, which `<DownloadDataset />` will be nested in

=============== ORIGINAL DESCRIPTION BELOW ===============
Designs are now available:

1. Interactive flow: https://chanzuckerberg.invisionapp.com/share/K6YKM66VU8J#/screens/429923777
2. Figma: https://www.figma.com/file/hy3wOqrKbunH1C3lA7CuP6/download-dataset?node-id=0%3A1

Requirements:
1. Implement non-resumable download and CURL command as shown in the mock
2. Add download column in the datasets page (current homepage)
3. Add modal according to the mock
4. Work with BE to figure out the POST endpoint interface `/dataset/{id}` and what the response shape looks like
5. Add E2E tests for the feature
6. Perhaps use `clipboard-copy` for copying CURL command

User flow:
1. When a user visits `cellxgene.cziscience.com/`, they see the datasets with a new column "Download dataset" and its "download" button
2. On "download" button click, a modal shows up with the dataset's information
3. The user can now select a dataset format either copy the CURL command OR click the "download" button to download the dataset

Context:
1. When the user clicks on the "download" button on the dataset row on the homepage, the modal opens and fetches the download link by sending a POST to `/dataset/{id}`, which returns the link as specified in https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/476 (which means we might need loading state)

2. We then use the download link to populate the the CURL command and the download button!

**Comment by tihuan** [comment]
@mckinsel Do we know the file size distribution? Like mix, max, median, etc.. Just wanted to get a sense of whether we need to implement resumable download if the file size is too big. Thank you!

**Comment by brianraymor** [comment]
@mckinsel says 7 GB is the largest dataset. 

Agreed during 8/18 Refinement to cost Resumable upload.

**Comment by bmccandless** [comment]
Are we planning any kind of fault tolerance, incremental download?  I think as datasets get very large, the download time may start to be a real problem.

**Comment by tihuan** [comment]
Timmy will work with Pat to break down the tickets

**Comment by tihuan** [comment]
@bmccandless Yes! Great concern 👍 

Dataset download will be implemented in different stages, the first step is shipping non-resumable download, and then we'll have time to spike on resumable download, and deliver that in later Sprints 🤩!

**Comment by tihuan** [comment]
@Bento007 @mckinsel Now thinking about it, I need help figuring out what the CURL template that user copies should look like lol 

Thank you!

**Comment by mckinsel** [comment]
I think you just want
`curl -o "<filename>" '<presigned_url>'`

**Comment by tihuan** [comment]
Oh perfect 🤩 Thanks so much, @mckinsel 🙏🙏🙏!
