### ISSUE TITLE
[Infra] Integrate DP Smoke Test with CI/CD

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#519]
Given that we're deferring DP's CI/CD deployment setup to Release 2+, we can hook smoke test integration into CI/CD once the setup is done too

Requirement:
1. After the deployment stage of our CI/CD pipeline, add a step that runs the smoke test on the new deployment

TEAM COMMENTS:
1. We're missing FE e2e tests against staging and prod! We already have the e2e commands in `package.json`, so we just need to use them in Github Actions!

**Comment by tihuan** [comment]
Ah @brianraymor I see this issue was removed from Release 2, can you remind me the reason please 😄? Thank you!

**Comment by maniarathi** [comment]
Add the frontend tests -- we currently execute the backend tests.

**Comment by Bento007** [comment]
dev: https://github.com/chanzuckerberg/corpora-data-portal/blob/2c6a0e7588737aaa5ac5cb13f134c73f6699eadb/.github/workflows/deploy.yml#L88
