### ISSUE TITLE
[Infra] Terraform Enterprise Migration for api.cellxgene.cziscience.com

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#520]
Context:

Infra Team will work with us to migrate to Terraform Enterprise

What:

1. We want Terraform config for api.cellxgene.cziscience.com to be using Terraform Enterprise

How:

1. Work with Infra Team to flesh out the details

**Comment by maniarathi** [comment]
Closing this ticket for now until we get more guidance on when the Terraform Enterprise migration might actually happen. At that point, we can create a new ticket.
