### ISSUE TITLE
Proposal for counts field 

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/corpora-data-portal#524]
Appetite: ? 

This question is limited to 10x scRNA/snRNA and Smart-Seq2-like assays.

Should the schema include a `counts` field? If so, how is it modeled per framework/assay? UMI counts from 10x for example.

**Comment by ambrosejcarr** [comment]
Addressing @mckinsel questions: 

1. What's the technical cost of leaving this optional? The requirement could be _"observation IDs for processed cells must be contained in the set of IDs of raw cells"_. I do **not** think we should _require_ unfiltered barcodes to be present, so if the cost of being unopinionated is high, I would suggest that raw and processed observation sets should match.
2. Do you mean the supplementary table that 10x generates? ([example link](https://cf.10xgenomics.com/samples/cell-exp/4.0.0/Parent_NGSC3_DI_PBMC/Parent_NGSC3_DI_PBMC_molecule_info.h5)) Do archives capture these data? If we confirm, I'd support an optional "links to more data" section, and decline to hold these data.
3. I think we need to treat transcripts like a separate data modality. Some thoughts on this below which could seed that epic. 

"Detected molecules of RNA per gene" (typical 10x 3' processing), "detected molecules of RNA per transcript" (transcript-aware RNA-seq processing, more commonly associated with SS2), "detected molecules of protein" (CITE-seq, CyTOF, MIBI), and "sequencing reads from promoter regions adjacent to genes" (sc-ATAC-seq) are separate data modalities and we should be aware of that in some way. 

They can all be reduced to "observations of gene", and we may want to enable that conversion, but we should be careful, deliberate, and have a separate set of rules for each modality. When we get to CITE-seq data, those naturally correspond better to transcript-level data. the [PTPRC gene](https://www.bio-rad-antibodies.com/cd45-characterization-isoforms-structure-function-antibodies-minireview.html) is a good example of where we'll get tripped up, and in the future I expect we'll start to see phospho (active) and non-phospho (inactive) forms of proteins detected with CITE-seq, introducing additional complexity beyond what's captured at the transcript level.

**Comment by brianraymor** [comment]
@ambrosejcarr to follow up on _Do we want unfiltered barcodes from 10x? We actually got some feedback from one person when shopping around the schema that the answer is yes, thought it was a nice-to-have. The problem is this would not be proper layer in any format as its dimensions are different._ and open a new issue as needed. The current position is that the answer is "no".

**Comment by brianraymor** [comment]
Issue moved to [chanzuckerberg/single-cell-curation #9](https://github.com/chanzuckerberg/single-cell-curation/issues/9) via [**ZenHub**](https://www.zenhub.com/)
