### ISSUE TITLE
[BE] Update database to add Remix cellxgene link

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#531]
What:
We want DP website to provide a Remix dataset's corresponding cellxgene link. E.g., cellxgene.cziscience.com/e/{file_name}.cxg

How:
We need to add Remix cellxgene link in the database, so we can include the link as part of the API response

**Comment by maniarathi** [comment]
The database already has the DeploymentDirectory table built. I have added a note in #508 to update the database population scripts to actually populate the contents of the table but no database changes are required, therefore closing.
