### ISSUE TITLE
Create loom and seurat rds files for remix datasets

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/corpora-data-portal#537]
The remix process produces h5ad and cxg representations of a dataset. We also want to provide loom and Seurat downloads for every dataset. So we need to create those for all the datasets as well.

- [x] Finalize code for performing conversions
- [x] Run on all datasets
- [x] Update DB with additional dataset artifacts

For the first point, anndata provides `write_loom` and sceasy provides an anndata to seurat function that appears to be somewhat widely used.

**Comment by maniarathi** [comment]
I almost think this can be split into two tickets to parallelize the work. One person could take on doing the Loom files and one could take on doing Seurat. What do you think @mckinsel ?

**Comment by mckinsel** [comment]
Oh....this is already done somehow. All the remix datasets have h5ad, cxg, loom, and a seurat rds.

**Comment by maniarathi** [comment]
Sweet lol
