### ISSUE TITLE
devops(conventional commits): Enforce conventional commits before merging to master

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#543]
# Need
As a developer, I want to standardize our git commit messages, so I can:
* Automatically generate change logs
* Uniformly determine the nature and scope of a commit
* Quickly determine if changes will result in a major, minor, or patch release.

# Approach
* Enforce the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/) standard in commit message when a pull requests is squashed and merged into the`main` branch. 
* Help transition developers to using the new convention by updating contributors guide with links to the [conventional commits documentation](https://www.conventionalcommits.org/en/v1.0.0-beta.2/).

# Definition of Done
* A github actions is created that prevents blocks PR from merging if the squashed commit message does not fit conventional commit standard
* contributor.md is updated with links to the standard.

**Comment by maniarathi** [comment]
Closing this for now -- it hasn't come up as a pain point in recent retros so let's reopen it if it comes up again.
