### ISSUE TITLE
Create local BE server + seed local database for E2E Tests 

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#546]
What:
1. We want to be able to run local e2e tests with local database + server

How:
1. Create CLI commands to seed local database + spin up a local API server that FE can hit
2. @Bento007 pointed out that API unit tests already have code that does something similar, so we just need to build on top of that?

    a. Postgres docker container: https://github.com/chanzuckerberg/corpora-data-portal/blob/ead93ab5fd9e8394855b7854dcd86852e3e86331/Makefile#L13

    b. Create and populate the DB https://github.com/chanzuckerberg/corpora-data-portal/blob/ead93ab5fd9e8394855b7854dcd86852e3e86331/tests/unit/backend/corpora/fixtures/database/__init__.py#L28

3. Work with @tihuan to create a `make` command to run local e2e test

Thank you!

**Comment by tihuan** [comment]
@Bento007 @mckinsel Do you think we should get this ticket done for Release 1 and perhaps add this in Sprint 2? If so, I'll add it to Refinement Backlog 😄 Thank you!

**Comment by mckinsel** [comment]
Yeah probably better sooner rather than later, though how close does [this](https://github.com/chanzuckerberg/corpora-data-portal/blob/main/tests/unit/backend/corpora/fixtures/database/__init__.py#L27) get us?

**Comment by tihuan** [comment]
SGTM! 

Yeah Trent was saying API tests already seed database via [this](https://github.com/chanzuckerberg/corpora-data-portal/blob/main/tests/unit/backend/corpora/fixtures/database/__init__.py#L27), so hopefully this ticket isn't a heavy lift

But it'd be cool if @mckinsel and @Bento007 can help estimate this ticket, so we can see if we can pull that in either this Sprint or next Sprint 🙏 

Thank you!!

**Comment by tihuan** [comment]
Hi @Bento007 ! Can you please help adding an estimate for this please? Thank you!
