### ISSUE TITLE
Update Data Portal Homepage to be close to Pat's design

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#556]
Designs are now available:

1. Interactive flow: https://chanzuckerberg.invisionapp.com/share/K6YKM66VU8J#/screens/429923777
2. Figma: https://www.figma.com/file/hy3wOqrKbunH1C3lA7CuP6/download-dataset?node-id=0%3A1

What:
1. We want top Navbar to be fixed, so scrolling the list doesn't make the navbar disappear
2. Remove the bottom logo/footer
3. Update dataset row height to match Pat's design as well as adding the zebra pattern
4. Change default `isLoading` to `true`, so Gatsby generated static page doesn't flash "Couldn't find any projects. Please try again!"
5. Update cellxgene link buttom text from "View in cellxgene" to "View" **[NO NEED THE ARROW]**
6. Fix cookie banner flashing

How:
1. For cookie banner:
It happens because by default the HTML will show the cookie banner, and then JS will hide it once it detects the user’s decision
We can change it by hiding the banner by default, and then show it if JS doesn’t detect the decision, so we avoid the flash of banner!

**Comment by brianraymor** [comment]
@tihuan - During the demo, @ambrosejcarr also noticed that the spacing had increased in the list. @pdugan20 - is there any other divergence from your design that needs to be addressed?
