### ISSUE TITLE
[Prod] Fix Safari Cookie Banner Button

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#557]
What:
Safari's cookie banner button is clipped

![Screen Shot 2020-08-27 at 12.12.45 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/e0dd87c3-273a-4ff4-a18b-da5cebda50c4)

How:
Make the experience as close to Chrome and Firefox as possible 🙏

![Screen Shot 2020-08-27 at 12.13.42 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/e7ee0a4d-d006-4ac4-b11e-bf7ef38241a1)

TEAM COMMENTS:
1. Timmy: At first glance, it feels like Safari has more spacing between the words, which could be the reason some chars get pushed to the second line. We can fix this by either allowing a more flexible button width or restrict word spacing. Personally feels like the former solution is easier than the latter 😆

**Comment by maniarathi** [comment]
FYI: will probably take longer than a 1 because I'm a frontend noob :D

**Comment by tihuan** [comment]
YOU CAN DO IT, @maniarathi !! 👏 🎉 

Since Safari has this weird between word spacing issue, maybe we can try replacing`width: 150px;` to:

```css
min-width: 150px;
max-width: Npx; /** whatever pixel width that makes the button looks great on Safari */
```

This way hopefully Chrome and Firefox will just use ~150px for the button, and only Safari will hit `max-width`!

The file is: `frontend/src/components/CookieBanner/style.ts:47`

Hope this helps! Thank you for taking on this 🚀 ⭐ !
