### ISSUE TITLE
Remove corpora.cziscience.com domain

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#559]
# Need
As part of the merging into a single cellxgene team we need to remove the old frontend website and api website.
The sites https://corpora.cziscience.com and https://api.corpora.cziscience.com must both be removed. This will require making changes to single-cell-infra as well as finding a new domain for https://api.corpora.cziscience.com.

# Definition of Done
- https://corpora.cziscience.com is removed
- https://api.corpora.cziscience.com is removed
- https://cellxgene.cziscience.com continues to display the datasets using the data-portal api.

**Comment by brianraymor** [comment]
Per September 24 Sprint Planning, @maniarathi and @mckinsel agreed that we should merge the three remaining issues related to corpora deprecation into one issue and assign an estimate of 1 (rather than three tickets each estimated at 1). Closing.
