### ISSUE TITLE
Add file size info in dataset

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#561]
Since the modal for the frontend of downloading matrices displays the file size per file, we need to populate the GET dataset API with file size information. We also need to update the database with a field for file size and calculate it for each dataset artifact.

**Comment by maniarathi** [comment]
Since the modal for the frontend of downloading matrices displays the file size per file, we need to populate the GET dataset API with file size information. We also need to update the database with a field for file size and calculate it for each dataset artifact.

**Comment by brianraymor** [comment]
@mckinsel - can we not simply use the common pattern of [`HEAD`](https://tools.ietf.org/html/rfc7231#section-4.3.2) to retrieve `Content-Length`?

For example:

* [How to determine the file size of a remote HTTP object](https://disjoint.ca/til/2016/05/17/how-to-determine-the-file-size-of-a-remote-http-object/)
* [Determine file size in JavaScript without downloading a file](https://bitexperts.com/Question/Detail/3316/determine-file-size-in-javascript-without-downloading-a-file)

**Comment by mckinsel** [comment]
Yeah I think that would be better. There's also an `object.content_length` attribute in boto3 if we have to use that for auth or something.

**Comment by maniarathi** [comment]
OK sounds good -- perhaps this ticket can be reworded to be a frontend ticket to fetch and display the files sizes in the modal then using @brianraymor's second suggestion link. The existing frontend UI ticket is size 8 anyways so this can be one of the sub-tickets of implementation.

**Comment by maniarathi** [comment]
Closing this ticket since the file size will be returned as part of the POST API to get a pre-signed URL for a dataset. Please see #476 for more information.
