### ISSUE TITLE
Add data for "More Information" column

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#562]
What:

We need to add "more information" data to the column as shown below

![Screen Shot 2020-08-27 at 6.08.28 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/c7ba5300-6fb4-4ccf-9212-a1f9a8c221dd)

How:
1. BE's API response should already have the needed information, so we just need to throw it in there per the mock

Context:

partial API response:

https://github.com/chanzuckerberg/corpora-data-portal/issues/562#issuecomment-682776893
```
"links": [
    {
      "name": "Human Lung Cell Atlas", 
      "type": "OTHER", 
      "url": "https://hlca.ds.czbiohub.org/"
    }, 
    {
      "name": "HLCA Github", 
      "type": "OTHER", 
      "url": "https://github.com/krasnowlab/HLCA"
    }, 
    {
      "name": "Synapse", 
      "type": "RAW_DATA", 
      "url": "https://www.synapse.org/#!Synapse:syn21041850/wiki/600865"
    }, 
    {
      "name": "EGA", 
      "type": "RAW_DATA", 
      "url": "https://www.ebi.ac.uk/ega/studies/EGAS00001004344"
    }, 
    {
      "name": "Human Lung Cell Atlas", 
      "type": "SUMMARY", 
      "url": "https://hlca.ds.czbiohub.org/"
    }
```

**Comment by tihuan** [comment]
Hi @mckinsel ! 

Quick question, I remember a month ago or so the BE API returns the "more information" links, but we didn't have the link names. Do we have that now? If not, I can create a BE story to add that! Thank you!

E.g., 

url: http://cmgm-new.stanford.edu/krasnow/
name: Krasnow Lab

url: https://github.com/krasnowlab/hlca
name: HLCA website

**Comment by mckinsel** [comment]
We're supposed to!  See here: https://github.com/chanzuckerberg/corpora-data-portal/blob/main/backend/config/corpora-api.yml#L610-L621

But I'm not seeing in the API response, let me poke around a little...

**Comment by mckinsel** [comment]
Alright, pending fix in #564

**Comment by mckinsel** [comment]
Merged, looks like it's working on dev:
```
  "links": [
    {
      "name": "Human Lung Cell Atlas", 
      "type": "OTHER", 
      "url": "https://hlca.ds.czbiohub.org/"
    }, 
    {
      "name": "HLCA Github", 
      "type": "OTHER", 
      "url": "https://github.com/krasnowlab/HLCA"
    }, 
    {
      "name": "Synapse", 
      "type": "RAW_DATA", 
      "url": "https://www.synapse.org/#!Synapse:syn21041850/wiki/600865"
    }, 
    {
      "name": "EGA", 
      "type": "RAW_DATA", 
      "url": "https://www.ebi.ac.uk/ega/studies/EGAS00001004344"
    }, 
    {
      "name": "Human Lung Cell Atlas", 
      "type": "SUMMARY", 
      "url": "https://hlca.ds.czbiohub.org/"
    }
```

**Comment by tihuan** [comment]
Amazing! Thanks so much, @mckinsel ! I'll add the API response to the FE ticket for context!
