### ISSUE TITLE
Consumers want a matrix download to have a meaningful filename

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#571]
For [Scientists can download annotated expression matrices from the portal dataset-view](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/16), there was agreement to use the **filename** for the download name. For this increment, the "-29-remixed" (-dsuid-remixed) must be eliminated from **filename**.

```
      "dataset_assets": [
        {
          "created_at": 1598479174.003882, 
          "dataset_id": "8e3bf114-5491-4855-99a1-83770a3f75fa", 
          "filename": "Single_cell_longitudinal_analysis_of_SARS_CoV_2_infection_in_human_bronchial_epithelial_cells-29-remixed.h5ad", 
          "filetype": "H5AD", 
```

---

Other options can be explored for customizing filenames based on consumer-defined formats and dataset metadata - [simple example](https://wiki.hydrogenaud.io/index.php?title=XLD_Configuration#.22File_Naming.22_tab).

**Comment by tihuan** [comment]
@mckinsel can you help check what needs to be done to meet the requirement, so the ticket is ready for estimate 😄? Thank you!

**Comment by mweiden** [comment]
@ambrosejcarr suggested we close this during the 2020-09-10. @mckinsel choose your own adventure!
