### ISSUE TITLE
Remove PII from API responses and close public access to APIs

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#576]
Currently the Corpora APIs return PII in the API response including the email of the project owner, contributors' emails and institutions. Until we get advice from Trust, we should remove all PII from API responses and close off public access to the APIs.

Definition of Done:
- [x] Place a notice on the API that it's for Private use and may change
- [x] Remove PII from API responses.

**Comment by maniarathi** [comment]
In the spirit of trying to be agile and since we'll need to figure out how to close down the API access after the api domain changes go in effect, what do you think about closing this ticket for now since the PII has been removed from the API responses?

**Comment by mckinsel** [comment]
I think @Bento007 is taking a quick look at turning off the swagger just to make the API somewhat less exposed.

**Comment by mckinsel** [comment]
Closed by #603 and #580
