### ISSUE TITLE
Include remixing as part of cellxgene CLI and add tests

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/corpora-data-portal#585]
"Remixing", that is, preparing a dataset so it meets the corpora metadata spec, was at first necessarily ad hoc and done only by a couple people at CZI. However, now we'd like to harden the process and make it accessible to people who are not engineers working on cellxgene. 

So, we're going to include it in the cellxgene CLI. The CLI already has a subcommand that primarily serves an internal use case: `cellxgene convert`. Also, we'll mark the command as "experimental" or something so users don't stumble into problems using it when they don't really want to. Note that this is just for taking an h5ad and turning into an h5ad that conforms to the spec. It doesn't include all the format conversions or anything with the data portal DB.

One of the big chunks of this work is actually testing all the remix code and bringing it into version control. The testing is nontrivial and includes resolving some bona fide questions about how the remix logic works.

- [x] Create `cellxgene validate` subcommand that takes an input h5ad and a config yaml and produces a conformant h5ad.
- [x] Add unit tests for all the ontology, gene symbol conversion, and layer manipulation functions
- [x] Add functional tests that verify that remixing preserves expression values for the common NormalizeData and SCTransform analysis paths.

**Comment by maniarathi** [comment]
Hang on, why should it live in the cellxgene CLI? Isn't the remixing logic portal-specific? Like eventually, the remixing will be automated and you'd want that code to live centrally in the corpora-data-portal repo instead of in the cellxgene repo, no?

**Comment by mckinsel** [comment]
Oh I'm super open to not putting it in the cellxgene cli. I thought we had talked about it and decided to go in this direction, though. I think the main advantage would be that it puts the tool in the hands of every cellxgene user rather than making it a separate thing that's only done at CZI.

**Comment by maniarathi** [comment]
Oh oops - I have completely forgotten about that conversation. 

re: remixing in the hands of the cellxgene user... that makes sense.

**Comment by mckinsel** [comment]
Addressed code review comments from @maniarathi , but for the time being we've decided to keep the remix logic in a separate branch.
