### ISSUE TITLE
API endpoint performance monitoring

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#598]
Context:
Related to https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/565

What:
We need to set up monitoring to ensure our API has reasonable performance

How:
- [ ] Write an automated scale test that reports out to an alert or summary statistics
- [ ] Scale test samples N projects from `/dp/v1/projects` for testing
- [ ] Deploy the tests for each deployment environment

**Comment by mweiden** [comment]
@MDunitz proposed Definition of Done for this ticket:
- [ ] Write an automated scale test that reports out to an alert or summary statistics
- [ ] Scale test samples N projects from `/dp/v1/projects` for testing
- [ ] Deploy the tests for each deployment environment

This would fold the desired changes you wanted in https://github.com/chanzuckerberg/corpora-data-portal/issues/618 into this ticket.

**Comment by MDunitz** [comment]
Todo
- [ ] add scale test to all environments
- [ ] replace list of project ids with list of project ids returned from /dp/v1/project
- [ ] update test with dialogue from ambrose "Response time percentiles (ms, approximated)" to the slack message
