### ISSUE TITLE
Custom Auth0 Page

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#600]
What:

1. Instead of using the default Auth0 Universal Login Page, we should use @pdugan20 's custom page!

  https://www.figma.com/file/wRek2pyjwgfooVH71HstdH/auth-flow?node-id=0%3A1
  
  **NOTE: Use page 9 as shown in the screenshot below, also two adjustments:**
  - Logo replace `Data Portal` with `cellxgene`, we can use the logo on DP homepage too by hosting that image on S3 and shared between Auth0 page and DP homepage
  - Sign up / login options are limited to just Google and regular email
  - <img width="718" alt="Screen Shot 2020-09-10 at 12 04 48 PM" src="https://user-images.githubusercontent.com/6309723/92824557-6c368880-f383-11ea-82d5-e0ed932023f7.png">

2. **We might want to use Terraform to store/manage our custom template for version control, so we'll need to sync with Infra how to set that up** <---- This one can be done in the [Auth0 Terraform ticket](https://github.com/chanzuckerberg/single-cell-infra/issues/168)!

**Comment by pdugan20** [comment]
Sure! https://www.figma.com/file/wRek2pyjwgfooVH71HstdH/auth-flow?node-id=0%3A1

**Comment by tihuan** [comment]
Yay! Thanks @pdugan20 !

Is it this one and just change "Data Portal" to "cellxgene"?

<img width="718" alt="Screen Shot 2020-09-10 at 12 04 48 PM" src="https://user-images.githubusercontent.com/6309723/92787384-e522e980-f35d-11ea-8dba-be0260e6a087.png">

**Comment by pdugan20** [comment]
Yup that's right!

**Comment by tihuan** [comment]
Awesome thanks a lot 😄 !!

@signechambers1 @bmccandless  do we know what sign up methods we want to allow in the first iteration? Just Google SSO and email?

Thanks!

**Comment by signechambers1** [comment]
@tihuan @bmccandless correct, we only need Google SSO and email. @bmccandless let me know if you disagree

**Comment by signechambers1** [comment]
The universal log in page provides enough customization for annotations launch so moving this ticket out of the annotations epic

**Comment by tihuan** [comment]
Awesome! Thanks so much, @signechambers1 😄 I'll update the ticket description accordingly now!

**Comment by mweiden** [comment]
2020-09-15 Refinement meeting: group decides to prioritize all identity providers other than ORCID.

**Comment by tihuan** [comment]
@brianraymor @signechambers1  Are you two OK punting this custom Auth0 page thing till 2021? Since it's cosmetic and doesn't affect functionality! Thank you!

**Comment by signechambers1** [comment]
Fine by me!

**Comment by tihuan** [comment]
Awesome! Thanks so much, @signechambers1 😄 !

**Comment by brianraymor** [comment]
It depends on how you intend to address the issue with the missing links to policies in the sign up dialog.

**Comment by tihuan** [comment]
For completeness, the missing links issue will be addressed [here](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/667) 👌 Thanks all!

**Comment by MDunitz** [comment]
Low priority --> Closed for cleanup
