### ISSUE TITLE
Add section that describes the datasets view to the datasets page of the data portal

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/corpora-data-portal#607]
#### Stories

_Scientists that come to the data portal need to understand what we are showing them in order to derive value from the data portal's capabilities._ 

#### Implementation

Add a section to the data portal data page as seen in [Pat's design](https://www.figma.com/file/hy3wOqrKbunH1C3lA7CuP6/download-dataset?node-id=0%3A1). 

![image.png](https://images.zenhubusercontent.com/5b2bd089a26e500c78d1a809/007c5c8f-80a3-45ab-82db-af3d808a85d7)

Currently, scientists can't "add their own". Instead, it should use the content hidden in the page header: 

> The cellxgene data portal is a repository of public, explorable single-cell datasets. If you have a public dataset which you would like hosted for visualization on this site, please let us know at cellxgene@chanzuckerberg.com.

**Comment by tihuan** [comment]
This should be 0.5 ticket, since it's just adding a div + one line in smoke test! Will add it to https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/602 🙏 Thank you!

**Comment by ambrosejcarr** [comment]
Closing, now covered in chanzuckerberg/corpora-data-portal#602 Per @tihuan 's comment above.
