### ISSUE TITLE
suggested tweaks to wording on the frontend

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/corpora-data-portal#616]
One the main page:

> The cellxgene data portal is a repository of public, explorable single-cell datasets. If you have a public dataset which you would like hosted for visualization on this site, please let us know at cellxgene@chanzuckerberg.com.

I believe "which" should be replaced with "that".  Also, I'd drop the "for visualization" can be dropped because it is also hosted not just for visualization (but also download, and more later).

> The cellxgene data portal is a repository of public, explorable single-cell datasets. If you have a public dataset that you would like hosted on this site, please let us know at cellxgene@chanzuckerberg.com.

On the download page:

> Select from an above data format to view download details.

I think this can be a bit more readable like this:

> Select a data format to view download details.

**Comment by brianraymor** [comment]
I have an existing [QA issue](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/622) with similar suggestions. I've merged your comments into that issue and am closing this one.
