### ISSUE TITLE
Scale test improvements

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/corpora-data-portal#618]
- use /dp/v1/projects to get list of all project uuids, and use those for testing
- add in note about units at top of slack message "Response time percentiles (ms, approximated)"

**Comment by mweiden** [comment]
@MDunitz to simplify the tickets here, I suggest that you close this ticket and fold the improvements you'd like to see into the definition of done in https://github.com/chanzuckerberg/corpora-data-portal/issues/598
