### ISSUE TITLE
[Safari] Dataset columns are not fixed length

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#621]
The _veer_ was discovered during QA using Safari Version 14.0 (15610.1.28.1.9, 15610):

![Screen Shot 2020-09-23 at 9.31.00 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/c0294088-b9b8-4f12-9e97-c470285a8f58)

**Comment by brianraymor** [comment]
@ambrosejcarr noted that the problem can also be reproduced on chrome with small window sizes.

**Comment by tihuan** [comment]
https://cellxgene.dev.single-cell.czi.technology/ PTAL! Thank you!

**Comment by brianraymor** [comment]
This looks correct.

**Comment by tihuan** [comment]
Thanks Brian! Moved to Ready for Prod!
