### ISSUE TITLE
Data portal slow to load despite api caching in cloudfront

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/corpora-data-portal#623]
## Underlying issue
- Data portal front end points at https://api.dev.corpora.cziscience.com/ instead of http://api.cellxgene.dev.single-cell.czi.technology/

**Comment by bmccandless** [comment]
Do we want to do caching in cloudfront?
I'm thinking about the case when we add new datasets to the database.  If we cache at the cloudfront level then we won't see the new datasets, right?  (unless we have a process to clear the cache after each new dataset is added).

**Comment by MDunitz** [comment]
This is an issue @Bento007 has raised concerns about as well. We've discussed invalidating the cache when we make changes in the db. Currently the cache only lasts an hour which should help somewhat. It may be worth organizing a larger group discussion to determine the best way to approach this.
