### ISSUE TITLE
icon-144x144.png (Download error or resource isn't a valid image)

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#624]
Reported by @bkmartinjr 

Staging is throwing (minor) console errors when I load it:
icon-144x144.png:1 GET https://cellxgene.staging.single-cell.czi.technology/icons/icon-144x144.png 404
13:59:02.710 (index):1 Error while trying to use the following icon from the Manifest: https://cellxgene.staging.single-cell.czi.technology/icons/icon-144x144.png (Download error or resource isn't a valid image)

What:
1. Add the pink favicon to Data Portal
2. Make sure prod build `npm run build && npm run serve` shows no error for `https://cellxgene.staging.single-cell.czi.technology/icons/icon-144x144.png` GET request

QA steps:
1. In staging https://cellxgene.staging.single-cell.czi.technology/icons/icon-144x144.png should not return 404
2. https://cellxgene.staging.single-cell.czi.technology should have pink favicon

**Comment by tihuan** [comment]
I think this is related to Data Portal not having a favicon yet!

![Screen Shot 2020-09-28 at 3.41.14 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/c8a95171-b3a4-44fa-bfb3-9c72ae9ee692)

@brianraymor it seems like cellxgene logo has both pink and black variations, so the favicon options we have are:

1. Both DP and cellxgene use pink
2. Both DP and cellxgene use black
3. DP use black and cellxgene use pink

Which one should we do? Thank you!

**Comment by brianraymor** [comment]
I defer to our designers - @pdugan20 and @colinmegill ... but it should be one color because there's one service.

**Comment by pdugan20** [comment]
I'm good with using the existing pink favicon!

**Comment by tihuan** [comment]
Awesome! Will update the ticket description to use the pink favicon 😄 Thanks all!

**Comment by tihuan** [comment]
just added definition of done, so I think the ticket is now ready for estimation! Thank you!

**Comment by tihuan** [comment]
This ticket can be closed after https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/765 is merged!

**Comment by brianraymor** [comment]
Closing per @tihuan 's comment above.
