### ISSUE TITLE
Enable HTTP Strict Transport Security and Content Security Policy (CSP) 

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#626]
**What:**
Currently Data Portal doesn't have HSTS and CSP

**Definition of Done**

1. Explore a viable way to implement CSP with Gatsby
1. Explore a viable way to implement HSTS with Gatsby, details below:
1. Worst case, if we can't find a viable way to do CSP properly with Gatsby, please create a design ticket to nuke Gatsby, and we'll figure out the next steps from there 👌 Thank you!

Per Sept 24, checkpoint with @sbeara:
_**Should have HSTS and CSP prior to launch or soon after**
HSTS, Content Security Policy, X-Frame-Options, X-Content-Type-Options_

See resources and details documented in previous (similar) [cellxgene issue](https://github.com/chanzuckerberg/cellxgene/issues/1237):

```
At a minimum, we’d want HTTPS enforced with HTTP Strict Transport Security enabled. Tablestakes:

Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: deny
```

*** TEAM NOTES ***

1. Timmy: Please read through the comments below for our preliminary research findings and ideas on why Gatsby is not CSP friendly and the potential workaround using Lambda@Edge. 

1. Please work with the team + Infra on exploring Lambda@Edge and/or any other solutions that could help us set CSP header in responses, taking into account that the hashed inline scripts will need to be generated at build time + readable by Lambda@Edge or whichever agent that sets the CSP header for us too

Thank you!

**Comment by tihuan** [comment]
Thanks @brianraymor ! Will add details to this ticket this week!

**Comment by tihuan** [comment]
@brianraymor I think we might need to turn this into a design ticket first

I encountered some issue researching this today, since Data Portal is using Gatsby to build a static website (different from how Meta and cellxgene's web app setup), it doesn't naturally play well with setting security related response header stuff as required, because the server is an S3 bucket

So my preliminary research points to using AWS Lambda@Edge to set the response header, but I want to dedicate more time to have a proper discussion with our team + infosec and infra to make sure we have the right solution before fleshing out the details

I'm thinking maybe a 3 would be enough!

Gatsby CSP issue: https://github.com/gatsbyjs/gatsby/issues/10890

If that sounds good to you I'll replace "refine me" with "design me"! Thank you!

**Comment by tihuan** [comment]
@brianraymor gentle ping 🙏 It feels like we might need to pull this into next sprint to work on design? Thanks!

**Comment by tihuan** [comment]
Sync'd with Brian offline, we'll pull this design ticket in for me to work on next sprint! Thank you!

**Comment by brianraymor** [comment]
@tihuan - are you aware of https://www.gatsbyjs.com/plugins/gatsby-plugin-csp/ which was noted in the security checklist.

**Comment by tihuan** [comment]
@brianraymor Thanks for the link! 

Yeah the thread https://github.com/gatsbyjs/gatsby/issues/10890 mentions the plugin, but since it serves CSP via HTML, it doesn't work for `report-uri`, which is needed for monitoring and also not the preferred way to serve CSP 😞 (https://developers.google.com/web/fundamentals/security/csp#the_meta_tag)

**Comment by seve** [comment]
Discussion started on slack in #ask-infra

**Comment by seve** [comment]
Call scheduled with infra tomorrow RE: Gatsby + CSP + migration

**Comment by tihuan** [comment]
Thanks so much for leading this, @seve !! Look forward to our meeting tomorrow 🤩 🎉 !

**Comment by tihuan** [comment]
@damien captured the following notes for us 🙏 Thanks so much again for your advices and insights!

Updating this thread and a ticket I'm using to track this request with action items/plans that came out of this meeting:

1. Single Cell Eng has a feature that takes user input that they plan to release by end of Q1. Prior to this feature, the static site in question was read-only. The release of this feature opens the site up to XSS attacks, which any CSP implementation would protect it from. I've advised the Single Cell Eng team to let their product people know that CSP is a hard requirement to securely launching that feature.

1. Single Cell Eng believes implementing CSP via meta tags to be trivial. They'll be giving this a shot as an easy way to implement CSP and unblock a new feature rollout.

1. Time allowing, Single Cell Eng hopes to migrate away from a Gatsby.js static site deployment to a more dynamic Express.js deployment. Express.js has built in facilities to allow for CSP implementation via response headers--important to note as response based CSP allows for reporting of CSP violations to our monitoring/alerting infra.

1. If either the meta-tag based CSP protections or the migration to Express.js cannot be done before the desired go-live date for the new user input feature, I've advised the Single Cell team to reach out to Infra for additional assistance. We can probably scrape something together using Cloudfront+Lambda to buy Single Cell Eng more time if they end up needing it.

I'll be noting all this in this week's on-call doc and in a ticket I'm using to track this conversation. :ok_hand:

https://chanzuckerbergteam.slack.com/archives/C94RQ5SBV/p1607466505036100?thread_ts=1607372238.494600&cid=C94RQ5SBV

**Comment by damien** [comment]
Thanks for looping me in! I think you guys have a good game plan, but again: feel free to reach out if you get stuck and are worried about not having some kind of CSP mitigation in place before launch. 💪 🚀 :shipit:

**Comment by damien** [comment]
Aside: We in Infra(Sec|Eng) recently saw another team publich a cztack TF module that uses [Cloudfront Lambda@Edge](https://docs.aws.amazon.com/lambda/latest/dg/lambda-edge.html) functions to [add HSTS headers](https://github.com/chanzuckerberg/cztack/pull/244). I figured we could do something similar for CSP headers as an approach of last resort if the meta-tag approach doesn't work and the Express.js migration runs longer than anticipated. 👌

**Comment by tihuan** [comment]
Ooh nice! OK that sounds great 😄👌  Thanks so much for sharing this too!
