### ISSUE TITLE
[BUG] Blish link is wrong

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#627]
Credit to @brianraymor for identifying it.

The Blish lab link is incorrect. It should be https://med.stanford.edu/blishlab.html instead of https://blishlab.sites.stanford.edu/. This needs to just get updated in the databases.

Definition of Done:
- [ ] New API endpoint in Portal that serves dataset metadata that currently is served in CXG.
- [ ] cellxgene explorer server needs to know about new API endpoint via configuration changes so that config endpoint returns said information.
- [ ] Test.

**Comment by brianraymor** [comment]
Per sprint planning, @mckinsel to refine this issue to incorporate a design for explorer to query the portal database for collection metadata.

**Comment by maniarathi** [comment]
@maniarathi to break this up into 2 3 point tickets.

**Comment by maniarathi** [comment]
Closing as #2008 and #779 now reflect the parallelized work to be done to accomplish this.
