### ISSUE TITLE
 Set up infrastructure to run validation and conversion of uploaded datasets

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/corpora-data-portal#633]
Submission of a new dataset to the portal requires a few steps:

1. Create a new collection or find an existing one.
2. Upload a file to the portal.
3. The portal verifies that the file follows the schema and converts it to different formats.
4. The new files are written to S3 and the portal DB is updated

Step (3) is kind of compute/memory heavy and requires some special infrastructure. This ticket is for setting that up across the three environments.

**Comment by lesliecodes** [comment]
Pair with infra!

**Comment by lesliecodes** [comment]
Check out code in old upload service

**Comment by brianraymor** [comment]
No longer required per conversation with @mckinsel.
