### ISSUE TITLE
Update Corpora database with small changes to accommodate API changes

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#636]
Need: the Corpora API has been modified to be simpler and follow the natural user flow more closely. We've also decided to rename "project" to be "collection." This means that a few database tweaks will be needed. Note: all the following changes will need to be applied in dev, staging, and prod.

Definition of Done: this ticket is primarily a database migration.
- [x] `visibility` is added to the Project table. This is an ENUM of either `private` or `public`. This is made to be part of the composite primary key. (This will need to trickle down into all the related tables where there is a foreign key relationship).
- [x] `status` is deleted from the Project table (and from the composite primary key).
- [x] `environment` is removed from the `deployment_directory` table.
- [x] `processing_state` is removed from the `project` table.
- [x] `validation_state` is removed from the `project` table.
- [x] `s3_uri` is removed from the `project` table.
- [x] `visibility` is added to the `project` table. This should be an ENUM -- one of `{private, public}` and defaults to `private`. Not nullable.
- [x] `obfuscated_uuid` is added to the `project` table. Is nullable.
- [x] `source_data_location` is removed from the `dataset` table.
- [x] `is_valid` boolean is added to the `dataset` table.
- [x] the `user` table is deleted.
- [ ] OPTIONAL: Any field or table using the term `project` is replaced with `collection`. 
- [ ] UML and ER diagrams in the Corpora High Level Architecture are updated to reflect reality.

Note: I'm skipping over adding any additional "processing_state" kind of field to the Dataset table. That ticket/work can be done once the Upload RFC is completed and we know with certainty what the possible enums are.

**Comment by maniarathi** [comment]
This ticket should be completed before any API work regarding collections is begun. Also cc-ing @mckinsel and @brianraymor to make sure that I didn't miss anything...

**Comment by Bento007** [comment]
@maniarathi if we remove the user table, how will we know who owns a project?

**Comment by maniarathi** [comment]
cc-ing @mckinsel as well, but I think where ever we need to store an owner id, we can make use of Auth0 IDs. We don't need to duplicate information that is stored in the Auth0 service so if need to pull additional information about the user later on, we can use their APIs to grab their email or whatnot. 

Sound right to you, Marcus?

**Comment by mckinsel** [comment]
Yeah, the user table really just stored name and email. I don't think we need that anymore since the auth0 key is essentially a foreign key to a much better user table.

**Comment by maniarathi** [comment]
I think this should still be in progress, @Bento007 . In QA generally means that the PRs are pushed through and Product uses the pipeline to know what they need to verify. The only time a ticket with an open PR should go into that pipeline is when it's a design/RFC ticket.

**Comment by maniarathi** [comment]
Going ahead and closing this, since it's an infra change and not a user-visible change.
