### ISSUE TITLE
Extend `GET /v1/collections` endpoint to return public collections and those owned by the user

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#637]
GET /v1/collections doesn’t need to accept optional visibility param, BUT, Back end needs to return all private collections owned by the user if logged in, so on the homepage, the user gets to see all public collections (whether they own or not) + all private collections they own

Definition of Done:
- [ ] Backend `GET /v1/collections` endpoint returns all public collections and all private collections owned by the user

## API Description
Lists all collections by their UUIDs that currently exist in Corpora. 

## Responses
200 OK: {request_id, collection_uuid, name, description, user_id}
400 Invalid parameter

**Comment by tihuan** [comment]
The following ticket will rename `/project` with `/collections`!

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/644

**Comment by mckinsel** [comment]
One possible additional filter: there may be datasets with a status that is "incomplete" in some way, either not done uploading or validating or converting or something failed.

**Comment by bmccandless** [comment]
Can a user see their own private projects from this API?

**Comment by maniarathi** [comment]
@mckinsel  They those projects wouldn't be able to get published publicly right? This endpoint would only be for public projects.

@bmccandless No. They would use `GET /v1/submissions`

**Comment by mckinsel** [comment]
@maniarathi , then I think the filter needs to go somewhere else. Suppose:

1. Submitter uploads a picture of a dog.
2. Upload starts, a row with a new dataset_id and appropriate collection_id gets inserted into dataset table.
3. Validation fails (hopefully), and error message gets written into dataset row.

Submitter then publishes the collection. What does this endpoint return?

**Comment by maniarathi** [comment]
Chatted offline so adding details here -- 

We haven't really talked about what "publishing" entails, but likely, it will involve
a) validating that the collection is valid (including the datasets)
b) rescinding the capability URL
c) database finagling if there are issues with changing the visibility of the collection since it's part of the primary key.

Regardless, it won't be possible to return a project that is **public** with errors.

HOWEVER, this API has been updated to just be the same regardless of whether we're working with private or public collections. You'll need to pass in the visibility to filter. So @bmccandless, I take back my previous statement and yes, you would be able to see private collections if you filter by private.
