### ISSUE TITLE
Upload Dataset: Figure out Google Drive FE integration

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#641]
Context:
1. According to the Upload Dataset priority, we want to allow users to upload datasets via Google Drive links

What:
1. Please figure out how to integrate Google Drive in our web app
2. Please check if it's possible to restrict max number of selected file and file types
3. Please create ticket(s) that will implement the integrations

**Comment by tihuan** [comment]
Related ticket for Dropbox: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/640undefined

**Comment by brianraymor** [comment]
Closing until self-publication stories return to the roadmap.
