### ISSUE TITLE
Upload Dataset Part 1 [Dropbox Integration]

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#642]
Design: https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Publisher-Collection?node-id=39%3A793

What:

**After finishing this PART 1 ticket, the user will be able to upload a dataset via Dropbox Chooser and FE will make an API call to the BE to kick start the upload process**

1. Please implement Dropbox Chooser following the [design](https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Publisher-Collection?node-id=39%3A894) - which includes the "Add Dataset" button. Right now we only allow Dropbox upload, so I don't think we need dropdown - @hthomas-czi please help confirm 🙏 Thank you!

1. Restrict to select ONE file for now / Direct download link

1. Call the relevant API to kick off the cloud to cloud transfer -- API TBD, since some discussion is still ongoing in Slack `#tmp-sc-collection-flow-ux`

1. API [here](https://github.com/chanzuckerberg/single-cell/blob/main/rfcs/0002-upload-from-dropbox/text.md#data-portal-apis), please also double check with Marcus and Trent to make sure that's the latest/correct API doc

Research notes:
1. Dropbox Chooser library: https://www.dropbox.com/developers/chooser
2. Need a Dropbox app in App Console
3. Need to create a CZI Dropbox account
4. Need to specify deployment web app links (dev, staging, prod)
5. Embed their script through Dropbox CDN
6. The Chooser option config section allows direct download link, multiselect, file types, size limit, etc.. Super convenient!
7. Direct download link expires in 4 hours
8. Looks like we need to call `Dropbox.isBrowserSupported()` to see if the browser supports it. (I've confirmed that the latest Chrome, Firefox, and Safari all work)
9. Contact IT to create Dropbox account for us!

**Comment by tihuan** [comment]
Keeping this as "Refined Me!", since API calls are not finalized yet!

**Comment by tihuan** [comment]
10/27 Update: Added API doc: https://github.com/chanzuckerberg/single-cell/blob/23bd9e23d17229747b8cf7193fdd40f7a3175352/rfcs/0002-upload-from-dropbox/text.md

Now waiting for design to finalize! Thank you!

CC: @brianraymor @hthomas-czi

**Comment by tihuan** [comment]
Hi all! I just added the following user story:

**After finishing this ticket, the user will be able to upload a dataset via Dropbox Chooser, see the dataset processing updates (success, pending, error), and download dataset in all three formats as well as visit the dataset's CXG link**

The part I left out is the ability to cancel the process, since I'm a little unclear when we want to stop allowing users to cancel. 

One option is to only allow cancel while the dataset is being uploaded, but once upload is complete and validation starts, they can no longer cancel. And then they will be able to delete the dataset when we deliver that feature. Does that sound good?

Thank you!

CC: @brianraymor @hthomas-czi

**Comment by brianraymor** [comment]
RE Timmy's [question](https://github.com/chanzuckerberg/corpora-data-portal/issues/642#issuecomment-717432112):

> The part I left out is the ability to cancel the process, since I'm a little unclear when we want to stop allowing users to cancel.

@mckinsel and @Bento007 - when will the upload RFC be updated based on yesterday's presentation?
