### ISSUE TITLE
Identify single value (continuous and categorical) fields during dataset curation

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/corpora-data-portal#643]
## Need
- As a user I dont want to see histograms or placeholders for histograms for categories that only contain a single value. 

## Approach
To avoid needing to check all of the data on the frontend (which is slow and leads to the display of category names in the rsb that we wont create histograms for) we would like to identify continuous variables as categorical when they only contain a single value. This should be done when retrieving the schema (there should be no changes to the actual dataset)

**Comment by MDunitz** [comment]
Update from discussion with @maniarathi @mckinsel @seve @signechambers1 @colinmegill 
We will add a check when creating the schema in the data adaptor, if a continuous variable stores the same value for all of the cells it will be redefined as a categorical variable. 

This may require recreating the schemas for datasets already in hosted cellxgene

**Comment by mckinsel** [comment]
Wait I thought it was not going to require recreating schemas. You just stick in some logic around [here](https://github.com/chanzuckerberg/cellxgene/blob/main/server/data_cxg/cxg_adaptor.py#L373) that detects single-valued continuous variables (and similarly in the anndata adaptor).

**Comment by maniarathi** [comment]
+1 to what Marcus said -- there shouldn't be any recreating of schemas. The API response for get schema is the only thing that should change.

**Comment by MDunitz** [comment]
Sorry misunderstood, I updated the ticket description

**Comment by brianraymor** [comment]
Issue moved to [chanzuckerberg/cellxgene #2010](https://github.com/chanzuckerberg/cellxgene/issues/2010) via [**ZenHub**](https://www.zenhub.com/)
