### ISSUE TITLE
Refactor `project` APIs to read `collections`

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#644]
## Need
We are moving away from the notion of "projects" and instead using the term "collections" to represents groups of datasets. In order to reduce future confusion, we'll refactor current use of `project` in the API to instead read `collections`.

## Definition of Done
- [x] Rename all current `/project/` APIs to instead be `/collections/`.
- [x] Update the frontend calls to make use of the renamed APIs.
- [x] Update the High level architecture RFC to reflect the latest API definitions.

**Comment by MDunitz** [comment]
Do we need/want to update the API version when we do this?

**Comment by maniarathi** [comment]
@MDunitz Good question.. I'm inclined to say keep it at the same version since we really don't have any external users.

**Comment by bmccandless** [comment]
@maniarathi Does this refactor only refer to the API?
The Database will still have Projects?

**Comment by bmccandless** [comment]
@maniarathi The images in the high level architecture are in png format.   I won't be able to change those, but I can change the text.
