### ISSUE TITLE
Extend `GET /v1/collections/{collection_uuid}`

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#645]
## Description
Returns all available metadata information about a project submission, including URIs of datasets that are attached to the project.

## Parameters:
- collection_uuid [REQUIRED]: the UUID of the project on which information is being requested.
- visibility [REQUIRED]: whether the collection to query is a private collection or a public collection.
- user_id [OPTIONAL]: the OAuth id of the user trying to access a the private collection.

Responses:
200 OK: Response payload will be a schema with all fields that are associated with a submission. Also return the `access_type` which is one of `{READ, WRITE}`.
401 Unauthorized user
404 Submission not found

Implementation details:
- Given the collection_id and the user_id, find the appropriate collection data (and children data like datasets, etc.) from the database.
- If the collection_uuid matches a collection_uuid in the database and the `owner` of the collection does not match the inputted `user_id` (or none is given) return a 401.
- Otherwise if collection_uuid matches a collection_uuid in the database and the `owner` of the collection matches the `used_id`, return the collection data with `access_type=WRITE`.

**Comment by Bento007** [comment]
I would prefer to have a different endpoint for resolving the obfuscated URLs.

**Comment by maniarathi** [comment]
I think having a separate endpoint for resolving obfuscated URLs doesn't make much sense. If someone navigates to a collection page using the obfuscated ID, how would the frontend know that it needs to query a different endpoint?

From purely an input/output standpoint, the two endpoints would exhibit exactly the same behavior as well. I don't see much complexity in checking the database whether the ID is the obfuscated ID or the real UUID of the collection.

**Comment by Bento007** [comment]
Connexions does not allow us to have an endpoint with an optional security field. This means we can not support this endpoint to both retrieve private collections using the user_id, and retrieve public collections requiring no auth.

**Comment by tihuan** [comment]
ahh I see! So from FE's point of view, if a user is logged in, we can use endpoint 1, and if logged out use endpoint 2? That would work for FE!
