### ISSUE TITLE
Routes Scaffolding

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#647]
Context:
This ticket is to provide the infrastructure and scaffolding needed to build the two new pages (**/collections/{id}**, and **/my-collections**)

What:

1. Build Feature Flag detection for param `?cc={1 or 0}` at app initialization. Store the feature flag in LocalStorage. Also create helper functions for another components to check for this feature flag in URL param and localStorage

1. Use React-Router v5 to handle routes and renders corresponding pages

1. Create views/ directory and the two new Collection pages as placeholders

**QA notes:**
1. We can check if feature flag: `cc` works in staging and prod:
Steps:
a. Check your `localStorage` and make sure `cxg-ff-cc` key doesn't exist or is `false`
b. Modify URL to add `?cc=true`. E.g., `http://localhost:8000/?cc=true`
c. Now you should see `cxg-ff-cc` to be `true`!
![Screen Shot 2020-10-26 at 9.53.49 AM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/2a791d7e-f1a4-4b50-a083-85328e67d8af)
d. Profits 💰!
Thank you!

**Comment by bmccandless** [comment]
What does cc mean in `?cc={1 or 0}`?

**Comment by tihuan** [comment]
Ah sorry just saw this, @bmccandless !

`cc` stands for `Create Collection` (apologies for missing this in the description!)

I wanted to allow setting feature flag via URL param `cc=0` to turn off and `cc=1` to turn on, and the config is persisted in `LocalStorage`! An example will be: `www.cellxgene.cziscience.com?cc=1` to turn on Create Collection related features. Like, `/my-collections`, `/collections/{id}`, and seeing "New Collection" button on the homepage 😄

**Comment by tihuan** [comment]
Thanks for adding me as assignee, @brianraymor 🙏 Sorry for missing that!
