### ISSUE TITLE
My Collections Page

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#650]
Context:

This ticket implements the My Collections Page.

Figma: https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Publisher-Collection?node-id=36%3A1457

NOTE: Please use to the latest design [here](https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Collections?node-id=0%3A1) and sync with @harley on which Blueprint components to use

What:

NOTE (11/6/2020): The API below may have changed, please sync with BE peeps for the right endpoints to use! Thank you!

1. Route: `/my-collections`

1. Use `GET /collections` to get all the collection ids that belong to this user

1. Use `GET /collections/{id}` to retrieve each collection's data

1. Use directory `/views/MyCollections` to construct the page

1. Use React Query to build queries where necessary

**TEAM NOTES**
1. Part 2 ticket: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/737

**Comment by seve** [comment]
Lost ~3 days due to Veterans Day, meetings, and interviews.  Should be seeing a PR today or tomorrow
