### ISSUE TITLE
Infra for upload step function

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#654]
# Need
To support the upload service, new infrastructure must be deployed to support queuing upload and streaming the files.

# Approach
- Create a step functions that can be invoked from the data portal backend.
- Ensure that IAM and SecretsManager are setup to be able to talk to the database and S3.

** IdSeq Approach**
- configure the step function using YAML. See how ID Seq does it, https://github.com/chanzuckerberg/idseq/tree/main/workflows/terraform/sfn_templates
- Convert the YAML to JSON: https://github.com/chanzuckerberg/idseq/blob/main/workflows/Makefile#L20
- Apply the step function using terraform: https://github.com/chanzuckerberg/idseq/blob/main/workflows/terraform/sfn.tf 

# DoD
- The backend can invoke the step function
- The IAM policy for the Data Portal Backend his permission to invoke the step function.

**Comment by brianraymor** [comment]
Per conversation with @mckinsel - this issue to be refined and re-estimated to include validation and conversion.

**Comment by mckinsel** [comment]
Is permissions for the container to write to the DP db and the artifacts/deployment buckets part of DoD?

**Comment by Bento007** [comment]
@mckinsel no, it should be a part of the container ticket
