### ISSUE TITLE
POST collections/{collection_id}/upload/link (Part 2)

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#655]
# Need

If the dataset fails to upload, the user needs a way to restart the upload.

# Approach
- If the dataset_id is provided in the request body, and the dataset submission is in a failed state, the upload job is restarted.
- A new upload step function job is started.

# DoD
- Update the `POST collections/{collection_id}/upload/link` to accept and optional dataset_id parameter. If the upload is in a failed state, with this endpoint is called, the upload job is added back onto the upload queue. The state of the upload is changed to waiting.

# Notes
- [link to API](https://github.com/chanzuckerberg/single-cell/blob/main/rfcs/0002-upload-from-dropbox/text.md#data-portal-apis)

**Comment by brianraymor** [comment]
During November 10 Refinement, we agreed to address this issue **after** the basic functionality was in place.

**Comment by brianraymor** [comment]
Closing per January 5th refinement.
