### ISSUE TITLE
Infra for upload container repository and batch environment

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#657]
# Need
The container with all the upload logic (see #680) needs to be deployed on AWS so it can execute in response to upload requests.

# Approach
1. Create and ECR repository for the upload container
2. Create a batch compute environment and job definition.
3. Set the job permissions so it can access ECR and write to the portal's S3 buckets.

Note that we originally were going to do this in Fargate. But Fargate has a 30GB memory maximum, and one of the container's R scripts requires much more.

# DoD
- The container defined in #680 can be pushed to ECR.
- A batch job can be manually started that successfully pulls a file from Dropbox and copies converted files to the correct S3 buckets.

**Comment by lesliecodes** [comment]
Separate out retry + other pieces @Bento007
