### ISSUE TITLE
Verify Upload integrity

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#658]
# Need

We need some kind of check to be certain that the file upload to S3 matches the files stored in DropBox.

# Approach
- Verify the file while streaming to S3
- Using the hash from dropbox verify the download matches the hash. https://www.dropbox.com/developers/reference/content-hash
- Verify the integrity of the upload to S3 using content-MD5 header https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#API_PutObject_RequestSyntax 
- Calculate the final hash of the upload to S3 and make sure it matches.
- If the hashes don't match, move the job back to the upload queue.

# DoD

- A message is logged that indicates the hash has been verified for both DropBox and S3. The expected hash values should appear in the logs.

**Comment by brianraymor** [comment]
During November 10 Refinement, we agreed to address this issue **after** the basic functionality was in place.

**Comment by brianraymor** [comment]
Closing per January 5th refinement.
