### ISSUE TITLE
DELETE datasets/{dataset_id} to cancel an upload

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#660]
# Need

Provide a method for a user to cancel an upload that is in progress.

# Approach
- Set the `upload_status` to `Cancel Pending`. 
- Update the upload/validation container to poll the `upload_status` and cleanup the current upload if the status is `Cancel Pending`
- Clean means delete anything uploaded to s3, set the `upload_status` to `Canceled`, and shut down the container gracefully.

# DoD

- an upload can be canceled if it has not reached the `uploaded`, `upload_status`
- The upload_status is changed to `Canceled` after successfully canceling and upload.
- A Canceled upload can be restarted using the POST submissions endpoint with the dataset_id.

# Notes
- [API Documentation](https://github.com/chanzuckerberg/single-cell/blob/main/rfcs/0002-upload-from-dropbox/text.md#delete-datasetsdataset_id)

**Comment by MDunitz** [comment]
Can anyone cancel a download? or only the owner?

**Comment by MDunitz** [comment]
No longer need to delete from s3 because no artifacts should be added before the status has changed to UPLOADED.
See https://github.com/chanzuckerberg/corpora-data-portal/pull/799#discussion_r554132464
