### ISSUE TITLE
Update Data Portal Database for Uploads

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#662]
# Need
[New Table Changes](https://github.com/chanzuckerberg/single-cell/blob/main/rfcs/0002-upload-from-dropbox/text.md#database-schema)

The database must be updated to support the upload, validation, and conversion tasks information that will be communicated to the user. The `dataset_processing_status` is a database table that tracks the current status of the upload, conversion, and validation tasks. 

# Approach

- [ ] create upload_status enum
- [ ] create validation_status enum
- [ ] create conversion_status enum
- [ ] create the `dataset_processing_status` table
- [ ] create the database migration

# DoD

- The dataset table contains the new fields
- The forward and backward migration code is written and tested
- All stages have been migrated to this schema.

**Comment by tihuan** [comment]
Please do a test migration! @Bento007 has instructions 🙆🏽‍♂️
