### ISSUE TITLE
Publisher Experience – Collection view, dataset view

### ISSUE THREAD

**Issue by hthomas-czi** [chanzuckerberg/corpora-data-portal#665]
**Requirements**
Collection view
- All collections should display title, contributors, preprint_doi, publication_doi, organisms, tissues, assays, and the total number of cells measured for all datasets in the collection [72](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/72)

Dataset view
- Page should show collection title and description
- Each dataset should display organisms, tissues, assays, and the total number of cells measured for all datasets in the collection [72](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/72)

Figma: https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Collections?node-id=55%3A727

Reference: https://github.com/chanzuckerberg/corpora-data-portal/issues/364

**Comment by brianraymor** [comment]
Closing this issue in favor of our shared design epic - [Publishers want to create a private collection for related dataset submissions](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/23)
