### ISSUE TITLE
Publisher Experience – Add dataset

### ISSUE THREAD

**Issue by hthomas-czi** [chanzuckerberg/corpora-data-portal#666]
**Requirements**
- Users should see their progress through each of the three steps in the `add dataset` process (upload → validation → conversion)
  - [Upload progress](https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Collections?node-id=235%3A0) will update every 10 seconds
  - Validation and conversion will be combined on the front-end as a single `processing` step 
  - [Processing](https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Collections?node-id=39%3A1019) will show indeterminate progress and skeleton for unprocessed metadata
- Users should be informed if there is an error
  - [Upload error](https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Collections?node-id=248%3A0)
  - [Validation errors](https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Collections?node-id=100%3A276)
  - [Conversion errors](https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Collections?node-id=174%3A434)
- Users should have access to functionality as it becomes available (e.g., can open in cellxgene explorer even if .rds conversion is incomplete) [Partial conversion](https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Collections?node-id=201%3A0)

Figma: https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Collections?node-id=39%3A793

**Comment by brianraymor** [comment]
Closing this issue in favor of our shared design epic [Publishers want to upload a .h5ad dataset to a private collection from dropbox](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/26)
