### ISSUE TITLE
Fix Auth0 Sign Up / Sign In Pages to add ToS and Privacy Links

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#667]
Currently our sign up Auth0 page doesn't provide links to our [ToS](https://cellxgene.cziscience.com/static/cellxgene/deploy/tos.html) and [Privacy](https://cellxgene.cziscience.com/static/cellxgene/deploy/privacy.html) pages 

![Screen Shot 2020-10-21 at 6.49.22 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/d92f20c5-97fe-478e-aafa-417d1f16f38f)

What:
I **think** it's possible to use Auth0 Custom Page to minimally modify the current Lock.js design to add the page links

===TEAM COMMENTS===
1. Timmy: I didn't spend enough time to explore Auth0 Custom Page to see how much we can customize the Auth0 Lock design. But the following two pages should be a good starting point!

https://auth0.com/docs/libraries/lock/lock-ui-customization
https://auth0.com/docs/libraries/lock/lock-api-reference

**Comment by tihuan** [comment]
The change is now live in prod:

https://login.cellxgene.cziscience.com/login?state=g6Fo2SB0enh5YkFLd0UzeVJnVU1qakVpOVVaOWgwcjl2S1h2eaN0aWTZIEg0Q3p2NTBHRjlETzFnUWxFcTlEU1NsNEcwR2FiNjROo2NpZNkgOUc5SmJXMEw4U0RQSm1ycWd2R3JUSGtwWlRRNHliS0o&client=9G9JbW0L8SDPJmrqgvGrTHkpZTQ4ybKJ&protocol=oauth2&response_type=code&redirect_uri=https%3A%2F%2Fapi.cellxgene.cziscience.com%2Fcellxgene%2Foauth2%2Fcallback&scope=openid%20profile%20email%20offline_access&nonce=ANxH0zLK960J9kB0xnzu

Or click on `login` here: https://cellxgene.cziscience.com/experimental/krasnow_lab_human_lung_cell_atlas_10x-1.cxg/

PTAL! Thank you!

**Comment by maniarathi** [comment]
@brianraymor to QA then close.

**Comment by brianraymor** [comment]
Looks good. The only other odd thing is that the cellxgene "title" on Log in:
<img width="365" alt="Screen Shot 2020-10-23 at 10 03 00 AM" src="https://user-images.githubusercontent.com/3644743/97032760-2985d580-1517-11eb-8610-b7aaee7dd4af.png">

changes to "Sign up" on Sign up:

<img width="360" alt="Screen Shot 2020-10-23 at 10 03 08 AM" src="https://user-images.githubusercontent.com/3644743/97032821-3dc9d280-1517-11eb-9f09-44158c02df69.png">

**Comment by brianraymor** [comment]
Also shouldn't **C**ellxgene be cellxgene? @colinmegill - cellxgene is always lower-case? As in _**cellxgene (pronounced “cell-by-gene”) is an interactive data explorer**_

**Comment by tihuan** [comment]
Ahh! I'll defer to you two to decide whether we want `Cellxgene` or `cellxgene`, and I'll update accordingly! Thank you!

**Comment by colinmegill** [comment]
Lowercase!

**Comment by tihuan** [comment]
Awesome! Thank you! Done 😆 🎉 

https://login.cellxgene.cziscience.com/login?state=g6Fo2SBUVzNrcTZxR0NhbkplejVNWnlnbjI5YjU2bWpmeUxtSqN0aWTZIHNJSHgtUkZVdk9IYXE0VlBCREdPVGwtSVJSbFVhT2Fxo2NpZNkgOUc5SmJXMEw4U0RQSm1ycWd2R3JUSGtwWlRRNHliS0o&client=9G9JbW0L8SDPJmrqgvGrTHkpZTQ4ybKJ&protocol=oauth2&response_type=code&redirect_uri=https%3A%2F%2Fapi.cellxgene.cziscience.com%2Fcellxgene%2Foauth2%2Fcallback&scope=openid%20profile%20email%20offline_access&nonce=UPiVWtExYQKhvBzB5kV3

<img width="1206" alt="Screen Shot 2020-10-23 at 11 19 05 AM" src="https://user-images.githubusercontent.com/6309723/97039705-b03fb000-1521-11eb-8007-5fc40183b686.png">
