### ISSUE TITLE
 Warn cellxgene data portal users that Safari will not be supported

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#699]
- [ ] cellxgene data portal must detect Safari and display a warning that Safari support is being deprecated by January 8 2021.

[Design](https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Publisher-Collection?node-id=604%3A0)

TEAM NOTES:
1. We could use `if (navigator.userAgent.indexOf('Safari') != -1 && navigator.userAgent.indexOf('Chrome') == -1) {alert('Its Safari');}` to detect Safari!

**Comment by maniarathi** [comment]
Pair with #1975

**Comment by brianraymor** [comment]
We agreed during _sprint drafting_ to not warn users before deprecating safari.
