### ISSUE TITLE
Upload Dataset Part 4 [Delete Dataset/Cancel Upload]

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#706]
Design: https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Publisher-Collection?node-id=493%3A225

What:

**After finishing this PART 4 ticket, the user will be able to delete/cancel a dataset**

[Delete Dataset](https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Publisher-Collection?node-id=547%3A136)
**No need to do delete collection**

![Screen Shot 2020-11-10 at 11.11.16 AM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/54dc6bbe-7594-444d-a975-e499beb49888)

1. Render the dataset entry as a row, as shown in design [here](https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Publisher-Collection?node-id=235%3A0) -- Please double check with @hthomas-czi this is the correct design 🙏

1. API doc is [here](https://github.com/chanzuckerberg/single-cell/blob/main/rfcs/0002-upload-from-dropbox/text.md) - to delete a dataset, call the `DELETE` endpoint

1. BE tickets [here](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/652)

**User Flows:**

1. Notice that the trash can button at the dataset row, on hover will expand and show text "Delete" in addition to the icon (please reach out to Harley if the mock doesn't reflect this hover behavior)

1. On trash can / delete button click, we show a confirmation modal as a checkpoint

1. Once user decides again to delete, we send a POST call to backend. If we get success response, we refetch all datasets, and the pending delete dataset should no longer be displayed

1. Please note that since cancel also hits the same `DELETE` endpoint, we'll also implement the cancel flow in this ticket!

**Comment by brianraymor** [comment]
Refinement note from @tihuan - _706 (Delete / Cancel Dataset) has a slight coupling with 705, because of the conversion cancellation trash can. But I think all three tickets can still be done in parallel, and I can create an integration ticket between 705 and 706 for 1 point, if we end up parallelizing 705 and 706!_
