### ISSUE TITLE
Remove Cloudfront

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/corpora-data-portal#708]
Currently some of the API responses are behind Cloudfront. But that doesn't seem to be helping the issue with long initial load times, and it introduces complexity around cache invalidation when we update. So, we should turn off Cloudfront for now.

Definition of Done:
- [ ] Every time you hit cloudfront cache, you get a miss.

**Comment by MDunitz** [comment]
See https://github.com/chanzuckerberg/single-cell-infra/pull/231
