### ISSUE TITLE
Integration: Publisher can choose a dataset from dropbox and start an upload

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#724]
Placeholder for any required FE-BE integration. 

***TEAM COMMENTS***

1. feature flags are: `cc=true` and `auth=true`
2. I think it's currently working in development env, and we're waiting to deploy to staging on Wednesday for QA!

QA steps once in staging:

1. Use this feature flag enabled staging link: https://cellxgene.staging.single-cell.czi.technology/?cc=true&auth=true
1. Log into your account
1. If you already have collections, click on My Collections link to a access a collection page
1. Once you're on a collection page, click on "Add dataset from Dropbox" to start the upload flow

![Screen Shot 2021-01-04 at 9.59.25 AM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/efd0698f-0ae0-4bd2-95ec-7b236395b683)

Thank you!

**Comment by tihuan** [comment]
I'll do this ticket along with [#642](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/642undefined)! Thank you!

**Comment by tihuan** [comment]
Deployed to staging and can confirm that it's working in staging. But @brianraymor please feel free verify too as product owner (QA steps in ticket description) 🙏 Thank you!

**Comment by tihuan** [comment]
Confirmed working in prod! Closing!
