### ISSUE TITLE
Integration: Publisher can track progress of their upload or cancel

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#725]
Placeholder for any required FE-BE integration.

**Comment by MDunitz** [comment]
Update 1/15
- @MDunitz will write an integration test for the backend (check that given a dropbox link a dataset is uploaded, correctly converted, the metadata is correctly added to the db and the dataset can be retrieved/dowloaded in its forms)
- @seve will write an integration test for the frontend using the current testing framework to ensure once uploaded the dataset information renders correctly

**Comment by tihuan** [comment]
Do we have updates on what Infra Team says about using Local Happy Path to run logged in E2E tests? Thank you!

**Comment by MDunitz** [comment]
Update 1/25
Meeting with Infra tomorrow re using local happy path for logged in e2e testing, particularly for the cicd pipeline.
Currently running into some issues with the OIDC auth process.
