### ISSUE TITLE
Design Authorization

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/corpora-data-portal#750]
The Portal and Explorer now both implement authentication using Auth0. And, when a collection is private, the Portal verifies that the requester is authenticated and is the owner of the collection.

We have a couple more authorization requirements we need to design:

1. The Explorer needs to know about authz. Currently, it checks the user's identity so it can associate user annotations with the correct user. But it also needs to apply the authorization logic that's currently in the Portal: only let the owner see private data.
2. We have a long-lived bearer token (aka obfuscated uuid) authz use case that needs to work in Portal and Explorer.

Right now all the authz information lives in the Portal, so the Explorer has no idea what an "owner" is. Also, the design needs to not harm performance in the explorer: things like caching in the instances and the CDN should still work correctly.

**Comment by bmccandless** [comment]
12/8, first version of the design doc:  https://github.com/chanzuckerberg/single-cell/pull/101/files

**Comment by maniarathi** [comment]
Closing due to roadmap changes.
