### ISSUE TITLE
[Dev Env] CORS Error: API Endpoints Not Returning `Access-Control-Allow-Origin`

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#759]
Seems like somehow Dev API is having CORS issue:

![Screen Shot 2020-12-03 at 5.41.53 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/f1c99271-fcf0-4ce9-a948-dfcc9ff5ea8c)

Thank you!

**Comment by Bento007** [comment]
The backend lambda was failing due to a bad python import. Fixed by https://github.com/chanzuckerberg/corpora-data-portal/pull/761

**Comment by tihuan** [comment]
Woohoo! Thanks so much, @Bento007 !! 🎉 🎉 🎉 🎉 🎉
