### ISSUE TITLE
Schema issues

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/corpora-data-portal#770]
This ticket is to track outstanding questions and issues with the integration schema.

Coming out of 1.1.0, there are a couple open questions:

- Should CL be an accepted ontology for `tissue`?
- There is ambiguity in the meaning of `assay`. It could mean something like "scRNA-seq" or it could mean something like "10x v3 sequencing" or some combination of those ideas for, say, CITE-seq.

**Comment by brianraymor** [comment]
Addressed in 2.0.0.
