### ISSUE TITLE
`organism_ontology_term_id` and `organism` in `uns` are insufficient in schema v1.1.0

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/corpora-data-portal#785]
Refers to [this](https://github.com/chanzuckerberg/single-cell-curation/issues/7)

Quick fix: allow for "multiple" in `organism` and empty string in `organism_ontology_term_id`

Long-term solution: move `organism_ontology_term_id` and `organism` from `uns` to `obs` in anndata

**Comment by brianraymor** [comment]
Issue moved to [chanzuckerberg/single-cell-curation #8](https://github.com/chanzuckerberg/single-cell-curation/issues/8) via [**ZenHub**](https://www.zenhub.com/)
