### ISSUE TITLE
[Dropbox Upload] Continue processing and converting datasets even if one fails

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/corpora-data-portal#797]
Currently, the behavior for uploading a dataset to the portal is that if during conversion to multiple formats, then the entire process will fail. The behavior should actually be that if one of the conversions fail, the other formats continue to progress until success or failure.

Also, ensure that the cxg conversion occurs first.

**Comment by MDunitz** [comment]
Done - refactor, wrap in try except, test skeleton
Todo - fill in tests

**Comment by MDunitz** [comment]
1/12
Done - tests of failures created with mocked out functions
question - do we want some testing of the conversion process itself?
