### ISSUE TITLE
auth0 custom login/sign up page is using old non-working tos and privacy pages

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/corpora-data-portal#801]
![Screen Shot 2021-01-07 at 1.37.27 PM.png](https://images.zenhubusercontent.com/5e31be33ed0cb222843df04c/3d630560-2ffd-4a81-8c14-e4038196119f)

**Comment by maniarathi** [comment]
This is actually a high priority bug -- pulling it into the sprint. Whoever takes this up, please estimate.

**Comment by tihuan** [comment]
Will fix it now! Thanks so much for catching this @bmccandless 🙏!!

**Comment by tihuan** [comment]
Fixed for both staging and prod! Thanks again Brian and Arathi! 😄🙏

![demo.gif](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/d7367dc8-4909-4103-ae68-13ae06fd9055)
