### ISSUE TITLE
Publish a Private Collection

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#804]
[Figma](https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Publisher-Collection?node-id=1487%3A1853)

This ticket allows a Curator to convert a private collection to a public collection

DoD:

1. Only need to add the "Publish" button and ignore adding the non functional "Delete" and "Share" buttons, which other tickets will deal with

1. Please disable the "Publish" button when the collection has one or more failed or WIP dataset. The goal is to only allow publishing a private collection with successfully uploaded dataset(s)

1. Please disable the "Publish" button if a collection doesn't have at least one successfully uploaded dataset

1. On click "Publish", show a modal with PENDING_TEXT, on click "Publish Collection", hits API [`POST /v1/collections/{project_uuid}/publish`](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/475)

1. If a collection is already Public, hide the "Publish" button (in the future, there will be a "Revise" button in its place) 

1. Write an E2E test!

**Comment by tihuan** [comment]
@brianraymor @hthomas-czi PTAL if the ticket description and DoD look good to you 🙏 

Highlighting three questions:

1. Do we want to allow publishing a private collection with NO dataset?
1. If a collection is already public, do we want to hide or disable the publish button?
1. Already asked in the [epic](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/29), but I'm assuming someone is working on the text copy for the modal?

Thank you!

**Comment by brianraymor** [comment]
_Do we want to allow publishing a private collection with NO dataset?_

No.

_If a collection is already public, do we want to hide or disable the publish button?_

Yes. I defer to @hthomas-czi on `hide` or `disable`. We'll be revisiting during the revision discussion. 

_Already asked in the epic, but I'm assuming someone is working on the text copy for the modal?_

I will draft text this afternoon for @hthomas-czi 's review.

**Comment by tihuan** [comment]
Thanks so much, @brianraymor ! Updated the ticket description 🎉

**Comment by tihuan** [comment]
Changed to `refine me` since the minor pending details shouldn't affect pointing 💪 Thanks all!

**Comment by tihuan** [comment]
Actually meant to change it to estimate me 🤦🏻‍♂️ Done!
