### ISSUE TITLE
Update DELETE /dp/v1/dataset/{dataset_uuid} 

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#828]
## Need
The frontend needs an endpoint to delete a dataset that has been uploaded to the data-portal.

## Approach
Update DELETE /dp/v1/dataset/{dataset_uuid} to delete a dataset even if it has already finished uploading
- Make the dataset unreachable by users through the backend API.
- delete all of its conversions (CXG, .rds, .loom, etc), if the upload has already completed. An upload is completed when all of the conversions are either Failed or Converted
- Delete all artifacts, deployment_directories, and processing_status from the database.
- The dataset will no longer appear in the list of datasets in a Collection.
- Only datasets that are apart of a private collection can be deleted
- DELETE /dp/v1/dataset/{dataset_uuid} always returns 202 even if the dataset does not exists or has been tombstoned.

## Definition of Done
- Tombstoned Datasets that were in the collection are not retrieved with GET collection/{collection_id}.
- Artifacts cannot be download from direct links
- Get dataset/status returns 403 for a deleted dataset
- DELETE /dp/v1/dataset/{dataset_uuid}  returns 202

**Comment by tihuan** [comment]
Hi @MDunitz ! Just wanted to double check to make sure that after completing this ticket, a user will be able to cancel/delete the dataset in any of the following phases:

1. Uploading 
1. Validating
1. Converting
1. Converted

And the first one should be working already, and this ticket will cover the rest of the phases?

Thank you!

CC: @mckinsel @brianraymor

**Comment by MDunitz** [comment]
The work in this ticket is somewhat blocked/dependent on work done in https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/875 to prevent race conditions during cancellation. Work to close that ticket will be included in the work closing this ticket leading to somewhat longer than expected dev time.
