### ISSUE TITLE
Create DELETE /dp/v1/collection/{collection_uuid}

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#830]
## Need
The frontend needs an endpoint to initiate the deletion of a collection.

## Approach

The DELETE /dp/v1/collection/{collection_uuid} will be created to make a collection unavailable to all users. 
- Make the collection unreachable by users by setting the tombstone flag of the collection and related datasets
- Delete all artifacts, deployment_directories, and processing_status from all related datasets.
- Delete all of its conversions (CXG, .rds, .loom, etc) from s3.
- The user must be the owner of the collection.
- The collection must be private to delete.

## Definition of Done
- The collection will no longer appear in the list of private Collections nor public collections
- The collection cannot be retrieved by the user
- Datasets that were in the collection cannot be retrieved.
- Artifacts cannot be download from direct links
- Get collection return 403 for a deleted collection
- Get dataset/status returns 403 for a deleted dataset
- Return status 202 to confirm the deleted or if the collection has already been deleted.

Work with the person implementing #828 to avoid duplicating work around deleting datasets. This ticket should make use of the functions written in #828 to perform deletion of datasets in the collection to be deleted.

**Comment by tihuan** [comment]
this works!
