### ISSUE TITLE
Processing Container Deployment Automation

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#845]
## Need
The processing container for adding new datasets currently require manual steps to deploy when changes occur. This process should be rolled into our existing automated deployment process. This will speed up the deployment process and provide a consistent deployment.

## Approach
The deployment must be able to update automatically, and rollback (automatically or manually).

Whenever a change is detected in the processing container code we must:
1.  bump the version number.
2. upload the container to ECS.
3. promote the container.

**Additional context**
The processing_container uses code from common. So whenever the common code is changed we must update the container.

## Definition of Done
	• A push to main, where changes have occurred in the processing container, will result in an update to the processing_container

**Comment by maniarathi** [comment]
Need to verify that all of this is being done.

**Comment by Bento007** [comment]
this is done
