### ISSUE TITLE
Upload progress is not updating

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#847]
I uploaded `7MB.h5ad`. It takes 3:19 for the upload to complete. During that time, the upload spinner is not animated and remains at 0.
I expected three minutes of 0-100 and a spinning spinner.

DoD:
1. When the `upload_status` is `WAITING`, UI should show active spinner + text: `Queued...`
2. Once the upload actually starts, show the progress percentage as we currently have

**Comment by tihuan** [comment]
Slack thread: https://chanzuckerbergteam.slack.com/archives/C01CM0MG9HB/p1611602457015300
> Hi Brian and Harley!
> 
> I saw this Upload Progress bug ticket: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/847, and wanted to double check if it’s worth optimizing the UX for a 7MB file, since I imagine the median file size should be much bigger than that?
> 
> The reason why most of the 3 mins for the upload to sit in 0% Uploading… is because most of the time it is waiting for the container to start the job. And once the job starts, it takes less than a second for the container to download the whole file. And because BE only updates its progress every 5 seconds, and FE only polls progress every 10 seconds, the next time FE receives the progress, it will be 100%. This is why we don’t see the progression such as, 0%, 14%, 27%, 49%, 79%, 100%
> 
> My experience shows that any file between 300MB to 1GB will only get 1 to 2 non-zero percentages before it completes, because the container’s download speed is too fast once it starts
> 
> For the spinner, given that uploading a known size file is a deterministic progress and we know how much progress we make, we use progress instead of spinning. However, for validation and conversion, we use spinner, since they are indeterministic!

**Comment by brianraymor** [comment]
I used the small file size as a demonstration. If I upload [1410MB](url),  then nothing happens for ~6-7 minutes. I’m not sure what’s the source of the underlying problem but as a user, I’d expect to see upload progress or animation before then.

**Comment by tihuan** [comment]
@Bento007 and @mckinsel are discussing possible solutions about the long startup time now!

**Comment by Bento007** [comment]
We could add another animation to make it seem like things are happening.

**Comment by tihuan** [comment]
@Bento007 and @mckinsel are investigating in https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/857!

**Comment by tihuan** [comment]
Yeah like spinner for `WAITING` and only start showing percentage when the upload actually starts!

**Comment by brianraymor** [comment]
@tihuan - per a conversation with @mckinsel and @hthomas-czi, the suggestion is to use `Queued` for the spinner until upload starts and returns progress. 

Addressing this issue is not be blocked by  [bug(upload): Slow upload process](https://app.zenhub.com/workspace/o/chanzuckerberg/corpora-data-portal/issues/857) while it's analysis continues. The BE may be addressed at a later time for self-publishing. The current delay is acceptable for curators.

**Comment by tihuan** [comment]
Love the solution! Thanks so much, @brianraymor 🎉 Will work on the FE change for this on Monday, so I get to finish Publish Collection today 👌
