### ISSUE TITLE
Download button is enabled for failed uploads

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#850]
I uploaded `NaN` which failed as expected. 

The Download button is enabled in both the collection view and on the landing page, but the Explore button is correctly not available in both cases.

![Screen Shot 2021-01-25 at 11.26.37 AM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/b8d90d8c-ee51-4a9f-8c7a-2908fe02bef6)

![Screen Shot 2021-01-25 at 11.23.24 AM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/d4f42197-014f-42db-a9f2-f958a090870f)

**Comment by tihuan** [comment]
Actually this is a quick fix! I'll work on that now. Thanks Brian 🎉!
