### ISSUE TITLE
bug(upload): Slow upload process

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#857]
## Describe the bug
The upload process is slow. Most time is spent in the batch process. Determine if this is something we can improve.

[Link](https://us-west-2.console.aws.amazon.com/states/home?region=us-west-2#/executions/details/arn:aws:states:us-west-2:699936264352:execution:corpora-dataset-uploader-dev-sfn:576cc617-1d29-42c1-ad02-23ef446cbcb2_1611606621) to slow step function task.

<img width="958" alt="Screen Shot 2021-01-26 at 10 45 22 AM" src="https://user-images.githubusercontent.com/1429913/105889975-9c459780-5fc3-11eb-95c7-789ff3029940.png">

### Leads
- There is a linear relationship between disk allocation for the container and startup time. This is where the disk size is defined https://github.com/chanzuckerberg/single-cell-infra/blob/main/terraform/modules/corpora/uploader/batch_launch_template.sh#L10. A solution for this could be using [EFS](https://aws.amazon.com/efs/).
- AWS batch does not start jobs as soon as they are received. Batch checks for new jobs periodically. This is a partial cause for the delay.
- It could be one process in particular in the container that is taking up the bulk of the time. If we can narrow down the scope to a particular process such as upload, validate, or convert we can refocus our effort from there.
- 
## To Reproduce
1. Start an upload process
2. Go into the AWS console and find the step function execution for the job. 
3. In the execution event history you can see the time it takes for a batch job to be submitted to complete or fail 

## Additional Context
- related to https://github.com/chanzuckerberg/corpora-data-portal/issues/847

**Comment by mckinsel** [comment]
Looked into this a bit:

- Messing around with the storage driver doesn't seem to help. You still end up with `mkfs` running for a while at the start of the job. We have room to turn down the size of the disk, but that's an incremental improvement which leaves the main issue in place.
- I think even if we solved the disk issue completely, we'd still have the same UX problem. There are a few unavoidable delays when starting a batch job: the EC2 instance has to start up, which takes ~30s and the ECS agent needs to start, which takes 30-60s. So for our most common file sizes, we still end up with a progress counter that sits confusingly at zero for a while and then suddenly jumps to 100%.

If we do find that cutting ~4 minutes of the job times would make a difference, then we can investigate EFS or shrinking/dynamically sizing the disk. In the meantime, I would favor marking this WONTFIX and adding a "Queued" status that improves the UX around the initial delay in processing.

**Comment by seve** [comment]
Closed as will not fix
