### ISSUE TITLE
feat(collection): Generalize the component view for read only access

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/corpora-data-portal#872]
## Need

Collection view should reflect the limited actions that a user with only read permissions can take

## Approach

* Remove collection actions that require write access when a user is looking at a collection they only hold read access to

## Definition of Done
*  Absence of delete, publish, and add dataset buttons on unauthorized public dataset
   * E2E tests to ensure buttons are correctly conditionally shown and hidden

**Comment by tihuan** [comment]
Ah sorry wasn't aware the PR: https://github.com/chanzuckerberg/corpora-data-portal/pull/897 is for this ticket!

Do we need another PR to add E2E tests for this 😄? Thank you!

**Comment by tihuan** [comment]
@Bento007 @seve how should we test this in staging? I can't seem to load a public collection page 🤔 Thanks!
