### ISSUE TITLE
feat(cancel): prevent race conditions

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#875]
## Need
There is a possibility for a race condition to occur when a user tries to cancel an upload. If the processing container updates the processing_status.upload_status field at the same time the user cancels their upload the cancel may not go through. There is a very low chance of this happening, and if it does the simplest solution is for the user to send another cancel request.

There is an additional dead time where cancel will have no effect. This dead space occurs between the beginning of validation to the end of conversion. If the user tries to cancel, the cancel will not be recorded until after the dead time has elapsed. After this, the user can delete the dataset.

### SQL Where Clause
- To avoid clobbering the users cancel request, add a `where` clause to the SQL query that updates the `processing_status` in the database. 
`Where dataset.tombstone != True`
- The `dataset.tombstone` field will be used to indicate to the processing_container to stop and cleanup. 
- If canceled/tombstoned, the processing_container will handle deleting any s3 object that has not yet been linked to the dataset.
- The DELETE dataset endpoint will be changed to update the `dataset.tombstone` column to `True` when a user wants to cancel or delete a dataset. This endpoint will continue to clean up and artifacts linked to the dataset.

#### Cancel Flag
The race condition can be avoided altogether by adding an additional column to processing_status. This field would be called `cancel` and would be updated by the user by making a request to cancel an upload. The processing container would read this field to check if the upload should be canceled. 

## Definition of Done
- Modify the processing container to read `dataset.tombstone` to determine if the upload has been canceled.
- DELETE dataset/dataset_uuid will tombstone a dataset.

**Comment by MDunitz** [comment]
Closed with [delete dataset ](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/878) work
