### ISSUE TITLE
Pin tiledb version in processing image

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/corpora-data-portal#894]
tiledb arrays are not backward compatible. So if a cxg object is written by tiledb version x it may not be readable by version y if x > y.

The version of tiledb in hosted cellxgene is pinned in single-cell-infra (currently 0.7.4). The version that's run in the processing image is whatever's specified in cellxgene's requirements.txt. That pretty much specifies the latest, which is now 0.7.5.

So right now, a new cxg created by the processing image cannot be read by hosted cellxgene. You get a 400.

We should pin the version in the processing image so we can make sure versions don't get incremented only in the processing image.

**Comment by tihuan** [comment]
@mckinsel how do we QA this in staging? Thank you!

**Comment by mckinsel** [comment]
For future reference, it's in this Makefile: https://github.com/chanzuckerberg/corpora-data-portal/blob/main/backend/processing_image/Makefile

You set your DEPLOYMENT_STAGE and then make build, make push, make promote
