### ISSUE TITLE
[FE] Create publisher geneset tab 

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/corpora-data-portal#912]
See https://www.figma.com/file/TKV4sJ00zWobEFkaNgklC3/Gene-Sets?node-id=178%3A1887

![Screen Shot 2021-02-17 at 11.57.20.png](https://images.zenhubusercontent.com/5b4523ca3f1e7333c932b3b1/b72d3347-180d-4f8a-9df6-e64b74112002)

@tihuan please update with FE details

**Comment by MDunitz** [comment]
Move actions button component for reuse
Need to create new grid

buttons will not be functional

How to handle gene sets that arent assigned to any datasets
- warn on publish (similar to delete alert) -- will be handled in publish ticket

**Comment by brianraymor** [comment]
Per the [simplification](https://docs.google.com/document/d/15rQuHfjezUo0RcJ3xVoRuWLP6OQ9bqiGDanmczehJtE/edit#heading=h.h1v05pg02lhb) of gene sets, UX linking is no longer required. Closing.
