### ISSUE TITLE
[SPIKE] Determine time requirements for uploading a 50mb geneset file and converting to a javascript object  for validation 

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/corpora-data-portal#916]
Before starting on [[FE] Gene set upload flow #913](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/913) we want to ensure that it is possible to parse and validate a large gene set file on the frontend without severely degrading the user experience

**Comment by tihuan** [comment]
Good news!

Parsing and converting a 80MB CSV to JSON takes around 4 seconds 🤩 So I think that's performant enough to do validation in the frontend?

CSV 1: 692KB: https://www.dropbox.com/s/9xuwq7l7sm1lm8l/Film_Locations_in_San_Francisco.csv?dl=0
CSV 2: 84.1MB: https://www.dropbox.com/s/jfrgq647rzjxv3v/Registered_Business_Locations_-_San_Francisco.csv?dl=0 

Example using 692KB CSV file:
![Screen Shot 2021-02-23 at 4.28.56 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/6c2ebc33-3aa0-448c-85b5-39344b63b50a)

Branch is `thuang-916-import-csv` if you wanna test it yourself on different machines!

Steps:
1. Download the branch
1. Run `npm i && npm run dev`
1. Go to `localhost:3000` and you'll see the upload input field, select a CSV file!
1. Wait till you see the alert 👌 

Thank you!
