### ISSUE TITLE
bug(no processing_status): datasets without processing_status cause error

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#919]
## Describe the bug
The frontend expects all dataset to have a processing_status that indication the upload and processing of the dataset was successful. A legacy dataset that was updated before processing status was implemented does not have a processing status. This causes the collections page to not load for the legacy datasets.

The fix is to write a database migration that adds a processing_status to any dataset that does not have a processing_status. The processing_status must indicate the dataset uploaded successfully.

## To Reproduce
1. Go to a legacy collection page 
2. The page will not load

## Expected behavior
1. The legacy collection pages should load.

**Comment by MDunitz** [comment]
get list of datasets without processing statuses
```
select id FROM dataset where id not in (select dataset_id from dataset_processing_status);
```

**Comment by MDunitz** [comment]
store ids from above query as dataset ids and run
```
from corpora.common.corpora_orm import *
from corpora.common.utils.db_session import db_session_manager
processing_status = {
    "upload_status": UploadStatus.UPLOADED,
    "upload_progress": 100,
    "processing_status": ProcessingStatus.SUCCESS,
}

def set_status(dataset_id, session):
    db_status = DbDatasetProcessingStatus(dataset_id=dataset_id, **processing_status)
    session.add(db_status)

with db_session_manager() as session:
     for id in dataset_ids:
         set_status(id, session)
     session.commit()
```
- [ ] run in dev
- [ ] run in staging
- [ ] run in pro

**Comment by MDunitz** [comment]
Check that the fix worked in prod here 
https://cellxgene.staging.single-cell.czi.technology/collections/120c8261-a137-44ac-97ca-897eb8916894
