### ISSUE TITLE
Create POST endpoint to create geneset dataset links

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/corpora-data-portal#928]
## Need create POST endpoint /dp/v1/dataset/{dataset_uuid}/genesets
- Expected body {“add”: [list of geneset uuids], “remove”: [list of geneset uuids]}
- Return list of genesets that belong to the dataset (name, description, uuid)

## Approach
- Only possible if the linked collection is private
-  The request body should contain a list of geneset_uuids to link to the dataset to (under add)
-  In the backend retrieve a list of genesets the dataset is already linked to (from the db), if not already linked for genesets in request body create a row in the geneset_dataset_link table with the geneset and dataset ids

## DOD
- If no dataset exists return 403
- If user is not owner of linked collection return 403
- If linked collection is public return 403
- If geneset does not exist or does not belong to the collection return 404 code with message “Invalid gene sets” - if FE sees that error message it will invalidate the geneset cache

**Comment by Bento007** [comment]
### Questions
1. If we remove genesets that don't exists do we fail silently? It makes sense to throw a 404 if we try adding a geneset that doesn't exist.
1. What do we return in the positive response?
1. Is this an all or nothing operation? If things partial fail do we roll back all of the changes?
1. What is the response if all of the genesets exist in the dataset?

**Comment by maniarathi** [comment]
1. We throw a 404.
2. 200. 
3. For now, it's an all-or-nothing operation, but we should check with Harley and Brian. @hthomas-czi @brianraymor 
4. Should be a 200.

**Comment by brianraymor** [comment]
3. all-or-nothing.
