### ISSUE TITLE
Integration Tests

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#940]
- [x] Create a collection
- [x] Delete a collection
- [x] Publish a collection
- [x] upload a dataset
- [x] delete a dataset
- [ ] delete a pending dataset
- [ ] upload a bad dataset
- [ ] delete a bad dataset
- [x] cannot retrieve a tombstoned collection
- [ ] cannot retrieve a tombstoned dataset
- [x] login
- [ ] logout
- [ ] list owners collections
- [ ] only owner can delete and upload datasets to a collection

## Definition of Done
- [ ] Write an integration test that run on a deployed environment.
- [ ] Ensure that cleanup happens after the test.

**Comment by maniarathi** [comment]
We should ensure that these use cases are covered both on the frontend and backend.

**Comment by Bento007** [comment]
I'll do the backend version.

**Comment by tihuan** [comment]
Actually writing the test for uploading a dataset and then cancelling it will take a few more hours, which I think is lower priority than working on the validation script. So I just sent out a PR for the E2E test fixes and will stop working on this ticket for now! Thank you!

https://github.com/chanzuckerberg/corpora-data-portal/pull/950

**Comment by Bento007** [comment]
created backend issue https://github.com/chanzuckerberg/corpora-data-portal/issues/970

**Comment by tihuan** [comment]
FE issue here! https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/971

Will close this ticket now 🤩 Thank you!
