### ISSUE TITLE
feat: PUT /collections/{collection_uuid}

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/corpora-data-portal#951]
## Need
As a creator of a private collection, I would like to update fields related to a collection and update, add, and delete links associated with the collection.

## Approach
Add a new API `PUT /collections/{collection_uuid}`. This API will take all of the parameters used in `POST /collections`. `collection_uud` will also need to be in the request so we know what collection to update. `link_uuid` may also need to be in the request body so we know which table entries to modify.

On the backend, the request body from `PUT /collections/{collection_uuid}` will be used to update the collections and links table. For the links table, some links will need to be removed, updated, or created.

The backend will respond with the collection with the same response format as `GET /collection/{collection_uuid}`.

Regarding updating links, it would be easier to delete all of the links and recreated all of the links in the requests. This simplified the processes of implementing separate create, update and delete functions. This works as long as the `link_uuid` is not needed by any other features.

## Definition of Done
- New API `PUT /collections/{collection_uuid}` is added to openapi.yml specification.
- The user must be the owner of the collection to modify
- The collection must be private to modify.
- A user can update a private collection info
- A user can add, remove, and update links in a private collection

**Comment by tihuan** [comment]
@Bento007 how should we verify this works in staging? Thank you!

**Comment by tihuan** [comment]
No easy way to test the API in staging. But moving to prod ready, since it's not using facing yet anyway!

**Comment by tihuan** [comment]
skipping verification
