### ISSUE TITLE
[FE]  Data Consumers can use the tab view to explore Datasets and Gene Sets in a Collection

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/corpora-data-portal#956]
Need - read only version of the tab view of Datasets and gene sets in a collection that data consumers can explore
See - https://www.figma.com/file/TKV4sJ00zWobEFkaNgklC3/Gene-Sets?node-id=188%3A4632

![Screen Shot 2021-03-02 at 11.07.39.png](https://images.zenhubusercontent.com/5b4523ca3f1e7333c932b3b1/3e4c7c56-33d7-4335-8f49-188f96d6cc19)

**Comment by brianraymor** [comment]
Per the [simplification](https://docs.google.com/document/d/15rQuHfjezUo0RcJ3xVoRuWLP6OQ9bqiGDanmczehJtE/edit#heading=h.h1v05pg02lhb) of gene sets, UX linking is no longer required. Closing.
