### ISSUE TITLE
Missing Contact information in Collection Dataset view

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#959]
See this [dataset view](https://cellxgene.cziscience.com/collections/367d95c0-0eb0-4dae-8276-9407239421ee). There is no Contact information, although Ed Lein appears on the collections view:

![Screen Shot 2021-03-02 at 4.53.55 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/8d7308a5-d1a9-42b0-b4c0-e3775547a6fe)

The [Figma](https://www.figma.com/file/6wPUe08qSM8V9G2G0UfYOP/Consumer-Collection?node-id=45%3A615) includes the Contact. I'm assuming that it's modeled as mailto: to include the email address. @hthomas-czi can you confirm? 

![Consumer – Dataset View.jpg](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/450c9f80-5144-48c9-991d-c490652d0117)

The Contact format should also be consistent between views.

**Comment by hthomas-czi** [comment]
> The [Figma](https://www.figma.com/file/6wPUe08qSM8V9G2G0UfYOP/Consumer-Collection?node-id=45%3A615) includes the Contact. I'm assuming that it's modeled as mailto: to include the email address. @hthomas-czi can you confirm?

That's right, @brianraymor

**Comment by tihuan** [comment]
![Screen Shot 2021-03-18 at 12.36.25 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/fc31cf12-0d6e-4105-8a75-4da52c244e32)

@brianraymor @Bento007 should we hide the contact field if the value is not available? Thanks!

https://cellxgene.staging.single-cell.czi.technology/collections/6bcda94e-8988-49a6-8b7c-cbd1a211bdd0

**Comment by tihuan** [comment]
I don't think this is a prod launch blocker, but if it is, we can fix this easily before prod deployment today too!

CC: @brianraymor

**Comment by brianraymor** [comment]
Arggh. In the future, it would raise an exception if this field was empty since it's required. The current issue is another artifact of the database not being updated with the transition between the early versions of the schema. We cannot correct that set of problems until revisions of public collections is available. Pablo has already prepared the datasets for re-ingestion.

Still, I'd prefer not to see an empty Contact now. 

@hthomas-czi - do you have a position?

**Comment by hthomas-czi** [comment]
I agree @brianraymor. Contact should be hidden if the field is null (even though it shouldn't be).

**Comment by tihuan** [comment]
OK! I'll send out a PR now to hide the field when value is not present! Thanks all!

**Comment by tihuan** [comment]
Confirmed the contact is no longer showing when unavailable! Moving to ready for prod 👍 

![Screen Shot 2021-03-18 at 3.12.20 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/5a6b5efa-adce-4750-88e5-7ae5923ed1db)

https://cellxgene.staging.single-cell.czi.technology/collections/6bcda94e-8988-49a6-8b7c-cbd1a211bdd0

**Comment by tihuan** [comment]
Works in prod!

https://cellxgene.cziscience.com/collections/24d42e5e-ce6d-45ff-a66b-a3b3b715deaf

![Screen Shot 2021-03-18 at 3.47.29 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/a4cd6602-3a93-435f-b4dd-8d119453b831)
