### ISSUE TITLE
Design schema to represent data processing and its outputs

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/corpora-data-portal#96]
The existing schema that has been used for the processes and outputs of the processing pipelines (essentially, everything in the graph from fastqs to matrices) is insufficient and inconsistent with the rest of the schema.
Especially important to update this and tighten it given the inclusion of metadata coming in from contributor processing.
I don't anticipate entities/linking changing, but the properties of each entity will be overhauled.

**Comment by mweiden** [comment]
@jahilton nudge me to get some prep work going on this as soon as you have a draft 🎏

**Comment by ambrosejcarr** [comment]
I'm happy to pitch in here in concepts, and on importance based tiering of
fields.

There will also be questions about multi modal integration -- if we have
DNA accessibility and RNA expression data, must those two have partially
shared schema to align? An interesting research topic.
