### ISSUE TITLE
Incorrect DOI format in Collection Dataset view

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#960]
In Collection view, it's the DOI as a link as illustrated in the [Figma](https://www.figma.com/file/6wPUe08qSM8V9G2G0UfYOP/Consumer-Collection?node-id=478%3A0):

![Screen Shot 2021-03-02 at 4.53.55 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/6d4195a2-b2c6-4c6c-a662-50f88fed2ba4)

In Dataset view, it appears as an anchor link - `doi.org` which is incorrect. See the [Figma](https://www.figma.com/file/6wPUe08qSM8V9G2G0UfYOP/Consumer-Collection?node-id=45%3A615).

![Screen Shot 2021-03-02 at 4.59.34 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/726410f1-c26c-42a2-92d5-9f22f33e0337)

**Comment by Bento007** [comment]
This one should be fixed by https://github.com/chanzuckerberg/corpora-data-portal/issues/955

**Comment by brianraymor** [comment]
... because it will default to the format specified in the Figma if an anchor element is not entered by the user?

**Comment by brianraymor** [comment]
Closing per agreement with @Bento007 to address in related issue while he _has his hands in the code_.
