### ISSUE TITLE
feat(tests): Add safe auth testing to frontend integration testing

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/corpora-data-portal#969]
## Need
Frontend authentication integration test(s) requires an elegant solution to fetch credentials from AWS Secret Manager

## Approach

**Describe the solution you'd like**
* Import and utilize [aws-sdk](https://github.com/aws/aws-sdk-js) to fetch auth credentials off of Secrets Manger and inject them into process.env  in our global setup file
* Alter login helper to use these saved auth details

## Definition of Done
Test successfully logs in and out of Auth0 and OIDC mock without leaking Auth0 credentials

-----

### (seve)Comment from : #998 

> This is almost ready for merge.  The tests currently pass on our deployments, but need some work to work on local-dev. 
> 
> LocalStack SecretsManager is successfully creating and serving the secrets needed to log into the mock OIDC, but we're having difficulty getting the frontend container to communicate with the OIDC container.  We're able to get communication working between the frontend and backend containers by replacing the config.js with local-docker.js via the `smoke-test-with-local-dev` Makefile target.  This changes the api url from localhost:5000 to backend:5000.  The difficulty with OIDC stems from the fact that the backend provides the URL to connect to the OAuth service and that URL is loaded into the backend through the `setup_dev_data` script when we run `make local-init`.
> 
> _Now that I'm looking at the commands behind that target, there might be a chance that we can run `export OIDC_BROWSER_URL=http://oidc` inside the backend container before we run the test and then replace it back with `https://localhost:8443` after the tests have completed_
> 
> I've changed/created a few Makefile targets for testing, but haven't put enough thought into the workflow to be certain they'll end up on main as is. Right now the workflow is calling `make e2e-on-local-dev` from `/frontend` with the containers already running.
> 
> I last left off on talking with Infra regarding setting all the containers to `network_mode: host` to remove the need to use the container name when connecting between containers.  This means we won't be replacing instances of `localhost` with `<container-name>`.
> 
> After this PR is merged we need to port over the setup and utilization code over to explorer.  This will just be including `    "aws-sdk/client-secrets-manager` as a devDep and loading in the secret from aws (we won't be needing any connection to localstack since local-dev doesn't support explorer).  This secret loading in will be in a new file that will be referenced in `e2eJestConfig.json:5` and then we'll grab the username/pass from env in`login()` in `cellxgeneActions.js` 
> 
> Once both explorer and data portal PRs are merged, the ticket can be closed 🥳 
> 
> P.S. The estimation for the ticket has been updated and the remaining work is pointed at a 2

**Comment by maniarathi** [comment]
Can this be moved to Ready for QA?
