### ISSUE TITLE
Update feature flags to work on ALL routes

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#983]
Currently feature flag `gs` only works on `/collections/:id` route, and doesn't work on homepage route `/`, because the collection page is the only page reading `gs` flag

We should update FE to detect feature flags on all routes, which means adding the related code in `frontend/src/components/AppContainer/index.tsx`

DoD:

1. Feature flags should be set on ALL routes, regardless of which page reads it. For example, homepage route `/?gs=true` should persist the feature flag in `localStorage` even though homepage doesn't use `gs` feature flag

1. Consolidate launched features under `curator=true` see https://github.com/chanzuckerberg/corpora-data-portal/issues/983#issuecomment-800480654 for explanation and examples

**Comment by brianraymor** [comment]
There was a rationale to define separate feature flags for `cc` (Create Collection) and `auth` in the past. Moving forward, I would recommend that we merge released features to one feature flag such as `curator=true`.  (Or perhaps something slightly harder to guess) Features under development would still have an internal feature flag. When the feature is ready for release to curators, then the internal feature flag would be deprecated and replaced by `curator`.

For example:

1. `?cc=true&auth=true` -> `?curator=true`
2. Gene sets in development -> `?curator=true&gs=true`
3. Gene sets released to curators -> `?curator=true` which now includes create collections, auth, gene sets
4. Revision in development -> `?curator=true&revision=true`
5. Revision released to curators -> `?curator=true` which now includes create collections, auth, gene sets, revise collections

@maniarathi and @tihuan - thoughts?

**Comment by maniarathi** [comment]
LGTM!

**Comment by tihuan** [comment]
Thanks for the great idea @brianraymor ! Added that as a DoD item in the description 🔥

**Comment by brianraymor** [comment]
We may want to make the change once gene sets are ready for release. That way, we're sharing a new feature when we require the curators to make the change.
