### ISSUE TITLE
A private collection shared with a reviewer is not read-only?

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#987]
If a curator shares the link to a private collection with reviewers, the reviewers _apparently_ have owner privileges, the UX is enabled for:

* `Add` a dataset
* `Delete` a dataset
* `Publish` the collection 

I write _apparently_ because I did not attempt to perform those actions. Perhaps the operation would fail.

The portal must differentiate between **Owner | Private | Shared link** (read/write) and **Private | Shared link** (read-only). 

I shared a screenshot on [**eng**](https://chanzuckerbergteam.slack.com/archives/C01CPJURT0S/p1615936099010700) but will not reproduce here because the collection has not been published.

**Comment by Bento007** [comment]
Attempting to add a new dataset to a collection using the fronted when the collection is not owned causes a 403 to be returned, which is the excepted response in this case. This bug with the way the frontend is rendering the private collection.

**Comment by tihuan** [comment]
@Bento007 will take this! Thank you!

**Comment by tihuan** [comment]
This will be done in https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/124

**Comment by maniarathi** [comment]
Verified in prod so closing.
