### ISSUE TITLE
Using auto-fill for Contact in Create Collection sometimes disables the Create button ?

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/corpora-data-portal#988]
Contact was auto-filled on chrome. `Create` is disabled:

![Screen Shot 2021-03-16 at 6.05.01 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/ef80ae5d-c9fb-48e5-841b-6a2e56da24e2)

Manually typed in the same contact information which enables `Create`:

![Screen Shot 2021-03-16 at 6.05.27 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/c0a7a8fd-0d1c-432d-bd3b-9f8c58f2e973)

**Comment by maniarathi** [comment]
@brianraymor -- I tagged @tihuan about this in his PR but this is still an open problem in prod. Chrome does some weird overrides such that even though autocomplete is disabled, Chrome still allows for auto-complete. This will likely require some more digging into either to turn off auto-complete or to allow auto-complete so does it make sense to label this as a spike and move it to the product backlog to be prioritized later?

**Comment by brianraymor** [comment]
Also see [Turning Off Autocomplete in Chrome with React](https://medium.com/paul-jaworski/turning-off-autocomplete-in-chrome-ee3ff8ef0908)

**Comment by tihuan** [comment]
Morning all! I found another 2021 solution Tuesday night and sent out a new PR for it 😄 

https://github.com/chanzuckerberg/corpora-data-portal/pull/1073

https://stackoverflow.com/questions/12374442/chrome-ignores-autocomplete-off/30873633#30873633

PTAL thank you!

**Comment by maniarathi** [comment]
Thank you @tihuan !!
